// 인물관계도 v2.2 — 생성물. tools/relations_diagram_gen.py 가 만든다(KO/JA 록스텝). 손으로 고치지 않는다.
// 세 차례의 계승전쟁을 축으로 네 장: ① 1차 ② 2차 ③ 3차(금서전쟁) ④ 그 뒤.
#import "@preview/cetz:0.4.2": canvas, draw

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[第一次継承戦争 ―― アンハルト家の枝])
    content((8.8, -0.8), name: "root", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[共通始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ホーエンアスカニアの共通始祖]]))
    content((5.4, -2.3), name: "anh0", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト中始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[共通始祖の一人息子]]))
    content((12.4, -2.3), name: "asc0", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア中始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[共通始祖の末娘 · この代から指名相続]]))
    content((5.4, -3.8), name: "g3", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト三代当主] \ #text(size: 5.1pt, fill: gray.darken(40%))[十九人の息子]]))
    content((12.4, -3.8), name: "asc", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア家門] \ #text(size: 5.1pt, fill: gray.darken(40%))[→ 第二次は旧宗家側（次の図）]]))
    content((1.7, -5.5), name: "f1", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[長男〜五男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争 · 断絶 †]]))
    content((4.2, -5.5), name: "f2", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[六男〜十二男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争 · 断絶 †]]))
    content((6.9, -5.5), name: "f3", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[十三・十四・十九男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争の一方]]))
    content((9.6, -5.5), name: "f4", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[十五男〜十八男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争の一方]]))
    content((3.0, -7.4), name: "main", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト旧宗家・新宗家] \ #text(size: 5.1pt, fill: gray.darken(40%))[十三男の系譜 · ハインリヒの家（旧宗家）→ ハルの家（新宗家）]]))
    content((7.0, -7.4), name: "meissen", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン] \ #text(size: 5.1pt, fill: gray.darken(40%))[十四男の系譜]]))
    content((10.4, -7.4), name: "witt", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ヴィッテンベルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[十九男の系譜 · のちの大公家]]))
    content((13.4, -7.4), name: "f17", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[十七男系譜の分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[長（女性・前科者）―― 終戦を妨げる]]))
    content((15.9, -7.4), name: "unk", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[何男から出たか定めない家々] \ #text(size: 5.1pt, fill: gray.darken(40%))[モード家 · メル家 · ホーエンシュタウフェン宗家・ヘヒンゲン分家・アントノフ分家 ·（ニーダーヴィッテンベルクは十九男から更に分かれた枝）]]))
    content((5.6, -9.0), name: "thal", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン＝タールベルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[初代当主の四男 → のちのタールベルク家]]))
    content((8.8, -9.0), name: "blum", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン＝ブルーメンタール] \ #text(size: 5.1pt, fill: gray.darken(40%))[五男 → のちのブルーメンタール家]]))
    content((1.4, -9.0), name: "arvid", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンアルヴィートブルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主の異母弟 → 第二次の反対側]]))
    line("root", "anh0", stroke: (paint: black, thickness: .7pt))
    lbl((7.10, -1.55), [一人息子])
    line("root", "asc0", stroke: (paint: black, thickness: .7pt))
    lbl((10.60, -1.55), [末娘])
    line("anh0", "g3", stroke: (paint: black, thickness: .7pt))
    line("asc0", "asc", stroke: (paint: black, thickness: .7pt))
    line("g3", "f1", stroke: (paint: black, thickness: .7pt))
    line("g3", "f2", stroke: (paint: black, thickness: .7pt))
    line("g3", "f3", stroke: (paint: black, thickness: .7pt))
    line("g3", "f4", stroke: (paint: black, thickness: .7pt))
    line("f3", "main", stroke: (paint: black, thickness: .7pt))
    lbl((4.95, -6.45), [十三男])
    line("f3", "meissen", stroke: (paint: black, thickness: .7pt))
    lbl((6.95, -6.45), [十四男])
    line("f3", "witt", stroke: (paint: black, thickness: .7pt))
    lbl((8.65, -6.45), [十九男])
    line("f4", "f17", stroke: (paint: black, thickness: .7pt))
    lbl((11.50, -6.45), [十七男])
    line("meissen", "thal", stroke: (paint: black, thickness: .7pt))
    lbl((6.30, -8.20), [四男])
    line("meissen", "blum", stroke: (paint: black, thickness: .7pt))
    lbl((7.90, -8.20), [五男])
    line("main", "arvid", stroke: (paint: black, thickness: .7pt))
    lbl((2.20, -8.20), [異母弟])
    content((8.8, -0.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[共通始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ホーエンアスカニアの共通始祖]]))
    content((5.4, -2.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト中始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[共通始祖の一人息子]]))
    content((12.4, -2.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア中始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[共通始祖の末娘 · この代から指名相続]]))
    content((5.4, -3.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト三代当主] \ #text(size: 5.1pt, fill: gray.darken(40%))[十九人の息子]]))
    content((12.4, -3.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア家門] \ #text(size: 5.1pt, fill: gray.darken(40%))[→ 第二次は旧宗家側（次の図）]]))
    content((1.7, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[長男〜五男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争 · 断絶 †]]))
    content((4.2, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[六男〜十二男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争 · 断絶 †]]))
    content((6.9, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[十三・十四・十九男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争の一方]]))
    content((9.6, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[十五男〜十八男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争の一方]]))
    content((3.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト旧宗家・新宗家] \ #text(size: 5.1pt, fill: gray.darken(40%))[十三男の系譜 · ハインリヒの家（旧宗家）→ ハルの家（新宗家）]]))
    content((7.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン] \ #text(size: 5.1pt, fill: gray.darken(40%))[十四男の系譜]]))
    content((10.4, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ヴィッテンベルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[十九男の系譜 · のちの大公家]]))
    content((13.4, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[十七男系譜の分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[長（女性・前科者）―― 終戦を妨げる]]))
    content((15.9, -7.4), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[何男から出たか定めない家々] \ #text(size: 5.1pt, fill: gray.darken(40%))[モード家 · メル家 · ホーエンシュタウフェン宗家・ヘヒンゲン分家・アントノフ分家 ·（ニーダーヴィッテンベルクは十九男から更に分かれた枝）]]))
    content((5.6, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン＝タールベルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[初代当主の四男 → のちのタールベルク家]]))
    content((8.8, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン＝ブルーメンタール] \ #text(size: 5.1pt, fill: gray.darken(40%))[五男 → のちのブルーメンタール家]]))
    content((1.4, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンアルヴィートブルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主の異母弟 → 第二次の反対側]]))
    line((0.4, -9.95), (1.0, -9.95), stroke: (paint: black, thickness: .7pt))
    content((1.1, -9.95), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -9.95), (3.15, -9.95), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -9.95), (3.15, -9.95), stroke: (paint: white, thickness: .8pt))
    content((3.25, -9.95), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -9.95), (5.299999999999999, -9.95), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -9.95), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -9.95), (7.449999999999999, -9.95), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -9.95), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -9.95), (9.6, -9.95), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -9.95), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -9.95), (11.75, -9.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -9.95), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -9.95), (13.9, -9.95), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -9.95), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -9.95), (16.05, -9.95), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -9.95), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図① 第一次継承戦争 ―― アンハルト家の枝（2-2・5-6、設定集専用）。三代当主の十九人の息子が四つの側で戦い、長男〜十二男の系譜は断絶した。残った枝がのちの二つの統治家・大公家・旧宗家と新宗家になる。何男から出たか定めない家々は右に別に。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    rect((0.2, -0.4), (8.6, -6.2), fill: rgb("#f4f8f5"), stroke: none)
    content((8.45, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[旧宗家側 ―― 進歩貴族・ジェントリ・ヨーマン・ブルジョワ連合（戦勝）])
    rect((9.0, -0.4), (17.6, -6.2), fill: rgb("#fdf2f0"), stroke: none)
    content((17.450000000000003, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[反対側 ―― 保守的貴族の連合])
    rect((0.2, -7.6), (17.6, -12.4), fill: rgb("#f7f7f7"), stroke: none)
    content((17.450000000000003, -7.68), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[そのあとに来たもの])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[第二次継承戦争 ―― 二つの側、そしてそのあとに来たもの])
    content((3.3, -1.5), name: "issue", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[旧宗家当主の第一子] \ #text(size: 5.1pt, fill: gray.darken(40%))[継承法の空白 · その空白を埋めた差別が戦争の原因]]))
    content((1.6, -3.0), name: "lord", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト旧宗家当主] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハルの曾祖父]]))
    content((1.6, -4.7), name: "gf", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの祖父] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一子の末弟 · 次の当主]]))
    content((4.3, -3.0), name: "gd1", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[ヴィッテンベルク女大公] \ #text(size: 5.1pt, fill: gray.darken(40%))[一等功臣 → 大公位 · 先々代（初代）]]))
    content((7.2, -3.0), name: "asc", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア家門] \ #text(size: 5.1pt, fill: gray.darken(40%))[家門全体が参戦 · ブルーメンタール分家を全滅寸前まで]]))
    content((4.3, -4.7), name: "maudmel", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード家・メル家] \ #text(size: 5.1pt, fill: gray.darken(40%))[戦勝側でありながら戦中すでに壊滅に準ずる打撃]]))
    content((7.2, -4.7), name: "anton", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン＝アントノフ・アントノヴァ] \ #text(size: 5.1pt, fill: gray.darken(40%))[生存]]))
    content((11.6, -1.3), name: "arvid", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアルヴィートブルク分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主の異母弟に従う · 禁書を「編む」· 老若男女全滅 †]]))
    content((11.6, -3.0), name: "stauf", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン宗家] \ #text(size: 5.1pt, fill: gray.darken(40%))[全滅 †]]))
    content((15.0, -3.0), name: "hech", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン＝ヘヒンゲン分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[勢力を減らしつつ生存]]))
    content((11.6, -4.7), name: "thal", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[土壇場に逃れて姓を替える]]))
    content((15.0, -4.7), name: "blum", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[土壇場に逃れて姓を替える]]))
    content((8.8, -6.9), name: "law", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[絶対的長子相続] \ #text(size: 5.1pt, fill: gray.darken(40%))[性別を問わず · 「選べないように」· 直後に制定]]))
    content((11.6, -8.5), name: "regT", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク政権（こちらの旧体制）] \ #text(size: 5.1pt, fill: gray.darken(40%))[のちにクーデターで政権 · のちの首班タールベルク・ヴァルター・ハラルト六世]]))
    content((15.4, -8.5), name: "regB", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール政権（向こうの旧体制）] \ #text(size: 5.1pt, fill: gray.darken(40%))[クーデターで政権 · 首班ブルーメンタール・ヨアヒム・ジギスムント ―― 虐殺を命じる]]))
    content((13.5, -10.3), name: "book", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[禁書の盗難] \ #text(size: 5.1pt, fill: gray.darken(40%))[二つの家のうち一方 ―― 定めない → 第三次の導火線]]))
    content((7.4, -8.5), name: "massA", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア虐殺] \ #text(size: 5.1pt, fill: gray.darken(40%))[政権直後の仕返し · 家門全体 †]]))
    content((4.2, -8.5), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[唯一の生存者 · 純粋な母系七代の分家 · 大公国を経てこちらへ]]))
    content((1.3, -8.5), name: "duke2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[先代大公（第二代）] \ #text(size: 5.1pt, fill: gray.darken(40%))[遺骨を葬り · 出生記録を保管]]))
    content((7.4, -10.3), name: "coup", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード家・メル家の逆クーデター] \ #text(size: 5.1pt, fill: gray.darken(40%))[鎮圧 → 報復の虐殺 · 一家族ずつ脱出]]))
    content((4.2, -10.3), name: "exile", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[亡命した二つの家族] \ #text(size: 5.1pt, fill: gray.darken(40%))[こちらで極度の貧困 · 二人を残して餓死 †]]))
    content((1.3, -10.3), name: "ariLaura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ · メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[亡命後こちらで生まれる · 各家の最後]]))
    content((8.8, -11.9), name: "trial", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[戦犯裁判の証言] \ #text(size: 5.1pt, fill: gray.darken(40%))[二つの虐殺が世界に明らかになる · アリ・ラウラもそのとき初めて知る（次の図）]]))
    line("issue", "lord", stroke: (paint: black, thickness: .7pt))
    line("lord", "gf", stroke: (paint: black, thickness: .7pt))
    lbl((1.60, -3.85), [末弟])
    line("issue", "arvid", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((7.45, -1.40), [外すべきだとした側])
    line("thal", "regT", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("blum", "regB", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("regB", "massA", stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((11.40, -8.50), [政権を握るや否や])
    line("massA", "fran", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((5.80, -8.50), [一人だけ生き残る])
    line("duke2", "fran", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    line((13.7, -9.05), (9.0, -10.3), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((11.35, -9.68), [報復の虐殺])
    line("coup", "exile", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("exile", "ariLaura", stroke: (paint: black, thickness: .7pt))
    line((7.4, -9.05), (7.4, -9.6), (9.6, -9.6), (9.6, -11.4), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line((8.0, -10.85), (8.8, -11.4), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((3.3, -1.5), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[旧宗家当主の第一子] \ #text(size: 5.1pt, fill: gray.darken(40%))[継承法の空白 · その空白を埋めた差別が戦争の原因]]))
    content((1.6, -3.0), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト旧宗家当主] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハルの曾祖父]]))
    content((1.6, -4.7), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの祖父] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一子の末弟 · 次の当主]]))
    content((4.3, -3.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[ヴィッテンベルク女大公] \ #text(size: 5.1pt, fill: gray.darken(40%))[一等功臣 → 大公位 · 先々代（初代）]]))
    content((7.2, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア家門] \ #text(size: 5.1pt, fill: gray.darken(40%))[家門全体が参戦 · ブルーメンタール分家を全滅寸前まで]]))
    content((4.3, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード家・メル家] \ #text(size: 5.1pt, fill: gray.darken(40%))[戦勝側でありながら戦中すでに壊滅に準ずる打撃]]))
    content((7.2, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン＝アントノフ・アントノヴァ] \ #text(size: 5.1pt, fill: gray.darken(40%))[生存]]))
    content((11.6, -1.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアルヴィートブルク分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主の異母弟に従う · 禁書を「編む」· 老若男女全滅 †]]))
    content((11.6, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン宗家] \ #text(size: 5.1pt, fill: gray.darken(40%))[全滅 †]]))
    content((15.0, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン＝ヘヒンゲン分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[勢力を減らしつつ生存]]))
    content((11.6, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[土壇場に逃れて姓を替える]]))
    content((15.0, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[土壇場に逃れて姓を替える]]))
    content((8.8, -6.9), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[絶対的長子相続] \ #text(size: 5.1pt, fill: gray.darken(40%))[性別を問わず · 「選べないように」· 直後に制定]]))
    content((11.6, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク政権（こちらの旧体制）] \ #text(size: 5.1pt, fill: gray.darken(40%))[のちにクーデターで政権 · のちの首班タールベルク・ヴァルター・ハラルト六世]]))
    content((15.4, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール政権（向こうの旧体制）] \ #text(size: 5.1pt, fill: gray.darken(40%))[クーデターで政権 · 首班ブルーメンタール・ヨアヒム・ジギスムント ―― 虐殺を命じる]]))
    content((13.5, -10.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[禁書の盗難] \ #text(size: 5.1pt, fill: gray.darken(40%))[二つの家のうち一方 ―― 定めない → 第三次の導火線]]))
    content((7.4, -8.5), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア虐殺] \ #text(size: 5.1pt, fill: gray.darken(40%))[政権直後の仕返し · 家門全体 †]]))
    content((4.2, -8.5), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[唯一の生存者 · 純粋な母系七代の分家 · 大公国を経てこちらへ]]))
    content((1.3, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[先代大公（第二代）] \ #text(size: 5.1pt, fill: gray.darken(40%))[遺骨を葬り · 出生記録を保管]]))
    content((7.4, -10.3), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード家・メル家の逆クーデター] \ #text(size: 5.1pt, fill: gray.darken(40%))[鎮圧 → 報復の虐殺 · 一家族ずつ脱出]]))
    content((4.2, -10.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[亡命した二つの家族] \ #text(size: 5.1pt, fill: gray.darken(40%))[こちらで極度の貧困 · 二人を残して餓死 †]]))
    content((1.3, -10.3), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ · メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[亡命後こちらで生まれる · 各家の最後]]))
    content((8.8, -11.9), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[戦犯裁判の証言] \ #text(size: 5.1pt, fill: gray.darken(40%))[二つの虐殺が世界に明らかになる · アリ・ラウラもそのとき初めて知る（次の図）]]))
    line((0.4, -12.95), (1.0, -12.95), stroke: (paint: black, thickness: .7pt))
    content((1.1, -12.95), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -12.95), (3.15, -12.95), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -12.95), (3.15, -12.95), stroke: (paint: white, thickness: .8pt))
    content((3.25, -12.95), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -12.95), (5.299999999999999, -12.95), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -12.95), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -12.95), (7.449999999999999, -12.95), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -12.95), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -12.95), (9.6, -12.95), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -12.95), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -12.95), (11.75, -12.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -12.95), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -12.95), (13.9, -12.95), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -12.95), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -12.95), (16.05, -12.95), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -12.95), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図② 第二次継承戦争（5-6・2-2、設定集専用・ナレーション層）。継承法の空白を埋めた差別が原因であり、側は一家ではなく社会全体に引かれた ―― 絶対的長子相続を支持した進歩的貴族・ジェントリ・ヨーマン・ブルジョワの連合 対 保守的貴族の連合。赤の矢印はそのあとブルーメンタール政権がしたこと（政権直後の虐殺・報復の虐殺）、青は恩人。モード家・メル家とホーエンアスカニアの位置がアリ・ラウラ・フランの出自になる（版2.2）。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    rect((0.2, -14.2), (17.6, -17.3), fill: rgb("#f4f8f5"), stroke: none)
    content((17.450000000000003, -14.28), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[「学校」])
    rect((0.2, -17.7), (17.6, -21.3), fill: rgb("#f3f3f3"), stroke: none)
    content((17.450000000000003, -17.779999999999998), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[終戦の夜とその前後 ―― 機関と名なしの人々])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[第三次継承戦争（禁書戦争）―― その戦争を生きた人々])
    content((2.4, -1.0), name: "thal6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ヴァルター・ハラルト六世] \ #text(size: 5.1pt, fill: gray.darken(40%))[こちらの旧体制の首班]]))
    content((7.0, -1.0), name: "felix", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ロフス・フェリクス] \ #text(size: 5.1pt, fill: gray.darken(40%))[父 † あの夜 · 平土葬]]))
    content((10.6, -1.0), name: "rosa", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ローザ・フリーデリケ] \ #text(size: 5.1pt, fill: gray.darken(40%))[母 † あの夜]]))
    content((15.2, -1.0), name: "sigis", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ヨアヒム・ジギスムント] \ #text(size: 5.1pt, fill: gray.darken(40%))[向こうの旧体制の首班]]))
    content((0.9, -2.6), name: "thal_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[こちらの首班の妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · あの夜を知り止めなかった]]))
    content((4.2, -2.6), name: "halfbro", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[異母兄] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · 父の婚外子]]))
    content((13.1, -2.6), name: "ex_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[向こうの首班の前妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · † 子どもたちの前で]]))
    content((16.7, -2.6), name: "new_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[向こうの首班の後妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし]]))
    content((3.4, -4.4), name: "cous_thal", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[従兄弟たち（こちらの首班の子）] \ #text(size: 5.1pt, fill: gray.darken(40%))[あの夜、両親を告発]]))
    content((3.4, -5.9), name: "cous_half", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[従兄弟たち（異母兄の子）] \ #text(size: 5.1pt, fill: gray.darken(40%))[告発]]))
    content((6.6, -4.4), name: "eiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[エイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[「S」 · 長女 · 禁書とともに消滅 †]]))
    content((8.8, -4.4), name: "reiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[「W」 · 次女 · 向こうへ · 送出]]))
    content((11.0, -4.4), name: "seiran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[リジ・セイラン · 末娘 · こちらの「学校」· 戦死 → 復活]]))
    content((13.6, -4.4), name: "cous_ex", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[従姉妹たち（前妻の子）]]))
    content((16.4, -4.4), name: "cous_new", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[従姉妹たち（後妻の子）]]))
    content((1.8, -8.2), name: "haru_par", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの父 · 母] \ #text(size: 5.1pt, fill: gray.darken(40%))[新宗家当主（譲位）· 原作第8巻]]))
    content((5.2, -8.2), name: "hein_par", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハインリヒの父母] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主夫妻 · ハルの伯父伯母 · 極秘文書を作り封印]]))
    content((0.85, -10.0), name: "haru_sis", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの姉] \ #text(size: 5.1pt, fill: gray.darken(40%))[† シュタウフェンで即死]]))
    content((2.85, -10.0), name: "haru", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハル] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ハルフレズ · 「学校」の学生 → 新宗家当主]]))
    content((5.5, -10.0), name: "hein", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハインリヒ] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ハインリヒ・カール † · 両親を知っていた人 · 両親の墓を作った · 処刑]]))
    content((4.8, -11.8), name: "six", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[弟たち六人] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 扉の前のスクラム · アンハルト家墓地]]))
    content((8.0, -11.8), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン先生] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」の教師 · ハインリヒの幼馴染 · 沈黙]]))
    content((8.0, -13.4), name: "frieda", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[フリーダ] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハインリヒの遺腹の娘 ―― 彼が知り認めた子 · 終戦21日前に生まれる]]))
    content((13.8, -8.2), name: "duke3", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[現大公（第三代）] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク · あの夜の馬車の群れ · 護衛兵力]]))
    content((16.6, -8.2), name: "duke2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[先代大公（第二代）] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 毒殺（家族とともに）]]))
    content((13.8, -10.0), name: "police", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[国際警察] \ #text(size: 5.1pt, fill: gray.darken(40%))[緊急国際逮捕状 · 追撃 · 引き渡し]]))
    content((16.6, -10.0), name: "icc", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[（仮称）国際刑事裁判所] \ #text(size: 5.1pt, fill: gray.darken(40%))[逮捕状を発付]]))
    content((1.3, -15.0), name: "omi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[オミ先生] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」の教師]]))
    content((4.0, -15.0), name: "mimi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ミミ] \ #text(size: 5.1pt, fill: gray.darken(40%))[カガリ・ミミ · 不老不死（母の蘇生）]]))
    content((6.6, -15.0), name: "shina", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[シーナ] \ #text(size: 5.1pt, fill: gray.darken(40%))[トツキ・シーナ · 主人公 · ミミの相方]]))
    content((9.2, -15.0), name: "laura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[シーナの元ルームメイト · 一話前に戦死 → 復活]]))
    content((11.8, -15.0), name: "ari", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランのルームメイト · あの夜馬車に]]))
    content((14.4, -15.0), name: "esta", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタ · ヘザー · リカ] \ #text(size: 5.1pt, fill: gray.darken(40%))[三人 · ヘザーは復活者]]))
    content((16.7, -15.0), name: "senpai", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[男子の先輩] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランが救った]]))
    content((4.0, -16.6), name: "mimi_mom", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[ミミの母] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 命を使い果たして蘇生]]))
    content((9.2, -16.6), name: "clea", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[クレア · ほかの女子生徒 · 二話の子]]))
    content((2.6, -18.6), name: "relay", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[信号を繋いだ人々] \ #text(size: 5.1pt, fill: gray.darken(40%))[向こうの地下ジャーナリスト · 世界のジャーナリスト · 名なし · 何人もが †（3-6）]]))
    content((6.6, -18.6), name: "reporter", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[外信記者] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · 扉の外で見る顔 · 撮って持ち出した]]))
    content((10.2, -18.6), name: "crowd", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[デモ隊] \ #text(size: 5.1pt, fill: gray.darken(40%))[顔なし · 街 · セイランに道を]]))
    content((13.8, -18.6), name: "employees", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト宗家の被雇用者たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[ジギスムントをシュタウフェンで捕らえる]]))
    content((8.4, -20.4), name: "night", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 7.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[終戦の夜 ―― 0年4月7日] \ #text(size: 5.1pt, fill: gray.darken(40%))[暴露放送 · 六人の火刑 · エイランの消滅 · セイランの復活と初めての出会い · 二人の姉妹の十五歳の誕生日]]))
    line((8.8, -1.25), (8.8, -3.3), stroke: (paint: black, thickness: .7pt))
    line((6.6, -3.3), (11.0, -3.3), stroke: (paint: black, thickness: .7pt))
    line((6.6, -3.3), (6.6, -3.95), stroke: (paint: black, thickness: .7pt))
    line((8.8, -3.3), (8.8, -3.95), stroke: (paint: black, thickness: .7pt))
    line((11.0, -3.3), (11.0, -3.95), stroke: (paint: black, thickness: .7pt))
    lbl((8.8, -2.85), [一卵性の三つ子 · −15年 4/7 · ブルーメンタールベルク])
    line("thal6", "felix", stroke: (paint: black, thickness: .7pt))
    lbl((4.70, -1.00), [実の兄弟])
    line("rosa", "sigis", stroke: (paint: black, thickness: .7pt))
    lbl((12.90, -1.00), [実の兄妹])
    line("felix", "rosa", stroke: (paint: black, thickness: 1.7pt))
    line("felix", "rosa", stroke: (paint: white, thickness: .8pt))
    line((2.4, -1.55), (2.4, -1.9), (6.4, -1.9), (6.4, -1.5), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((4.40, -1.90), [暗殺の命令])
    line((15.2, -1.55), (15.2, -1.9), (11.2, -1.9), (11.2, -1.5), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((13.20, -1.90), [暗殺の命令])
    line("thal_wife", "thal6", stroke: (paint: black, thickness: 1.7pt))
    line("thal_wife", "thal6", stroke: (paint: white, thickness: .8pt))
    line("halfbro", "thal6", stroke: (paint: black, thickness: .7pt))
    lbl((3.30, -1.80), [異母兄])
    line("ex_wife", "sigis", stroke: (paint: black, thickness: 1.7pt))
    line("ex_wife", "sigis", stroke: (paint: white, thickness: .8pt))
    lbl((14.15, -1.80), [前妻])
    line("new_wife", "sigis", stroke: (paint: black, thickness: 1.7pt))
    line("new_wife", "sigis", stroke: (paint: white, thickness: .8pt))
    lbl((15.95, -1.80), [後妻])
    line((13.1, -2.2), (12.0, -1.3), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((12.55, -1.75), [道を開く])
    line("thal6", "cous_thal", stroke: (paint: black, thickness: .7pt))
    line("halfbro", "cous_half", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cous_ex", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cous_new", stroke: (paint: black, thickness: .7pt))
    line((6.6, -4.85), (6.6, -5.45), (8.8, -5.45), (8.8, -4.9), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((7.70, -5.45), [解除法を与えた（2-6）])
    line("haru_par", "hein_par", stroke: (paint: black, thickness: .7pt))
    lbl((3.50, -8.20), [兄弟])
    line("haru_par", "haru", stroke: (paint: black, thickness: .7pt))
    line("haru_par", "haru_sis", stroke: (paint: black, thickness: .7pt))
    line("hein_par", "hein", stroke: (paint: black, thickness: .7pt))
    lbl((5.35, -9.10), [長男])
    line((5.9, -8.65), (5.9, -11.35), stroke: (paint: black, thickness: .7pt))
    line((6.8, -10.2), (7.7, -11.3), stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((7.25, -10.75), [幼馴染 · 子を知り認めた（婚姻はなし）])
    line((6.5, -10.55), (7.0, -13.4), stroke: (paint: black, thickness: .7pt))
    lbl((6.75, -11.98), [父])
    line("fran", "frieda", stroke: (paint: black, thickness: .7pt))
    line((4.6, -9.45), (4.6, -7.2), (6.0, -5.3), (6.4, -4.9), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((5.30, -6.25), [あの夜抱いて走った])
    line((6.8, -9.75), (8.2, -9.6), (10.6, -5.3), (10.8, -4.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((9.40, -7.45), [二年かけて探し出した])
    line((14.6, -1.55), (14.6, -2.0), (12.4, -2.0), (12.4, -12.55), (5.6, -12.55), (5.4, -12.3), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((12.40, -7.28), [火刑の命令])
    line((14.3, -1.55), (14.3, -2.15), (12.2, -2.15), (12.2, -7.5), (0.35, -7.5), (0.35, -9.6), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((12.20, -4.83), [射殺])
    line((16.2, -1.55), (17.75, -2.4), (17.75, -7.0), (16.9, -7.75), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((17.75, -4.70), [毒殺])
    line((14.9, -1.55), (14.9, -2.3), (12.3, -2.3), (12.3, -11.0), (6.9, -11.0), (6.5, -10.55), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((12.30, -6.65), [処刑（フェルデンブルク）])
    line("duke3", "police", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("icc", "police", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    lbl((15.20, -10.00), [逮捕状])
    line("mimi_mom", "mimi", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((4.00, -15.80), [蘇生])
    line("mimi", "shina", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((5.30, -15.00), [相方])
    line("shina", "laura", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((7.90, -15.00), [元ルームメイト])
    line((11.0, -4.85), (11.8, -14.5), stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((11.40, -9.68), [ルームメイト])
    line((12.0, -4.6), (16.7, -14.5), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((14.35, -9.55), [救った])
    line((7.6, -12.3), (1.3, -14.4), stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((4.45, -13.35), [同僚の教師])
    line("relay", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("reporter", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("crowd", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("employees", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((2.4, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ヴァルター・ハラルト六世] \ #text(size: 5.1pt, fill: gray.darken(40%))[こちらの旧体制の首班]]))
    content((7.0, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ロフス・フェリクス] \ #text(size: 5.1pt, fill: gray.darken(40%))[父 † あの夜 · 平土葬]]))
    content((10.6, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ローザ・フリーデリケ] \ #text(size: 5.1pt, fill: gray.darken(40%))[母 † あの夜]]))
    content((15.2, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ヨアヒム・ジギスムント] \ #text(size: 5.1pt, fill: gray.darken(40%))[向こうの旧体制の首班]]))
    content((0.9, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[こちらの首班の妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · あの夜を知り止めなかった]]))
    content((4.2, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[異母兄] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · 父の婚外子]]))
    content((13.1, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[向こうの首班の前妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · † 子どもたちの前で]]))
    content((16.7, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[向こうの首班の後妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし]]))
    content((3.4, -4.4), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[従兄弟たち（こちらの首班の子）] \ #text(size: 5.1pt, fill: gray.darken(40%))[あの夜、両親を告発]]))
    content((3.4, -5.9), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[従兄弟たち（異母兄の子）] \ #text(size: 5.1pt, fill: gray.darken(40%))[告発]]))
    content((6.6, -4.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[エイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[「S」 · 長女 · 禁書とともに消滅 †]]))
    content((8.8, -4.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[「W」 · 次女 · 向こうへ · 送出]]))
    content((11.0, -4.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[リジ・セイラン · 末娘 · こちらの「学校」· 戦死 → 復活]]))
    content((13.6, -4.4), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[従姉妹たち（前妻の子）]]))
    content((16.4, -4.4), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[従姉妹たち（後妻の子）]]))
    content((1.8, -8.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの父 · 母] \ #text(size: 5.1pt, fill: gray.darken(40%))[新宗家当主（譲位）· 原作第8巻]]))
    content((5.2, -8.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハインリヒの父母] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主夫妻 · ハルの伯父伯母 · 極秘文書を作り封印]]))
    content((0.85, -10.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの姉] \ #text(size: 5.1pt, fill: gray.darken(40%))[† シュタウフェンで即死]]))
    content((2.85, -10.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハル] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ハルフレズ · 「学校」の学生 → 新宗家当主]]))
    content((5.5, -10.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハインリヒ] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ハインリヒ・カール † · 両親を知っていた人 · 両親の墓を作った · 処刑]]))
    content((4.8, -11.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[弟たち六人] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 扉の前のスクラム · アンハルト家墓地]]))
    content((8.0, -11.8), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン先生] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」の教師 · ハインリヒの幼馴染 · 沈黙]]))
    content((8.0, -13.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[フリーダ] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハインリヒの遺腹の娘 ―― 彼が知り認めた子 · 終戦21日前に生まれる]]))
    content((13.8, -8.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[現大公（第三代）] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク · あの夜の馬車の群れ · 護衛兵力]]))
    content((16.6, -8.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[先代大公（第二代）] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 毒殺（家族とともに）]]))
    content((13.8, -10.0), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[国際警察] \ #text(size: 5.1pt, fill: gray.darken(40%))[緊急国際逮捕状 · 追撃 · 引き渡し]]))
    content((16.6, -10.0), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[（仮称）国際刑事裁判所] \ #text(size: 5.1pt, fill: gray.darken(40%))[逮捕状を発付]]))
    content((1.3, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[オミ先生] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」の教師]]))
    content((4.0, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ミミ] \ #text(size: 5.1pt, fill: gray.darken(40%))[カガリ・ミミ · 不老不死（母の蘇生）]]))
    content((6.6, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[シーナ] \ #text(size: 5.1pt, fill: gray.darken(40%))[トツキ・シーナ · 主人公 · ミミの相方]]))
    content((9.2, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[シーナの元ルームメイト · 一話前に戦死 → 復活]]))
    content((11.8, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランのルームメイト · あの夜馬車に]]))
    content((14.4, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタ · ヘザー · リカ] \ #text(size: 5.1pt, fill: gray.darken(40%))[三人 · ヘザーは復活者]]))
    content((16.7, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[男子の先輩] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランが救った]]))
    content((4.0, -16.6), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[ミミの母] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 命を使い果たして蘇生]]))
    content((9.2, -16.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[クレア · ほかの女子生徒 · 二話の子]]))
    content((2.6, -18.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[信号を繋いだ人々] \ #text(size: 5.1pt, fill: gray.darken(40%))[向こうの地下ジャーナリスト · 世界のジャーナリスト · 名なし · 何人もが †（3-6）]]))
    content((6.6, -18.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[外信記者] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · 扉の外で見る顔 · 撮って持ち出した]]))
    content((10.2, -18.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[デモ隊] \ #text(size: 5.1pt, fill: gray.darken(40%))[顔なし · 街 · セイランに道を]]))
    content((13.8, -18.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト宗家の被雇用者たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[ジギスムントをシュタウフェンで捕らえる]]))
    content((8.4, -20.4), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 7.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[終戦の夜 ―― 0年4月7日] \ #text(size: 5.1pt, fill: gray.darken(40%))[暴露放送 · 六人の火刑 · エイランの消滅 · セイランの復活と初めての出会い · 二人の姉妹の十五歳の誕生日]]))
    line((0.4, -21.950000000000003), (1.0, -21.950000000000003), stroke: (paint: black, thickness: .7pt))
    content((1.1, -21.950000000000003), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -21.950000000000003), (3.15, -21.950000000000003), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -21.950000000000003), (3.15, -21.950000000000003), stroke: (paint: white, thickness: .8pt))
    content((3.25, -21.950000000000003), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -21.950000000000003), (5.299999999999999, -21.950000000000003), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -21.950000000000003), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -21.950000000000003), (7.449999999999999, -21.950000000000003), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -21.950000000000003), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -21.950000000000003), (9.6, -21.950000000000003), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -21.950000000000003), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -21.950000000000003), (11.75, -21.950000000000003), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -21.950000000000003), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -21.950000000000003), (13.9, -21.950000000000003), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -21.950000000000003), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -21.950000000000003), (16.05, -21.950000000000003), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -21.950000000000003), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図③ 第三次継承戦争＝禁書戦争 ―― その戦争を生きた人々（2-2・2-5・3-6・5-6・24節）。上：二つの家と三姉妹・従兄弟たち。中：アンハルト宗家・ハインリヒ七兄弟・フラン・フリーダ。下：「学校」と、終戦の夜にいた人々・機関。婚姻・後孫・裁判は次の図。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    rect((0.2, -0.4), (17.6, -4.4), fill: rgb("#f7f7f7"), stroke: none)
    content((17.450000000000003, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[戦犯裁判（+1〜+3年）とそのあと ―― 姓の行方])
    rect((0.2, -14.0), (17.6, -16.8), fill: rgb("#f3f3f3"), stroke: none)
    content((17.450000000000003, -14.08), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[百年後（+99年）])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[禁書戦争のあと ―― 裁判・婚姻・後孫・百年後])
    content((1.6, -1.3), name: "judge", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[裁判長] \ #text(size: 5.1pt, fill: gray.darken(40%))[軍のない中立国の首長 · 大公国の出]]))
    content((5.0, -1.3), name: "thal6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ヴァルター・ハラルト六世] \ #text(size: 5.1pt, fill: gray.darken(40%))[終身刑 · 画面にはナレーションの呼名一度だけ]]))
    content((8.6, -1.3), name: "sigis", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ヨアヒム・ジギスムント] \ #text(size: 5.1pt, fill: gray.darken(40%))[終身刑 · 面会室のガラスの向こう · 「どうか、長生きしてください」]]))
    content((12.2, -1.3), name: "spouses", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[二人の首班の配偶者たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[裁判（別の刑）· 異母兄は絞首刑 †]]))
    content((15.6, -1.3), name: "witness", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[証言台の顔] \ #text(size: 5.1pt, fill: gray.darken(40%))[従兄弟たちの証言 · 大公家の人々とフランの証言（二つの虐殺）· あの日呼び出された人]]))
    content((3.2, -3.2), name: "cousT", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[父方の従兄弟たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[姓を捨てる → 大公国が与えた姓]]))
    content((7.0, -3.2), name: "cousB", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[母方の従姉妹たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[ブルーメンタールベルクを受ける · 五親等の甥姪（弁護士、第19.7話）]]))
    content((11.0, -3.2), name: "acting", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[大統領権限代行] \ #text(size: 5.1pt, fill: gray.darken(40%))[国葬を質素に · 記録館を任期制に]]))
    content((14.6, -3.2), name: "pres", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[男子の先輩 → 大統領] \ #text(size: 5.1pt, fill: gray.darken(40%))[人権弁護士 → 議員 → 大統領 · 第20話 †]]))
    content((4.4, -6.0), name: "reiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[初代記録館長 · 生涯]]))
    content((7.0, -6.0), name: "laura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[日記の保管者 · 大統領秘書室長]]))
    content((10.4, -6.0), name: "seiran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[光学の修士 · 写真家]]))
    content((13.0, -6.0), name: "ari", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ] \ #text(size: 5.1pt, fill: gray.darken(40%))[陪審拒否 · 遺骸処理に志願]]))
    content((5.7, -7.9), name: "d_reiran", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイランの娘二人 · ラウラの娘二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[ラウラ・ミラン · アマリア・カラン / アントニア二世 · ソフィア二世]]))
    content((10.4, -7.9), name: "d_seiran", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイランの娘三人 · アリの娘二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[ルディ・スズラン · フリーダ・フェリシア・ジュラン · ハルフリート・マルガレーテ・ケイラン / レティシア三世 · プレシス二世]]))
    content((14.2, -7.9), name: "adela", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[アデラ・アリ・アイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランの末娘]]))
    content((1.5, -8.6), name: "haru", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハル] \ #text(size: 5.1pt, fill: gray.darken(40%))[新宗家当主 → 譲位]]))
    content((1.5, -6.0), name: "haru_par", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの父 · 母] \ #text(size: 5.1pt, fill: gray.darken(40%))[兄夫婦の墓を開けDNAで確認]]))
    content((14.2, -10.2), name: "ferd", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト・フェルディナント] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハルの養子 · 当主 · 第二代記録館長（初の任期制）]]))
    content((14.2, -12.2), name: "seven", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[フェルディナントの七人の娘] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ブルーメンタールベルク]]))
    content((4.6, -10.4), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[第19.5話の告白 · 新宗家が家族として認める]]))
    content((8.0, -10.4), name: "frieda", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[フリーダ] \ #text(size: 5.1pt, fill: gray.darken(40%))[極秘文書でアンハルト＝ヘヒンゲン姓 · アンハルト＝ホーエンアスカニア＝ヘヒンゲン＝フェルデンブルク]]))
    content((8.0, -12.4), name: "esta", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタ] \ #text(size: 5.1pt, fill: gray.darken(40%))[出産直後 †（+20年）]]))
    content((4.6, -12.4), name: "heather", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ヘザー · リカ] \ #text(size: 5.1pt, fill: gray.darken(40%))[五人を育てる · フェルディナントも守った子]]))
    content((11.2, -12.4), name: "quint", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタの五つ子] \ #text(size: 5.1pt, fill: gray.darken(40%))[第21話の老人五人]]))
    content((1.5, -12.4), name: "funeral", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[五重の国葬（+78年）] \ #text(size: 5.1pt, fill: gray.darken(40%))[大統領 · セイラン · レイラン · ラウラ · アリ]]))
    content((1.8, -15.2), name: "pres100", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[大統領（百年後）] \ #text(size: 5.1pt, fill: gray.darken(40%))[女性 · 未来編後編]]))
    content((5.2, -15.2), name: "ferd2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[第二代記録館長フェルディナント] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハインリヒの遺骨を掘り鑑定する]]))
    content((9.0, -15.2), name: "desc", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイランの女系の後孫] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」上級生 · mtDNA · 名なし]]))
    content((12.4, -15.2), name: "males", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[純粋な男系の二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[大公国の人 · Y染色体]]))
    content((15.6, -15.2), name: "envoy", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[使節団 · ヘリの撮影記者] \ #text(size: 5.1pt, fill: gray.darken(40%))[後編 · 前編の最後のコマ]]))
    line("judge", "thal6", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("judge", "sigis", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("thal6", "cousT", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cousB", stroke: (paint: black, thickness: .7pt))
    line("acting", "pres", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    lbl((12.80, -3.20), [死後の代行])
    line("reiran", "laura", stroke: (paint: black, thickness: 1.7pt))
    line("reiran", "laura", stroke: (paint: white, thickness: .8pt))
    line("seiran", "ari", stroke: (paint: black, thickness: 1.7pt))
    line("seiran", "ari", stroke: (paint: white, thickness: .8pt))
    line("laura", "d_reiran", stroke: (paint: black, thickness: .7pt))
    line("ari", "d_seiran", stroke: (paint: black, thickness: .7pt))
    line((11.4, -6.2), (14.2, -7.45), stroke: (paint: black, thickness: .7pt))
    lbl((12.80, -6.83), [末娘])
    line("adela", "ferd", stroke: (paint: black, thickness: 1.7pt))
    line("adela", "ferd", stroke: (paint: white, thickness: .8pt))
    line("ferd", "seven", stroke: (paint: black, thickness: .7pt))
    line("haru_par", "haru", stroke: (paint: black, thickness: .7pt))
    lbl((1.50, -7.30), [譲位])
    line((1.5, -9.15), (1.5, -9.55), (12.5, -9.55), (13.0, -10.0), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    lbl((7.00, -9.55), [養子 · 譲位])
    line((5.2, -12.85), (5.2, -13.35), (16.5, -13.35), (16.5, -10.55), (15.75, -10.3), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    lbl((10.85, -13.35), [守った子])
    line((4.4, -6.55), (3.3, -7.1), (3.3, -9.05), (12.7, -9.05), (13.6, -9.7), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    lbl((3.30, -8.07), [初代 → 第二代記録館長])
    line((2.4, -6.55), (3.4, -9.9), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((2.90, -8.22), [家族として認める])
    line("fran", "frieda", stroke: (paint: black, thickness: .7pt))
    line("esta", "quint", stroke: (paint: black, thickness: .7pt))
    line((5.9, -12.55), (9.9, -12.55), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    lbl((7.90, -12.55), [育てる])
    line((14.2, -10.75), (16.9, -11.6), (16.9, -13.6), (6.7, -13.6), (5.2, -14.75), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("desc", "ferd2", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((7.10, -15.20), [鑑定に系統を提供])
    line((11.2, -15.2), (10.4, -15.9), (6.7, -15.9), (6.3, -15.6), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((1.6, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[裁判長] \ #text(size: 5.1pt, fill: gray.darken(40%))[軍のない中立国の首長 · 大公国の出]]))
    content((5.0, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ヴァルター・ハラルト六世] \ #text(size: 5.1pt, fill: gray.darken(40%))[終身刑 · 画面にはナレーションの呼名一度だけ]]))
    content((8.6, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ヨアヒム・ジギスムント] \ #text(size: 5.1pt, fill: gray.darken(40%))[終身刑 · 面会室のガラスの向こう · 「どうか、長生きしてください」]]))
    content((12.2, -1.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[二人の首班の配偶者たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[裁判（別の刑）· 異母兄は絞首刑 †]]))
    content((15.6, -1.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[証言台の顔] \ #text(size: 5.1pt, fill: gray.darken(40%))[従兄弟たちの証言 · 大公家の人々とフランの証言（二つの虐殺）· あの日呼び出された人]]))
    content((3.2, -3.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[父方の従兄弟たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[姓を捨てる → 大公国が与えた姓]]))
    content((7.0, -3.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[母方の従姉妹たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[ブルーメンタールベルクを受ける · 五親等の甥姪（弁護士、第19.7話）]]))
    content((11.0, -3.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[大統領権限代行] \ #text(size: 5.1pt, fill: gray.darken(40%))[国葬を質素に · 記録館を任期制に]]))
    content((14.6, -3.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[男子の先輩 → 大統領] \ #text(size: 5.1pt, fill: gray.darken(40%))[人権弁護士 → 議員 → 大統領 · 第20話 †]]))
    content((4.4, -6.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[初代記録館長 · 生涯]]))
    content((7.0, -6.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[日記の保管者 · 大統領秘書室長]]))
    content((10.4, -6.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[光学の修士 · 写真家]]))
    content((13.0, -6.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ] \ #text(size: 5.1pt, fill: gray.darken(40%))[陪審拒否 · 遺骸処理に志願]]))
    content((5.7, -7.9), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイランの娘二人 · ラウラの娘二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[ラウラ・ミラン · アマリア・カラン / アントニア二世 · ソフィア二世]]))
    content((10.4, -7.9), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイランの娘三人 · アリの娘二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[ルディ・スズラン · フリーダ・フェリシア・ジュラン · ハルフリート・マルガレーテ・ケイラン / レティシア三世 · プレシス二世]]))
    content((14.2, -7.9), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[アデラ・アリ・アイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランの末娘]]))
    content((1.5, -8.6), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハル] \ #text(size: 5.1pt, fill: gray.darken(40%))[新宗家当主 → 譲位]]))
    content((1.5, -6.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの父 · 母] \ #text(size: 5.1pt, fill: gray.darken(40%))[兄夫婦の墓を開けDNAで確認]]))
    content((14.2, -10.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト・フェルディナント] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハルの養子 · 当主 · 第二代記録館長（初の任期制）]]))
    content((14.2, -12.2), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[フェルディナントの七人の娘] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ブルーメンタールベルク]]))
    content((4.6, -10.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[第19.5話の告白 · 新宗家が家族として認める]]))
    content((8.0, -10.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[フリーダ] \ #text(size: 5.1pt, fill: gray.darken(40%))[極秘文書でアンハルト＝ヘヒンゲン姓 · アンハルト＝ホーエンアスカニア＝ヘヒンゲン＝フェルデンブルク]]))
    content((8.0, -12.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタ] \ #text(size: 5.1pt, fill: gray.darken(40%))[出産直後 †（+20年）]]))
    content((4.6, -12.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ヘザー · リカ] \ #text(size: 5.1pt, fill: gray.darken(40%))[五人を育てる · フェルディナントも守った子]]))
    content((11.2, -12.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタの五つ子] \ #text(size: 5.1pt, fill: gray.darken(40%))[第21話の老人五人]]))
    content((1.5, -12.4), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[五重の国葬（+78年）] \ #text(size: 5.1pt, fill: gray.darken(40%))[大統領 · セイラン · レイラン · ラウラ · アリ]]))
    content((1.8, -15.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[大統領（百年後）] \ #text(size: 5.1pt, fill: gray.darken(40%))[女性 · 未来編後編]]))
    content((5.2, -15.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[第二代記録館長フェルディナント] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハインリヒの遺骨を掘り鑑定する]]))
    content((9.0, -15.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイランの女系の後孫] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」上級生 · mtDNA · 名なし]]))
    content((12.4, -15.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[純粋な男系の二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[大公国の人 · Y染色体]]))
    content((15.6, -15.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[使節団 · ヘリの撮影記者] \ #text(size: 5.1pt, fill: gray.darken(40%))[後編 · 前編の最後のコマ]]))
    line((0.4, -17.35), (1.0, -17.35), stroke: (paint: black, thickness: .7pt))
    content((1.1, -17.35), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -17.35), (3.15, -17.35), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -17.35), (3.15, -17.35), stroke: (paint: white, thickness: .8pt))
    content((3.25, -17.35), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -17.35), (5.299999999999999, -17.35), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -17.35), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -17.35), (7.449999999999999, -17.35), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -17.35), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -17.35), (9.6, -17.35), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -17.35), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -17.35), (11.75, -17.35), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -17.35), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -17.35), (13.9, -17.35), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -17.35), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -17.35), (16.05, -17.35), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -17.35), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図④ 禁書戦争のあと（2-2・5-2・2-12・第19.5話・終章・百年後の未来編）。上：裁判と姓の行方。中：二組の夫婦と娘たち（破線＝設定集専用）、フェルディナントと七人の娘、フラン・フリーダに来たもの。下：五重の国葬、百年後。二重線＝婚姻、一点鎖線＝養子・育てた人、点線＝職務。],
  supplement: none,
  numbering: none,
)
