// 인물관계도 v2.7.4 — 생성물. tools/relations_diagram_gen.py 가 만든다(KO/JA 록스텝). 손으로 고치지 않는다.
// 일곱 장 — ① 1차 계승전쟁 ② 2차 ③ 금서전쟁: 권력의 집과 세 자매 ④ 곁에 있던 사람들
// ⑤ 「학교」와 그날 ⑥ 전쟁의 뒤: 재판과 성의 향방 ⑦ 관계와 아이들, 그리고 먼 뒤(유향 하이퍼엣지).
#import "@preview/cetz:0.4.2": canvas, draw

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[제1차 계승전쟁 — 안할트가의 갈래])
    content((8.8, -0.8), name: "root", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[공통시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트·호헨아스카니아의 공통 시조]]))
    content((5.4, -2.3), name: "anh0", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 중시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[공통시조의 외아들]]))
    content((12.4, -2.3), name: "asc0", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 중시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[공통시조의 막내딸 · 이 대부터 지명상속제]]))
    content((5.4, -3.8), name: "g3", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 3대 가주] \ #text(size: 5.1pt, fill: gray.darken(40%))[아들 열아홉]]))
    content((12.4, -3.8), name: "asc", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 가문] \ #text(size: 5.1pt, fill: gray.darken(40%))[→ 2차 때 구종가측(다음 장)]]))
    content((1.7, -5.5), name: "f1", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[장남 ~ 5남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁 · 단절 †]]))
    content((4.2, -5.5), name: "f2", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[6남 ~ 12남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁 · 단절 †]]))
    content((6.9, -5.5), name: "f3", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[13 · 14 · 19남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁의 한 편]]))
    content((9.6, -5.5), name: "f4", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[15남 ~ 18남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁의 한 편]]))
    content((3.0, -7.4), name: "main", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 구종가 · 신종가] \ #text(size: 5.1pt, fill: gray.darken(40%))[13남 계보 · 하인리히의 집(구종가) → 하루의 집(신종가)]]))
    content((7.0, -7.4), name: "meissen", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센] \ #text(size: 5.1pt, fill: gray.darken(40%))[14남 계보 · 가주 직계 등 나머지는 2차 때 단절 †]]))
    content((10.4, -7.4), name: "witt", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-비텐베르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[19남 계보 · 뒷날 대공가]]))
    content((13.0, -7.4), name: "f17", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[17남 계보 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[소송에서 파산 · 이름을 받지 못한 쪽 · 수장(여성·전과자) — 종전을 방해]]))
    content((16.15, -7.4), name: "unk", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[몇 남에서 왔는지 정하지 않는 집들] \ #text(size: 5.1pt, fill: gray.darken(40%))[호헨슈타우펜 종가 · 헤힝겐 분가 · 안토노프·안토노바 분가 등]]))
    content((5.6, -9.0), name: "thal", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센-탈베르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[초대 가주의 4남 → 뒷날 탈베르크 가문 · 친가 사촌들(→안할트-니더비텐베르크)의 기원]]))
    content((8.8, -9.0), name: "blum", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센-블루멘탈] \ #text(size: 5.1pt, fill: gray.darken(40%))[5남 → 뒷날 블루멘탈 가문 · 세 자매·외가 사촌들(→블루멘탈베르크)의 기원]]))
    content((1.4, -9.0), name: "arvid", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨아르비드부르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 당주의 이복남동생 → 2차의 반대편]]))
    line("root", "anh0", stroke: (paint: black, thickness: .7pt))
    lbl((7.10, -1.55), [외아들])
    line("root", "asc0", stroke: (paint: black, thickness: .7pt))
    lbl((10.60, -1.55), [막내딸])
    line("anh0", "g3", stroke: (paint: black, thickness: .7pt))
    line("asc0", "asc", stroke: (paint: black, thickness: .7pt))
    line("g3", "f1", stroke: (paint: black, thickness: .7pt))
    line("g3", "f2", stroke: (paint: black, thickness: .7pt))
    line("g3", "f3", stroke: (paint: black, thickness: .7pt))
    line("g3", "f4", stroke: (paint: black, thickness: .7pt))
    line("f3", "main", stroke: (paint: black, thickness: .7pt))
    lbl((4.95, -6.45), [13남])
    line("f3", "meissen", stroke: (paint: black, thickness: .7pt))
    lbl((6.95, -6.45), [14남])
    line("f3", "witt", stroke: (paint: black, thickness: .7pt))
    lbl((8.65, -6.45), [19남])
    line("f4", "f17", stroke: (paint: black, thickness: .7pt))
    lbl((11.30, -6.45), [17남])
    line("meissen", "thal", stroke: (paint: black, thickness: .7pt))
    lbl((6.30, -8.20), [4남])
    line("meissen", "blum", stroke: (paint: black, thickness: .7pt))
    lbl((7.90, -8.20), [5남])
    line("main", "arvid", stroke: (paint: black, thickness: .7pt))
    lbl((2.20, -8.20), [이복남동생])
    content((8.8, -0.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[공통시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트·호헨아스카니아의 공통 시조]]))
    content((5.4, -2.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 중시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[공통시조의 외아들]]))
    content((12.4, -2.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 중시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[공통시조의 막내딸 · 이 대부터 지명상속제]]))
    content((5.4, -3.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 3대 가주] \ #text(size: 5.1pt, fill: gray.darken(40%))[아들 열아홉]]))
    content((12.4, -3.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 가문] \ #text(size: 5.1pt, fill: gray.darken(40%))[→ 2차 때 구종가측(다음 장)]]))
    content((1.7, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[장남 ~ 5남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁 · 단절 †]]))
    content((4.2, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[6남 ~ 12남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁 · 단절 †]]))
    content((6.9, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[13 · 14 · 19남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁의 한 편]]))
    content((9.6, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[15남 ~ 18남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁의 한 편]]))
    content((3.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 구종가 · 신종가] \ #text(size: 5.1pt, fill: gray.darken(40%))[13남 계보 · 하인리히의 집(구종가) → 하루의 집(신종가)]]))
    content((7.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센] \ #text(size: 5.1pt, fill: gray.darken(40%))[14남 계보 · 가주 직계 등 나머지는 2차 때 단절 †]]))
    content((10.4, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-비텐베르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[19남 계보 · 뒷날 대공가]]))
    content((13.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[17남 계보 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[소송에서 파산 · 이름을 받지 못한 쪽 · 수장(여성·전과자) — 종전을 방해]]))
    content((16.15, -7.4), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[몇 남에서 왔는지 정하지 않는 집들] \ #text(size: 5.1pt, fill: gray.darken(40%))[호헨슈타우펜 종가 · 헤힝겐 분가 · 안토노프·안토노바 분가 등]]))
    content((5.6, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센-탈베르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[초대 가주의 4남 → 뒷날 탈베르크 가문 · 친가 사촌들(→안할트-니더비텐베르크)의 기원]]))
    content((8.8, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센-블루멘탈] \ #text(size: 5.1pt, fill: gray.darken(40%))[5남 → 뒷날 블루멘탈 가문 · 세 자매·외가 사촌들(→블루멘탈베르크)의 기원]]))
    content((1.4, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨아르비드부르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 당주의 이복남동생 → 2차의 반대편]]))
    line((0.4, -9.95), (1.0, -9.95), stroke: (paint: black, thickness: .7pt))
    content((1.1, -9.95), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -9.95), (3.15, -9.95), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -9.95), (3.15, -9.95), stroke: (paint: white, thickness: .8pt))
    content((3.25, -9.95), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -9.95), (5.299999999999999, -9.95), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -9.95), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -9.95), (7.449999999999999, -9.95), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -9.95), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -9.95), (9.6, -9.95), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -9.95), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -9.95), (11.75, -9.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -9.95), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -9.95), (13.9, -9.95), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -9.95), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -9.95), (16.05, -9.95), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -9.95), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ① 제1차 계승전쟁 — 안할트가의 갈래(2-2·3-6, 설정집 전용). 3대 가주의 아들 열아홉이 네 편으로 싸웠고, 장남~12남 계보는 단절되었다. 남은 갈래가 뒷날의 두 통치 가문(14남 안할트-호헨마이센 계보)·대공가(19남)·구종가와 신종가(13남)가 된다. 몇 남에서 왔는지 정하지 않은 귀족 집들은 오른쪽에 따로(모드가·멜가는 귀족이 아닌 젠트리 집안 — ②장 참조).],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    rect((0.2, -0.4), (8.6, -6.2), fill: rgb("#f4f8f5"), stroke: none)
    content((8.45, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[구종가측 — 진보 귀족·젠트리·요먼·부르주아 연합 (승전)])
    rect((9.0, -0.4), (17.6, -6.2), fill: rgb("#fdf2f0"), stroke: none)
    content((17.450000000000003, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[반대편 — 보수적 귀족의 연합])
    rect((0.2, -7.6), (17.6, -12.4), fill: rgb("#f7f7f7"), stroke: none)
    content((17.450000000000003, -7.68), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[그 뒤에 온 것])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[제2차 계승전쟁 — 두 편, 그리고 그 뒤에 온 것])
    content((3.3, -1.5), name: "issue", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[구종가 당주의 첫째 자녀] \ #text(size: 5.1pt, fill: gray.darken(40%))[승계법의 빈칸 · 그 빈칸을 채운 차별이 전쟁의 원인 · 뒷날 가주가 되어 천수를 누렸고 자녀가 없다]]))
    content((1.6, -3.0), name: "lord", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 구종가 당주] \ #text(size: 5.1pt, fill: gray.darken(40%))[하루의 친증조할아버지]]))
    content((1.6, -4.7), name: "gf", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 친할아버지] \ #text(size: 5.1pt, fill: gray.darken(40%))[첫째 자녀의 막내동생 · 다음 가주]]))
    content((4.3, -3.0), name: "gd1", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[초대 여대공 나타샤 1세] \ #text(size: 5.1pt, fill: gray.darken(40%))[1등공신 → 대공위 · 초대 국서 올렉사 1세(어부 출신, 부인 성씨 하사)]]))
    content((7.2, -3.0), name: "asc", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 가문] \ #text(size: 5.1pt, fill: gray.darken(40%))[가문 전체 참전 · 블루멘탈 분가를 멸망 직전까지]]))
    content((4.3, -4.7), name: "maudmel", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드가 · 멜가 (젠트리)] \ #text(size: 5.1pt, fill: gray.darken(40%))[귀족과 혈연·혼맥 없음 · 승전 측이면서 전쟁 중 궤멸에 준하는 타격]]))
    content((7.2, -4.7), name: "anton", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜-안토노프·안토노바] \ #text(size: 5.1pt, fill: gray.darken(40%))[생존]]))
    content((11.6, -1.3), name: "arvid", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아르비드부르크 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 당주의 이복남동생을 따름 · 금서를 「엮음」 · 남녀노소 전멸 †]]))
    content((11.6, -3.0), name: "stauf", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜 종가] \ #text(size: 5.1pt, fill: gray.darken(40%))[전멸 †]]))
    content((15.0, -3.0), name: "hech", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜-헤힝겐 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[세력이 줄었으나 생존]]))
    content((11.6, -4.7), name: "thal", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[막판에 탈주해 성을 갈다]]))
    content((15.0, -4.7), name: "blum", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[막판에 탈주해 성을 갈다]]))
    content((8.8, -6.9), name: "law", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[절대적 맏이상속제] \ #text(size: 5.1pt, fill: gray.darken(40%))[성별 불문 · 「고르지 못하게 하려고」 · 직후 제정]]))
    content((11.6, -8.5), name: "regT", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 정권(이쪽 구체제)] \ #text(size: 5.1pt, fill: gray.darken(40%))[뒷날 쿠데타로 집권 · 뒷날의 수반 탈베르크 발터 하랄트 6세]]))
    content((15.4, -8.5), name: "regB", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 정권(저쪽 구체제)] \ #text(size: 5.1pt, fill: gray.darken(40%))[쿠데타로 집권 · 수반 블루멘탈 요아힘 지기스문트 — 학살을 명령]]))
    content((13.5, -10.3), name: "book", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[금서 도난] \ #text(size: 5.1pt, fill: gray.darken(40%))[두 집 중 한쪽 — 정하지 않는다 → 3차의 도화선]]))
    content((7.4, -8.5), name: "massA", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 학살] \ #text(size: 5.1pt, fill: gray.darken(40%))[집권 직후의 앙갚음 · 가문 전체 †]]))
    content((4.2, -8.5), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란] \ #text(size: 5.1pt, fill: gray.darken(40%))[유일 생존자 · 모친 에밀리아 · 마사코가 도주 도움 · 대공국 거쳐 이쪽으로]]))
    content((1.3, -8.5), name: "duke2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[선대 대공(2대) 올렉사 2세] \ #text(size: 5.1pt, fill: gray.darken(40%))[유골 안장 · 출생 기록 보관]]))
    content((7.4, -10.3), name: "coup", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드가 · 멜가의 역쿠데타] \ #text(size: 5.1pt, fill: gray.darken(40%))[진압 → 보복학살 · 한 가정씩 탈출]]))
    content((4.2, -10.3), name: "exile", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[망명한 두 가정] \ #text(size: 5.1pt, fill: gray.darken(40%))[이쪽에서 극심한 빈곤 · 둘만 남기고 아사 †]]))
    content((1.3, -10.3), name: "ariLaura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리 · 멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[젠트리 두 집의 마지막 · 아리·라우라 외에는 귀족과 혈연·혼맥 전무]]))
    content((8.8, -11.9), name: "trial", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[전범재판의 증언들] \ #text(size: 5.1pt, fill: gray.darken(40%))[두 학살이 세계에 드러난다 · 아리·라우라도 그때 처음 안다(다음 장)]]))
    line("issue", "lord", stroke: (paint: black, thickness: .7pt))
    line("lord", "gf", stroke: (paint: black, thickness: .7pt))
    lbl((1.60, -3.85), [막내])
    line("issue", "arvid", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((7.45, -1.40), [빼야 한다고 한 쪽])
    line("thal", "regT", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("blum", "regB", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("regB", "massA", stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((11.40, -8.50), [집권하자마자])
    line("massA", "fran", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((5.80, -8.50), [혼자 살아남는다])
    line("duke2", "fran", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    line((13.7, -9.05), (9.0, -10.3), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((11.35, -9.68), [보복학살])
    line("coup", "exile", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("exile", "ariLaura", stroke: (paint: black, thickness: .7pt))
    line((7.4, -9.05), (7.4, -9.6), (9.6, -9.6), (9.6, -11.4), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line((8.0, -10.85), (8.8, -11.4), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((3.3, -1.5), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[구종가 당주의 첫째 자녀] \ #text(size: 5.1pt, fill: gray.darken(40%))[승계법의 빈칸 · 그 빈칸을 채운 차별이 전쟁의 원인 · 뒷날 가주가 되어 천수를 누렸고 자녀가 없다]]))
    content((1.6, -3.0), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 구종가 당주] \ #text(size: 5.1pt, fill: gray.darken(40%))[하루의 친증조할아버지]]))
    content((1.6, -4.7), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 친할아버지] \ #text(size: 5.1pt, fill: gray.darken(40%))[첫째 자녀의 막내동생 · 다음 가주]]))
    content((4.3, -3.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[초대 여대공 나타샤 1세] \ #text(size: 5.1pt, fill: gray.darken(40%))[1등공신 → 대공위 · 초대 국서 올렉사 1세(어부 출신, 부인 성씨 하사)]]))
    content((7.2, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 가문] \ #text(size: 5.1pt, fill: gray.darken(40%))[가문 전체 참전 · 블루멘탈 분가를 멸망 직전까지]]))
    content((4.3, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드가 · 멜가 (젠트리)] \ #text(size: 5.1pt, fill: gray.darken(40%))[귀족과 혈연·혼맥 없음 · 승전 측이면서 전쟁 중 궤멸에 준하는 타격]]))
    content((7.2, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜-안토노프·안토노바] \ #text(size: 5.1pt, fill: gray.darken(40%))[생존]]))
    content((11.6, -1.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아르비드부르크 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 당주의 이복남동생을 따름 · 금서를 「엮음」 · 남녀노소 전멸 †]]))
    content((11.6, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜 종가] \ #text(size: 5.1pt, fill: gray.darken(40%))[전멸 †]]))
    content((15.0, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜-헤힝겐 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[세력이 줄었으나 생존]]))
    content((11.6, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[막판에 탈주해 성을 갈다]]))
    content((15.0, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[막판에 탈주해 성을 갈다]]))
    content((8.8, -6.9), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[절대적 맏이상속제] \ #text(size: 5.1pt, fill: gray.darken(40%))[성별 불문 · 「고르지 못하게 하려고」 · 직후 제정]]))
    content((11.6, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 정권(이쪽 구체제)] \ #text(size: 5.1pt, fill: gray.darken(40%))[뒷날 쿠데타로 집권 · 뒷날의 수반 탈베르크 발터 하랄트 6세]]))
    content((15.4, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 정권(저쪽 구체제)] \ #text(size: 5.1pt, fill: gray.darken(40%))[쿠데타로 집권 · 수반 블루멘탈 요아힘 지기스문트 — 학살을 명령]]))
    content((13.5, -10.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[금서 도난] \ #text(size: 5.1pt, fill: gray.darken(40%))[두 집 중 한쪽 — 정하지 않는다 → 3차의 도화선]]))
    content((7.4, -8.5), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 학살] \ #text(size: 5.1pt, fill: gray.darken(40%))[집권 직후의 앙갚음 · 가문 전체 †]]))
    content((4.2, -8.5), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란] \ #text(size: 5.1pt, fill: gray.darken(40%))[유일 생존자 · 모친 에밀리아 · 마사코가 도주 도움 · 대공국 거쳐 이쪽으로]]))
    content((1.3, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[선대 대공(2대) 올렉사 2세] \ #text(size: 5.1pt, fill: gray.darken(40%))[유골 안장 · 출생 기록 보관]]))
    content((7.4, -10.3), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드가 · 멜가의 역쿠데타] \ #text(size: 5.1pt, fill: gray.darken(40%))[진압 → 보복학살 · 한 가정씩 탈출]]))
    content((4.2, -10.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[망명한 두 가정] \ #text(size: 5.1pt, fill: gray.darken(40%))[이쪽에서 극심한 빈곤 · 둘만 남기고 아사 †]]))
    content((1.3, -10.3), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리 · 멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[젠트리 두 집의 마지막 · 아리·라우라 외에는 귀족과 혈연·혼맥 전무]]))
    content((8.8, -11.9), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[전범재판의 증언들] \ #text(size: 5.1pt, fill: gray.darken(40%))[두 학살이 세계에 드러난다 · 아리·라우라도 그때 처음 안다(다음 장)]]))
    line((0.4, -12.95), (1.0, -12.95), stroke: (paint: black, thickness: .7pt))
    content((1.1, -12.95), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -12.95), (3.15, -12.95), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -12.95), (3.15, -12.95), stroke: (paint: white, thickness: .8pt))
    content((3.25, -12.95), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -12.95), (5.299999999999999, -12.95), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -12.95), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -12.95), (7.449999999999999, -12.95), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -12.95), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -12.95), (9.6, -12.95), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -12.95), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -12.95), (11.75, -12.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -12.95), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -12.95), (13.9, -12.95), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -12.95), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -12.95), (16.05, -12.95), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -12.95), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ② 제2차 계승전쟁(3-6·2-2, 설정집 전용·내레이션 층). 승계법의 빈칸을 채운 차별이 원인이고, 편은 한 집안이 아니라 사회 전체에 그어졌다 — 절대적 맏이상속제를 지지한 진보적 귀족·젠트리·요먼·부르주아의 연합 대 보수적 귀족의 연합. 붉은 화살표는 그 뒤 블루멘탈 정권이 한 일(집권 직후의 학살·보복학살), 파랑은 은인. 모드가·멜가(귀족과 혈연·혼맥이 일절 없던 젠트리 집안)와 호헨아스카니아의 자리가 아리·라우라·프란의 출신이 된다(판본 2.2 · 2.7.1).],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[금서전쟁 — 권력의 집과 세 자매])
    content((2.4, -1.0), name: "thal6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 발터 하랄트 6세] \ #text(size: 5.1pt, fill: gray.darken(40%))[이쪽 구체제 수반]]))
    content((7.0, -1.0), name: "felix", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 로흐스 펠릭스] \ #text(size: 5.1pt, fill: gray.darken(40%))[아버지 † 그 밤 · 평토장]]))
    content((10.6, -1.0), name: "rosa", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 로자 프레데리케] \ #text(size: 5.1pt, fill: gray.darken(40%))[어머니 † 그 밤]]))
    content((15.2, -1.0), name: "sigis", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 요아힘 지기스문트] \ #text(size: 5.1pt, fill: gray.darken(40%))[저쪽 구체제 수반]]))
    content((0.9, -2.6), name: "thal_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[이쪽 수반의 부인] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 그 밤을 알고 막지 않았다]]))
    content((4.2, -2.6), name: "halfbro", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[이복형] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 아버지의 혼외자 · 권력의 심층부에서 반인륜범죄 · 사형 → 교수형 †]]))
    content((13.1, -3.05), name: "ex_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[저쪽 수반의 전처] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · † 아이들 앞에서 · 로자에게 길을 열어 주었다]]))
    content((16.7, -3.05), name: "new_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[저쪽 수반의 후처] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음]]))
    content((3.4, -4.4), name: "cous_thal", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(이쪽 수반의 자녀들)] \ #text(size: 5.1pt, fill: gray.darken(40%))[그 밤 부모를 고발]]))
    content((3.4, -5.9), name: "cous_half", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(이복형의 자녀들)] \ #text(size: 5.1pt, fill: gray.darken(40%))[고발]]))
    content((6.6, -4.4), name: "eiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[에이란] \ #text(size: 5.1pt, fill: gray.darken(40%))['S' · 맏이 · 금서와 함께 소멸 †]]))
    content((8.8, -4.4), name: "reiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란] \ #text(size: 5.1pt, fill: gray.darken(40%))['W' · 둘째 · 저쪽으로 · 송출]]))
    content((11.5, -4.4), name: "seiran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[리지 세이란 · 막내 · 이쪽 「학교」 · 전사 → 부활]]))
    content((13.9, -5.9), name: "cous_ex", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(전처 소생)]]))
    content((16.5, -5.9), name: "cous_new", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(후처 소생)]]))
    line((8.8, -1.25), (8.8, -3.3), stroke: (paint: black, thickness: .7pt))
    line((6.6, -3.3), (11.5, -3.3), stroke: (paint: black, thickness: .7pt))
    line((6.6, -3.3), (6.6, -3.95), stroke: (paint: black, thickness: .7pt))
    line((8.8, -3.3), (8.8, -3.95), stroke: (paint: black, thickness: .7pt))
    line((11.5, -3.3), (11.5, -3.95), stroke: (paint: black, thickness: .7pt))
    lbl((8.8, -2.85), [일란성 세쌍둥이 · −15년 4/7 · 블루멘탈베르크])
    line("thal6", "felix", stroke: (paint: black, thickness: .7pt))
    lbl((4.70, -1.00), [친형제])
    line("rosa", "sigis", stroke: (paint: black, thickness: .7pt))
    lbl((12.90, -1.00), [친남매])
    line("felix", "rosa", stroke: (paint: black, thickness: 1.7pt))
    line("felix", "rosa", stroke: (paint: white, thickness: .8pt))
    line((2.4, -1.55), (2.4, -1.9), (6.4, -1.9), (6.4, -1.5), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((4.40, -1.90), [암살 명령])
    line((15.2, -1.55), (15.2, -1.9), (11.2, -1.9), (11.2, -1.5), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((13.20, -1.90), [암살 명령])
    line("thal_wife", "thal6", stroke: (paint: black, thickness: 1.7pt))
    line("thal_wife", "thal6", stroke: (paint: white, thickness: .8pt))
    line("halfbro", "thal6", stroke: (paint: black, thickness: .7pt))
    lbl((3.30, -1.80), [이복형])
    line("ex_wife", "sigis", stroke: (paint: black, thickness: 1.7pt))
    line("ex_wife", "sigis", stroke: (paint: white, thickness: .8pt))
    lbl((14.15, -2.02), [전처])
    line("new_wife", "sigis", stroke: (paint: black, thickness: 1.7pt))
    line("new_wife", "sigis", stroke: (paint: white, thickness: .8pt))
    lbl((15.95, -2.02), [후처])
    line("ex_wife", "rosa", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    line("thal6", "cous_thal", stroke: (paint: black, thickness: .7pt))
    line("halfbro", "cous_half", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cous_ex", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cous_new", stroke: (paint: black, thickness: .7pt))
    line((6.6, -4.85), (6.6, -5.45), (8.8, -5.45), (8.8, -4.9), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((7.70, -5.45), [해제법을 주었다(2-6)])
    content((2.4, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 발터 하랄트 6세] \ #text(size: 5.1pt, fill: gray.darken(40%))[이쪽 구체제 수반]]))
    content((7.0, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 로흐스 펠릭스] \ #text(size: 5.1pt, fill: gray.darken(40%))[아버지 † 그 밤 · 평토장]]))
    content((10.6, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 로자 프레데리케] \ #text(size: 5.1pt, fill: gray.darken(40%))[어머니 † 그 밤]]))
    content((15.2, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 요아힘 지기스문트] \ #text(size: 5.1pt, fill: gray.darken(40%))[저쪽 구체제 수반]]))
    content((0.9, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[이쪽 수반의 부인] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 그 밤을 알고 막지 않았다]]))
    content((4.2, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[이복형] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 아버지의 혼외자 · 권력의 심층부에서 반인륜범죄 · 사형 → 교수형 †]]))
    content((13.1, -3.05), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[저쪽 수반의 전처] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · † 아이들 앞에서 · 로자에게 길을 열어 주었다]]))
    content((16.7, -3.05), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[저쪽 수반의 후처] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음]]))
    content((3.4, -4.4), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(이쪽 수반의 자녀들)] \ #text(size: 5.1pt, fill: gray.darken(40%))[그 밤 부모를 고발]]))
    content((3.4, -5.9), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(이복형의 자녀들)] \ #text(size: 5.1pt, fill: gray.darken(40%))[고발]]))
    content((6.6, -4.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[에이란] \ #text(size: 5.1pt, fill: gray.darken(40%))['S' · 맏이 · 금서와 함께 소멸 †]]))
    content((8.8, -4.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란] \ #text(size: 5.1pt, fill: gray.darken(40%))['W' · 둘째 · 저쪽으로 · 송출]]))
    content((11.5, -4.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[리지 세이란 · 막내 · 이쪽 「학교」 · 전사 → 부활]]))
    content((13.9, -5.9), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(전처 소생)]]))
    content((16.5, -5.9), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(후처 소생)]]))
    line((0.4, -7.75), (1.0, -7.75), stroke: (paint: black, thickness: .7pt))
    content((1.1, -7.75), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -7.75), (3.15, -7.75), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -7.75), (3.15, -7.75), stroke: (paint: white, thickness: .8pt))
    content((3.25, -7.75), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -7.75), (5.299999999999999, -7.75), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -7.75), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -7.75), (7.449999999999999, -7.75), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -7.75), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -7.75), (9.6, -7.75), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -7.75), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -7.75), (11.75, -7.75), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -7.75), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -7.75), (13.9, -7.75), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -7.75), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -7.75), (16.05, -7.75), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -7.75), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ③ 제3차 계승전쟁(금서전쟁) — 권력의 집과 세 자매(2-2·2-5). 두 수반은 형제이고, 세 자매의 부모는 그 사이에서 나온다. 세 자매가 어디로 갔는지는 ⑤에 있다.],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[금서전쟁 — 곁에 있던 사람들])
    content((1.8, -1.2), name: "haru_par", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 아버지 · 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[신종가 가주(양위) · 원작 제8권]]))
    content((5.2, -1.2), name: "hein_par", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하인리히의 부모] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 가주 내외 · 하루의 백부모 · 극비 문서를 만들어 봉인]]))
    content((0.85, -3.0), name: "haru_sis", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 언니] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 슈타우펜 즉사]]))
    content((2.85, -3.0), name: "haru", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트 할프레드 · 「학교」 학생 → 신종가 가주]]))
    content((7.4, -3.0), name: "hein", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하인리히] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트 하인리히 카를 † · 부모를 알던 사람 · 부모의 무덤을 만들었다 · 처형]]))
    content((4.5, -4.8), name: "six", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[동생 여섯] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 문 앞 스크럼 · 안할트가 묘지]]))
    content((10.4, -4.8), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란 선생] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 교사 · 하인리히의 죽마고우 · 함구]]))
    content((7.8, -6.5), name: "frieda", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[프리다] \ #text(size: 5.1pt, fill: gray.darken(40%))[하인리히의 유복녀 — 그가 알고 인정한 아이 · 종전 21일 전 출생]]))
    content((13.4, -1.2), name: "duke3", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[현 대공(3대) 게오르그-구스타프] \ #text(size: 5.1pt, fill: gray.darken(40%))[부친 볼로디미르(일찍 병사 †) · 그 밤 마차 떼 · 호위 병력]]))
    content((16.3, -1.2), name: "duke2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[선대 대공(2대) 올렉사 2세] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 독살(가족과 함께)]]))
    content((13.4, -3.0), name: "police", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[국제경찰] \ #text(size: 5.1pt, fill: gray.darken(40%))[긴급국제체포영장 · 추격 · 인계]]))
    content((16.3, -3.0), name: "icc", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[국제형사재판소(가칭)] \ #text(size: 5.1pt, fill: gray.darken(40%))[영장 발부]]))
    line("haru_par", "hein_par", stroke: (paint: black, thickness: .7pt))
    lbl((3.50, -1.20), [형제])
    line("haru_par", "haru", stroke: (paint: black, thickness: .7pt))
    line("haru_par", "haru_sis", stroke: (paint: black, thickness: .7pt))
    line("hein_par", "hein", stroke: (paint: black, thickness: .7pt))
    lbl((6.30, -2.10), [맏이])
    line("hein_par", "six", stroke: (paint: black, thickness: .7pt))
    line("hein", "fran", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((8.90, -3.90), [죽마고우])
    line("hein", "frieda", stroke: (paint: black, thickness: .7pt))
    lbl((7.60, -4.75), [아버지])
    line("fran", "frieda", stroke: (paint: black, thickness: .7pt))
    line("duke3", "police", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("icc", "police", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((1.8, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 아버지 · 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[신종가 가주(양위) · 원작 제8권]]))
    content((5.2, -1.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하인리히의 부모] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 가주 내외 · 하루의 백부모 · 극비 문서를 만들어 봉인]]))
    content((0.85, -3.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 언니] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 슈타우펜 즉사]]))
    content((2.85, -3.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트 할프레드 · 「학교」 학생 → 신종가 가주]]))
    content((7.4, -3.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하인리히] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트 하인리히 카를 † · 부모를 알던 사람 · 부모의 무덤을 만들었다 · 처형]]))
    content((4.5, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[동생 여섯] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 문 앞 스크럼 · 안할트가 묘지]]))
    content((10.4, -4.8), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란 선생] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 교사 · 하인리히의 죽마고우 · 함구]]))
    content((7.8, -6.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[프리다] \ #text(size: 5.1pt, fill: gray.darken(40%))[하인리히의 유복녀 — 그가 알고 인정한 아이 · 종전 21일 전 출생]]))
    content((13.4, -1.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[현 대공(3대) 게오르그-구스타프] \ #text(size: 5.1pt, fill: gray.darken(40%))[부친 볼로디미르(일찍 병사 †) · 그 밤 마차 떼 · 호위 병력]]))
    content((16.3, -1.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[선대 대공(2대) 올렉사 2세] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 독살(가족과 함께)]]))
    content((13.4, -3.0), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[국제경찰] \ #text(size: 5.1pt, fill: gray.darken(40%))[긴급국제체포영장 · 추격 · 인계]]))
    content((16.3, -3.0), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[국제형사재판소(가칭)] \ #text(size: 5.1pt, fill: gray.darken(40%))[영장 발부]]))
    line((0.4, -7.949999999999999), (1.0, -7.949999999999999), stroke: (paint: black, thickness: .7pt))
    content((1.1, -7.949999999999999), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -7.949999999999999), (3.15, -7.949999999999999), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -7.949999999999999), (3.15, -7.949999999999999), stroke: (paint: white, thickness: .8pt))
    content((3.25, -7.949999999999999), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -7.949999999999999), (5.299999999999999, -7.949999999999999), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -7.949999999999999), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -7.949999999999999), (7.449999999999999, -7.949999999999999), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -7.949999999999999), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -7.949999999999999), (9.6, -7.949999999999999), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -7.949999999999999), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -7.949999999999999), (11.75, -7.949999999999999), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -7.949999999999999), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -7.949999999999999), (13.9, -7.949999999999999), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -7.949999999999999), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -7.949999999999999), (16.05, -7.949999999999999), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -7.949999999999999), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ④ 제3차 계승전쟁 — 곁에 있던 사람들(2-2·2-5-c·5-6·제19.5화). 하루네 집과 안할트가, 프란과 프리다, 대공가와 국제기구. ⚠ 이들은 세 자매의 설계를 알지 못한다 — 하인리히와 프란만 한 조각씩 안다.],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[금서전쟁 — 「학교」와 그날])
    content((1.3, -1.2), name: "omi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[오미 선생] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 교사]]))
    content((4.0, -1.2), name: "mimi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[미미] \ #text(size: 5.1pt, fill: gray.darken(40%))[카가리 미미 · 불로불사(어머니의 소생)]]))
    content((6.6, -1.2), name: "shina", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[시나] \ #text(size: 5.1pt, fill: gray.darken(40%))[토츠키 시나 · 가문 밖의 고아 · 미미의 짝]]))
    content((9.2, -1.2), name: "laura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[시나의 전 룸메이트 · 1화 전 전사 → 부활]]))
    content((11.8, -1.2), name: "ari", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란의 룸메이트 · 그 밤 마차에]]))
    content((14.4, -1.2), name: "esta", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타 · 헤더 · 리카] \ #text(size: 5.1pt, fill: gray.darken(40%))[셋 · 헤더는 부활자]]))
    content((16.7, -1.2), name: "senpai", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[남자 선배] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란이 구했다]]))
    content((4.0, -2.8), name: "mimi_mom", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[카가리 마사코 (미미의 어머니)] \ #text(size: 5.1pt, fill: gray.darken(40%))[평민 미혼모 · 프란 도주 도움 · † 생명을 소진해 소생 · 제14화 後編 블루멘푸르트 합장]]))
    content((10.1, -2.8), name: "clea", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[클레아 (쿠 쨩) · 다른 여학생들 · 2화의 아이] \ #text(size: 5.1pt, fill: gray.darken(40%))[클레아는 하루의 룸메이트 · 대중교통·도시공학 천재성 · 천도·수도 재정비·3국 국제교통망 주도 · 종장~미래편 前編 사이 자연사]]))
    content((2.6, -4.8), name: "relay", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[신호를 이어 준 사람들] \ #text(size: 5.1pt, fill: gray.darken(40%))[저쪽 지하 언론인들 · 세계의 언론인들 · 이름 없음 · 여럿이 † (3-6)]]))
    content((6.6, -4.8), name: "reporter", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[외신기자] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 문 밖의 보는 얼굴 · 찍어 나갔다]]))
    content((10.2, -4.8), name: "crowd", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[시위대] \ #text(size: 5.1pt, fill: gray.darken(40%))[얼굴 없음 · 거리 · 세이란에게 길을]]))
    content((13.8, -4.8), name: "employees", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 종가의 피고용인들] \ #text(size: 5.1pt, fill: gray.darken(40%))[지기스문트를 슈타우펜에서 붙잡다]]))
    content((8.4, -6.6), name: "night", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 7.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[종전의 밤 — 0년 4월 7일] \ #text(size: 5.1pt, fill: gray.darken(40%))[폭로방송 · 여섯의 화형 · 에이란의 소멸 · 세이란의 부활과 첫 만남 · 두 자매의 15번째 생일]]))
    line("mimi_mom", "mimi", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((4.00, -2.00), [소생])
    line("mimi", "shina", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((5.30, -1.20), [짝])
    line("shina", "laura", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((7.90, -1.20), [전 룸메이트])
    line("relay", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("reporter", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("crowd", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("employees", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((1.3, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[오미 선생] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 교사]]))
    content((4.0, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[미미] \ #text(size: 5.1pt, fill: gray.darken(40%))[카가리 미미 · 불로불사(어머니의 소생)]]))
    content((6.6, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[시나] \ #text(size: 5.1pt, fill: gray.darken(40%))[토츠키 시나 · 가문 밖의 고아 · 미미의 짝]]))
    content((9.2, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[시나의 전 룸메이트 · 1화 전 전사 → 부활]]))
    content((11.8, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란의 룸메이트 · 그 밤 마차에]]))
    content((14.4, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타 · 헤더 · 리카] \ #text(size: 5.1pt, fill: gray.darken(40%))[셋 · 헤더는 부활자]]))
    content((16.7, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[남자 선배] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란이 구했다]]))
    content((4.0, -2.8), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[카가리 마사코 (미미의 어머니)] \ #text(size: 5.1pt, fill: gray.darken(40%))[평민 미혼모 · 프란 도주 도움 · † 생명을 소진해 소생 · 제14화 後編 블루멘푸르트 합장]]))
    content((10.1, -2.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[클레아 (쿠 쨩) · 다른 여학생들 · 2화의 아이] \ #text(size: 5.1pt, fill: gray.darken(40%))[클레아는 하루의 룸메이트 · 대중교통·도시공학 천재성 · 천도·수도 재정비·3국 국제교통망 주도 · 종장~미래편 前編 사이 자연사]]))
    content((2.6, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[신호를 이어 준 사람들] \ #text(size: 5.1pt, fill: gray.darken(40%))[저쪽 지하 언론인들 · 세계의 언론인들 · 이름 없음 · 여럿이 † (3-6)]]))
    content((6.6, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[외신기자] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 문 밖의 보는 얼굴 · 찍어 나갔다]]))
    content((10.2, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[시위대] \ #text(size: 5.1pt, fill: gray.darken(40%))[얼굴 없음 · 거리 · 세이란에게 길을]]))
    content((13.8, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 종가의 피고용인들] \ #text(size: 5.1pt, fill: gray.darken(40%))[지기스문트를 슈타우펜에서 붙잡다]]))
    content((8.4, -6.6), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 7.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[종전의 밤 — 0년 4월 7일] \ #text(size: 5.1pt, fill: gray.darken(40%))[폭로방송 · 여섯의 화형 · 에이란의 소멸 · 세이란의 부활과 첫 만남 · 두 자매의 15번째 생일]]))
    line((0.4, -8.15), (1.0, -8.15), stroke: (paint: black, thickness: .7pt))
    content((1.1, -8.15), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -8.15), (3.15, -8.15), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -8.15), (3.15, -8.15), stroke: (paint: white, thickness: .8pt))
    content((3.25, -8.15), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -8.15), (5.299999999999999, -8.15), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -8.15), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -8.15), (7.449999999999999, -8.15), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -8.15), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -8.15), (9.6, -8.15), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -8.15), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -8.15), (11.75, -8.15), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -8.15), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -8.15), (13.9, -8.15), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -8.15), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -8.15), (16.05, -8.15), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -8.15), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ⑤ 제3차 계승전쟁 — 「학교」와 그날(2-5·2-7·3-6). 병기로 길러진 아이들과 그들을 가르친 사람, 그리고 종전의 밤에 바깥에 있던 사람들. ⚠ 세 자매가 여기에도 있다(③ 참조) — 같은 사람이 두 장에 나오는 것은 이 도표의 형식이다.],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[전쟁의 뒤 — 재판과 성의 향방])
    content((1.6, -1.3), name: "judge", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[재판장] \ #text(size: 5.1pt, fill: gray.darken(40%))[군대 없는 중립국의 수장 · 대공국 출신]]))
    content((5.0, -1.3), name: "thal6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 발터 하랄트 6세] \ #text(size: 5.1pt, fill: gray.darken(40%))[종신형(제14화 後編 뒤 ×8) · 화면에는 내레이션의 호명 한 번뿐]]))
    content((8.6, -1.3), name: "sigis", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 요아힘 지기스문트] \ #text(size: 5.1pt, fill: gray.darken(40%))[종신형(×6→×8) · 면회실의 유리 저쪽 · 「부디 장수하십시오」]]))
    content((12.2, -1.3), name: "spouses", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[두 수반의 배우자들] \ #text(size: 5.1pt, fill: gray.darken(40%))[재판을 받았고 형은 다르다 · 화면에 오르지 않는다(2-2)]]))
    content((15.6, -1.3), name: "witness", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[증언대의 얼굴] \ #text(size: 5.1pt, fill: gray.darken(40%))[사촌들의 증언 · 대공가 사람들과 프란의 증언(두 학살) · 그날 불려 나온 사람]]))
    content((3.2, -3.2), name: "cousT", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[친가 쪽 사촌들] \ #text(size: 5.1pt, fill: gray.darken(40%))[14남(호헨마이센-탈베르크) 후손 · 성을 버림 → 대공국이 선물한 성 「안할트-니더비텐베르크」]]))
    content((7.0, -3.2), name: "cousB", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[외가 쪽 사촌들] \ #text(size: 5.1pt, fill: gray.darken(40%))[14남(호헨마이센-블루멘탈) 후손 · 블루멘탈베르크를 받음 · 5촌 조카(변호사, 제20.7화) — 남자 선배에게 법을 배웠다]]))
    content((14.6, -3.2), name: "pres", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[남자 선배 → 대통령] \ #text(size: 5.1pt, fill: gray.darken(40%))[소년병 → 법학도 → 인권변호사 → 로스쿨 교수(석좌) → 최다선 의원 → 대통령 · 임기 중 서거(제21화) †]]))
    content((1.6, -6.5), name: "haru", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루] \ #text(size: 5.1pt, fill: gray.darken(40%))[신종가 가주 → 양위]]))
    content((1.6, -5.0), name: "haru_par", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 아버지 · 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[형 내외의 무덤을 열어 DNA로 확인]]))
    content((5.0, -6.5), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란] \ #text(size: 5.1pt, fill: gray.darken(40%))[제19.5화의 고백 · 신종가가 가족으로 인정]]))
    content((9.1, -6.5), name: "frieda", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[프리다] \ #text(size: 5.1pt, fill: gray.darken(40%))[극비 문서로 안할트-헤힝겐 성 · 안할트-호헨아스카니아-헤힝겐-펠덴부르크 · 뒷날 다섯쌍둥이 가운데 한 명과 사돈]]))
    line("judge", "thal6", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("judge", "sigis", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("thal6", "cousT", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cousB", stroke: (paint: black, thickness: .7pt))
    line("pres", "cousB", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((10.80, -3.20), [법을 가르쳤다])
    line("haru_par", "haru", stroke: (paint: black, thickness: .7pt))
    lbl((1.60, -5.75), [양위])
    line("haru_par", "fran", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((3.30, -5.75), [가족으로 인정])
    line("fran", "frieda", stroke: (paint: black, thickness: .7pt))
    content((1.6, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[재판장] \ #text(size: 5.1pt, fill: gray.darken(40%))[군대 없는 중립국의 수장 · 대공국 출신]]))
    content((5.0, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 발터 하랄트 6세] \ #text(size: 5.1pt, fill: gray.darken(40%))[종신형(제14화 後編 뒤 ×8) · 화면에는 내레이션의 호명 한 번뿐]]))
    content((8.6, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 요아힘 지기스문트] \ #text(size: 5.1pt, fill: gray.darken(40%))[종신형(×6→×8) · 면회실의 유리 저쪽 · 「부디 장수하십시오」]]))
    content((12.2, -1.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[두 수반의 배우자들] \ #text(size: 5.1pt, fill: gray.darken(40%))[재판을 받았고 형은 다르다 · 화면에 오르지 않는다(2-2)]]))
    content((15.6, -1.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[증언대의 얼굴] \ #text(size: 5.1pt, fill: gray.darken(40%))[사촌들의 증언 · 대공가 사람들과 프란의 증언(두 학살) · 그날 불려 나온 사람]]))
    content((3.2, -3.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[친가 쪽 사촌들] \ #text(size: 5.1pt, fill: gray.darken(40%))[14남(호헨마이센-탈베르크) 후손 · 성을 버림 → 대공국이 선물한 성 「안할트-니더비텐베르크」]]))
    content((7.0, -3.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[외가 쪽 사촌들] \ #text(size: 5.1pt, fill: gray.darken(40%))[14남(호헨마이센-블루멘탈) 후손 · 블루멘탈베르크를 받음 · 5촌 조카(변호사, 제20.7화) — 남자 선배에게 법을 배웠다]]))
    content((14.6, -3.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[남자 선배 → 대통령] \ #text(size: 5.1pt, fill: gray.darken(40%))[소년병 → 법학도 → 인권변호사 → 로스쿨 교수(석좌) → 최다선 의원 → 대통령 · 임기 중 서거(제21화) †]]))
    content((1.6, -6.5), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루] \ #text(size: 5.1pt, fill: gray.darken(40%))[신종가 가주 → 양위]]))
    content((1.6, -5.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 아버지 · 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[형 내외의 무덤을 열어 DNA로 확인]]))
    content((5.0, -6.5), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란] \ #text(size: 5.1pt, fill: gray.darken(40%))[제19.5화의 고백 · 신종가가 가족으로 인정]]))
    content((9.1, -6.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[프리다] \ #text(size: 5.1pt, fill: gray.darken(40%))[극비 문서로 안할트-헤힝겐 성 · 안할트-호헨아스카니아-헤힝겐-펠덴부르크 · 뒷날 다섯쌍둥이 가운데 한 명과 사돈]]))
    line((0.4, -7.75), (1.0, -7.75), stroke: (paint: black, thickness: .7pt))
    content((1.1, -7.75), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -7.75), (3.15, -7.75), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -7.75), (3.15, -7.75), stroke: (paint: white, thickness: .8pt))
    content((3.25, -7.75), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -7.75), (5.299999999999999, -7.75), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -7.75), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -7.75), (7.449999999999999, -7.75), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -7.75), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -7.75), (9.6, -7.75), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -7.75), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -7.75), (11.75, -7.75), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -7.75), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -7.75), (13.9, -7.75), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -7.75), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -7.75), (16.05, -7.75), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -7.75), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ⑥ 금서전쟁의 뒤 — 재판과 성의 향방(5-2·2-2·제19.5화). 두 수반이 나란히 서고, 그 아래 세대가 성을 버리거나 받는다. 프란과 프리다에게 온 것도 여기다. ⚠ 사람이 적은 장이고, 적은 것이 이 자리의 성질이다.],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[관계와 아이들, 그리고 먼 뒤])
    content((1.35, -1.2), name: "shina", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[시나]]))
    content((3.1, -1.2), name: "mimi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[미미]]))
    content((5.3, -1.2), name: "reiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란]]))
    content((7.05, -1.2), name: "laura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[라우라]]))
    content((9.25, -1.2), name: "seiran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란]]))
    content((11.0, -1.2), name: "ari", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[아리]]))
    content((13.2, -1.2), name: "esta", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타]]))
    content((14.9, -1.2), name: "heather", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[헤더]]))
    content((16.6, -1.2), name: "rika", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[리카]]))
    content((2.1, -4.3), name: "nine", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[아홉 딸] \ #text(size: 5.1pt, fill: gray.darken(40%))[맏이 → 대통령 · 막내 → 대공국 총리 · 가운데 일곱은 각자 다른 나라에서]]))
    content((6.2, -4.3), name: "d_rl", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란의 딸 둘 · 라우라의 딸 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[레이란 — 라우라 미란 · 아말리아 카란(이란성 쌍둥이) / 라우라 — 안토니아 2세 · 소피아 2세]]))
    content((11.2, -4.3), name: "d_sa", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 5.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란의 딸 넷 · 아리의 딸 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란 — 프레데리케 루디 스즈란 · 프리다 펠리시아 주란(이란성) · 할프리트 마르가레테 케이란 · 아델라 아리 아이란(일란성) / 아리 — 레티시아 3세 · 프레시스 2세]]))
    content((15.8, -4.3), name: "quint", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[다섯쌍둥이 남매] \ #text(size: 5.1pt, fill: gray.darken(40%))[제22화의 노인 다섯 · 한 명이 프리다와 사돈(어느 쪽인지 정하지 않는다)]]))
    content((2.2, -6.7), name: "acting", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[권한대행 → 조기대선] \ #text(size: 5.1pt, fill: gray.darken(40%))[당선자가 즉시 취임(2-12)]]))
    content((6.4, -6.7), name: "funeral", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[다섯 겹의 국장(+78년)] \ #text(size: 5.1pt, fill: gray.darken(40%))[대통령 · 세이란 · 레이란 · 라우라 · 아리]]))
    content((11.6, -6.7), name: "ferd", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 페르디난트] \ #text(size: 5.1pt, fill: gray.darken(40%))[헤더·리카가 지킨 아이 · 하루가 입양]]))
    content((14.9, -6.7), name: "fwife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[처 — 아델라 아리 아이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란의 막내딸 · 세이란은 일곱 딸의 외할머니다(판본 1.69)]]))
    content((2.2, -10.1), name: "pres100", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[대통령(백 년 뒤)] \ #text(size: 5.1pt, fill: gray.darken(40%))[맏이가 당선 훨씬 전부터 수십 년에 걸쳐 가르친 후계자이자 직후임]]))
    content((9.4, -10.1), name: "premier", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[대공국 총리(백 년 뒤)] \ #text(size: 5.1pt, fill: gray.darken(40%))[아홉째]]))
    content((13.4, -10.1), name: "seven", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 4.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[일곱 딸] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-블루멘탈베르크 하이케 카를라 1세 · 페르디난다 하이데 1세 · 앨리스 리카 · 실비아 에스타 1세 · 카트리나 에이란 · 에밀리아 레이란 · 미아 레나 세이란 · 백 년 뒤의 그 자리에 전원]]))
    content((1.9, -12.7), name: "duke3", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[현 대공(3대)] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 게오르그-구스타프 · 헤더와 리카의 관을 싣고 갔다가 급사 †]]))
    content((6.6, -12.7), name: "duke4", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[4대 여대공] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 카타리나-테레지아 엘리자베트 · 현 대공의 차녀 · 평생 독신 · 다섯쌍둥이에게 합장을 제안]]))
    content((11.0, -12.7), name: "duke5", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[5대 여대공 나타샤 2세] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 나타샤 2세 · 4대의 양딸(장녀의 무남독녀 · 생후 두 달 입양)]]))
    content((15.3, -12.7), name: "duke6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[6대 여대공 아가타 1세 · 흑인 국서] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 아가타 1세(5대의 무남독녀 · 미래편 직전 양위) · 국서는 엄청난 딸바보]]))
    content((1.35, -15.1), name: "ferd2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[2대 기록관장] \ #text(size: 5.1pt, fill: gray.darken(40%))[페르디난트 · 백 년 뒤에 판다]]))
    content((4.45, -15.1), name: "desc", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란의 여계 후손] \ #text(size: 5.1pt, fill: gray.darken(40%))[mtDNA 대조]]))
    content((7.85, -15.1), name: "males", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[순수 남계 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[대공국 사람 · 이 Y만 쓸 수 있다 — 다른 Y는 양자라 불가]]))
    content((11.35, -15.1), name: "envoy", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[사절단 · 헬기의 촬영기자]]))
    content((15.3, -15.1), name: "duke7", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[지명계승자 — 아가타 날라] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 아가타 날라 · 첫 흑백혼혈 가주 예정 · 둘째딸(언니와 이란성 쌍둥이) · 유년기 선상 생활 · 국제 구혼 쇄도]]))
    line("funeral", "acting", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("nine", "acting", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((2.15, -5.50), [맏이가 당선])
    line((2.1, -4.9), (2.1, -5.4), (9.4, -5.4), (9.4, -9.5), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((5.75, -5.40), [막내])
    line("duke3", "duke4", stroke: (paint: black, thickness: .7pt))
    lbl((4.25, -12.70), [차녀])
    line("duke4", "duke5", stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    lbl((8.80, -12.70), [지명])
    line("duke5", "duke6", stroke: (paint: black, thickness: .7pt))
    lbl((13.15, -12.70), [양위])
    line("duke6", "duke7", stroke: (paint: black, thickness: .7pt))
    lbl((15.30, -13.90), [지명(차녀)])
    line("ferd2", "desc", stroke: (paint: gray.darken(15%), thickness: .55pt))
    line("desc", "males", stroke: (paint: gray.darken(15%), thickness: .55pt))
    line("shina", (2.2, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("mimi", (2.2, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((2.2, -2.75), "nine", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((2.2, -2.75), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    line("reiran", (6.2, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("laura", (6.2, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((6.2, -2.75), "d_rl", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((6.2, -2.75), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    line("seiran", (9.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("ari", (9.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((9.9, -2.75), "d_sa", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((9.9, -2.75), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    line("esta", (14.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("heather", (14.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("rika", (14.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((14.9, -2.75), "quint", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((14.9, -2.75), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    lbl((15.52, -2.75), [셋])
    line("ferd", (13.4, -8.6), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("fwife", (13.4, -8.6), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((13.4, -8.6), "seven", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((13.4, -8.6), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    content((1.35, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[시나]]))
    content((3.1, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[미미]]))
    content((5.3, -1.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란]]))
    content((7.05, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[라우라]]))
    content((9.25, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란]]))
    content((11.0, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[아리]]))
    content((13.2, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타]]))
    content((14.9, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[헤더]]))
    content((16.6, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[리카]]))
    content((2.1, -4.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[아홉 딸] \ #text(size: 5.1pt, fill: gray.darken(40%))[맏이 → 대통령 · 막내 → 대공국 총리 · 가운데 일곱은 각자 다른 나라에서]]))
    content((6.2, -4.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란의 딸 둘 · 라우라의 딸 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[레이란 — 라우라 미란 · 아말리아 카란(이란성 쌍둥이) / 라우라 — 안토니아 2세 · 소피아 2세]]))
    content((11.2, -4.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 5.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란의 딸 넷 · 아리의 딸 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란 — 프레데리케 루디 스즈란 · 프리다 펠리시아 주란(이란성) · 할프리트 마르가레테 케이란 · 아델라 아리 아이란(일란성) / 아리 — 레티시아 3세 · 프레시스 2세]]))
    content((15.8, -4.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[다섯쌍둥이 남매] \ #text(size: 5.1pt, fill: gray.darken(40%))[제22화의 노인 다섯 · 한 명이 프리다와 사돈(어느 쪽인지 정하지 않는다)]]))
    content((2.2, -6.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[권한대행 → 조기대선] \ #text(size: 5.1pt, fill: gray.darken(40%))[당선자가 즉시 취임(2-12)]]))
    content((6.4, -6.7), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[다섯 겹의 국장(+78년)] \ #text(size: 5.1pt, fill: gray.darken(40%))[대통령 · 세이란 · 레이란 · 라우라 · 아리]]))
    content((11.6, -6.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 페르디난트] \ #text(size: 5.1pt, fill: gray.darken(40%))[헤더·리카가 지킨 아이 · 하루가 입양]]))
    content((14.9, -6.7), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[처 — 아델라 아리 아이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란의 막내딸 · 세이란은 일곱 딸의 외할머니다(판본 1.69)]]))
    content((2.2, -10.1), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[대통령(백 년 뒤)] \ #text(size: 5.1pt, fill: gray.darken(40%))[맏이가 당선 훨씬 전부터 수십 년에 걸쳐 가르친 후계자이자 직후임]]))
    content((9.4, -10.1), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[대공국 총리(백 년 뒤)] \ #text(size: 5.1pt, fill: gray.darken(40%))[아홉째]]))
    content((13.4, -10.1), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 4.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[일곱 딸] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-블루멘탈베르크 하이케 카를라 1세 · 페르디난다 하이데 1세 · 앨리스 리카 · 실비아 에스타 1세 · 카트리나 에이란 · 에밀리아 레이란 · 미아 레나 세이란 · 백 년 뒤의 그 자리에 전원]]))
    content((1.9, -12.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[현 대공(3대)] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 게오르그-구스타프 · 헤더와 리카의 관을 싣고 갔다가 급사 †]]))
    content((6.6, -12.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[4대 여대공] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 카타리나-테레지아 엘리자베트 · 현 대공의 차녀 · 평생 독신 · 다섯쌍둥이에게 합장을 제안]]))
    content((11.0, -12.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[5대 여대공 나타샤 2세] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 나타샤 2세 · 4대의 양딸(장녀의 무남독녀 · 생후 두 달 입양)]]))
    content((15.3, -12.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[6대 여대공 아가타 1세 · 흑인 국서] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 아가타 1세(5대의 무남독녀 · 미래편 직전 양위) · 국서는 엄청난 딸바보]]))
    content((1.35, -15.1), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[2대 기록관장] \ #text(size: 5.1pt, fill: gray.darken(40%))[페르디난트 · 백 년 뒤에 판다]]))
    content((4.45, -15.1), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란의 여계 후손] \ #text(size: 5.1pt, fill: gray.darken(40%))[mtDNA 대조]]))
    content((7.85, -15.1), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[순수 남계 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[대공국 사람 · 이 Y만 쓸 수 있다 — 다른 Y는 양자라 불가]]))
    content((11.35, -15.1), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[사절단 · 헬기의 촬영기자]]))
    content((15.3, -15.1), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[지명계승자 — 아가타 날라] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 아가타 날라 · 첫 흑백혼혈 가주 예정 · 둘째딸(언니와 이란성 쌍둥이) · 유년기 선상 생활 · 국제 구혼 쇄도]]))
    line((0.4, -16.75), (1.0, -16.75), stroke: (paint: black, thickness: .7pt))
    content((1.1, -16.75), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -16.75), (3.15, -16.75), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -16.75), (3.15, -16.75), stroke: (paint: white, thickness: .8pt))
    content((3.25, -16.75), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -16.75), (5.299999999999999, -16.75), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -16.75), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -16.75), (7.449999999999999, -16.75), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -16.75), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -16.75), (9.6, -16.75), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -16.75), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -16.75), (11.75, -16.75), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -16.75), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -16.75), (13.9, -16.75), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -16.75), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -16.75), (16.05, -16.75), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -16.75), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
    line((0.4, -17.25), (1.0, -17.25), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((0.62, -17.25), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    content((1.1, -17.25), anchor: "west", text(size: 5.8pt)[관계(집합) → 아이들])
  }),
  caption: [인물관계도 ⑦ 관계와 아이들, 그리고 먼 뒤(2-11·2-12·제20화·제21화·백 년 뒤의 미래편). ★ 네 쌍과 페르디난트 가족을 같은 도형으로 그린다 — 유향 하이퍼엣지(초록, 토픽맵의 association 형식): 허브 하나가 그 관계이고 거기서 아이들로 화살표 하나가 나간다. ⚠ 출발점 집합 안을 도형이 가르지 않는다(누가 낳았는지 말하지 않는다 — 판본 2.3.1) · 도착점은 수만 있고 이름이 없다(누가 그 아이인지 확정하지 않는다) · 이성 짝에도 같은 도형을 쓴다. ⚠ 딸들의 이름은 원전의 표 그대로이고(판본 2.3.44에서 되살렸다 — ⑦장을 새로 만들 때 떨어져 있었다), 아래 줄은 대공가의 승계다.],
  supplement: none,
  numbering: none,
)
