// 인물관계도 v2.2 — 생성물. tools/relations_diagram_gen.py 가 만든다(KO/JA 록스텝). 손으로 고치지 않는다.
// 세 차례의 계승전쟁을 축으로 네 장: ① 1차 ② 2차 ③ 3차(금서전쟁) ④ 그 뒤.
#import "@preview/cetz:0.4.2": canvas, draw

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[제1차 계승전쟁 — 안할트가의 갈래])
    content((8.8, -0.8), name: "root", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[공통시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트·호헨아스카니아의 공통 시조]]))
    content((5.4, -2.3), name: "anh0", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 중시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[공통시조의 외아들]]))
    content((12.4, -2.3), name: "asc0", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 중시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[공통시조의 막내딸 · 이 대부터 지명상속제]]))
    content((5.4, -3.8), name: "g3", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 3대 가주] \ #text(size: 5.1pt, fill: gray.darken(40%))[아들 열아홉]]))
    content((12.4, -3.8), name: "asc", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 가문] \ #text(size: 5.1pt, fill: gray.darken(40%))[→ 2차 때 구종가측(다음 장)]]))
    content((1.7, -5.5), name: "f1", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[장남 ~ 5남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁 · 단절 †]]))
    content((4.2, -5.5), name: "f2", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[6남 ~ 12남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁 · 단절 †]]))
    content((6.9, -5.5), name: "f3", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[13 · 14 · 19남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁의 한 편]]))
    content((9.6, -5.5), name: "f4", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[15남 ~ 18남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁의 한 편]]))
    content((3.0, -7.4), name: "main", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 구종가 · 신종가] \ #text(size: 5.1pt, fill: gray.darken(40%))[13남 계보 · 하인리히의 집(구종가) → 하루의 집(신종가)]]))
    content((7.0, -7.4), name: "meissen", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센] \ #text(size: 5.1pt, fill: gray.darken(40%))[14남 계보]]))
    content((10.4, -7.4), name: "witt", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-비텐베르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[19남 계보 · 뒷날 대공가]]))
    content((13.4, -7.4), name: "f17", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[17남 계보 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[수장(여성·전과자) — 종전을 방해]]))
    content((15.9, -7.4), name: "unk", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[몇 남에서 왔는지 정하지 않는 집들] \ #text(size: 5.1pt, fill: gray.darken(40%))[모드가 · 멜가 · 호헨슈타우펜 종가·헤힝겐 분가·안토노프 분가 · (니더비텐베르크는 19남에서 또 갈라진 갈래)]]))
    content((5.6, -9.0), name: "thal", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센-탈베르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[초대 가주의 4남 → 뒷날 탈베르크 가문]]))
    content((8.8, -9.0), name: "blum", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센-블루멘탈] \ #text(size: 5.1pt, fill: gray.darken(40%))[5남 → 뒷날 블루멘탈 가문]]))
    content((1.4, -9.0), name: "arvid", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨아르비드부르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 당주의 이복남동생 → 2차의 반대편]]))
    line("root", "anh0", stroke: (paint: black, thickness: .7pt))
    lbl((7.10, -1.55), [외아들])
    line("root", "asc0", stroke: (paint: black, thickness: .7pt))
    lbl((10.60, -1.55), [막내딸])
    line("anh0", "g3", stroke: (paint: black, thickness: .7pt))
    line("asc0", "asc", stroke: (paint: black, thickness: .7pt))
    line("g3", "f1", stroke: (paint: black, thickness: .7pt))
    line("g3", "f2", stroke: (paint: black, thickness: .7pt))
    line("g3", "f3", stroke: (paint: black, thickness: .7pt))
    line("g3", "f4", stroke: (paint: black, thickness: .7pt))
    line("f3", "main", stroke: (paint: black, thickness: .7pt))
    lbl((4.95, -6.45), [13남])
    line("f3", "meissen", stroke: (paint: black, thickness: .7pt))
    lbl((6.95, -6.45), [14남])
    line("f3", "witt", stroke: (paint: black, thickness: .7pt))
    lbl((8.65, -6.45), [19남])
    line("f4", "f17", stroke: (paint: black, thickness: .7pt))
    lbl((11.50, -6.45), [17남])
    line("meissen", "thal", stroke: (paint: black, thickness: .7pt))
    lbl((6.30, -8.20), [4남])
    line("meissen", "blum", stroke: (paint: black, thickness: .7pt))
    lbl((7.90, -8.20), [5남])
    line("main", "arvid", stroke: (paint: black, thickness: .7pt))
    lbl((2.20, -8.20), [이복남동생])
    content((8.8, -0.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[공통시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트·호헨아스카니아의 공통 시조]]))
    content((5.4, -2.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 중시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[공통시조의 외아들]]))
    content((12.4, -2.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 중시조] \ #text(size: 5.1pt, fill: gray.darken(40%))[공통시조의 막내딸 · 이 대부터 지명상속제]]))
    content((5.4, -3.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 3대 가주] \ #text(size: 5.1pt, fill: gray.darken(40%))[아들 열아홉]]))
    content((12.4, -3.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 가문] \ #text(size: 5.1pt, fill: gray.darken(40%))[→ 2차 때 구종가측(다음 장)]]))
    content((1.7, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[장남 ~ 5남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁 · 단절 †]]))
    content((4.2, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[6남 ~ 12남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁 · 단절 †]]))
    content((6.9, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[13 · 14 · 19남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁의 한 편]]))
    content((9.6, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[15남 ~ 18남] \ #text(size: 5.1pt, fill: gray.darken(40%))[1차 계승전쟁의 한 편]]))
    content((3.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 구종가 · 신종가] \ #text(size: 5.1pt, fill: gray.darken(40%))[13남 계보 · 하인리히의 집(구종가) → 하루의 집(신종가)]]))
    content((7.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센] \ #text(size: 5.1pt, fill: gray.darken(40%))[14남 계보]]))
    content((10.4, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-비텐베르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[19남 계보 · 뒷날 대공가]]))
    content((13.4, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[17남 계보 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[수장(여성·전과자) — 종전을 방해]]))
    content((15.9, -7.4), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[몇 남에서 왔는지 정하지 않는 집들] \ #text(size: 5.1pt, fill: gray.darken(40%))[모드가 · 멜가 · 호헨슈타우펜 종가·헤힝겐 분가·안토노프 분가 · (니더비텐베르크는 19남에서 또 갈라진 갈래)]]))
    content((5.6, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센-탈베르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[초대 가주의 4남 → 뒷날 탈베르크 가문]]))
    content((8.8, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨마이센-블루멘탈] \ #text(size: 5.1pt, fill: gray.darken(40%))[5남 → 뒷날 블루멘탈 가문]]))
    content((1.4, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트-호헨아르비드부르크] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 당주의 이복남동생 → 2차의 반대편]]))
    line((0.4, -9.95), (1.0, -9.95), stroke: (paint: black, thickness: .7pt))
    content((1.1, -9.95), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -9.95), (3.15, -9.95), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -9.95), (3.15, -9.95), stroke: (paint: white, thickness: .8pt))
    content((3.25, -9.95), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -9.95), (5.299999999999999, -9.95), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -9.95), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -9.95), (7.449999999999999, -9.95), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -9.95), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -9.95), (9.6, -9.95), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -9.95), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -9.95), (11.75, -9.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -9.95), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -9.95), (13.9, -9.95), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -9.95), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -9.95), (16.05, -9.95), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -9.95), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ① 제1차 계승전쟁 — 안할트가의 갈래(2-2·5-6, 설정집 전용). 3대 가주의 아들 열아홉이 네 편으로 싸웠고, 장남~12남 계보는 단절되었다. 남은 갈래가 뒷날의 두 통치 가문·대공가·구종가와 신종가가 된다. 몇 남에서 왔는지 정하지 않은 집들은 오른쪽에 따로.],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    rect((0.2, -0.4), (8.6, -6.2), fill: rgb("#f4f8f5"), stroke: none)
    content((8.45, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[구종가측 — 진보 귀족·젠트리·요먼·부르주아 연합 (승전)])
    rect((9.0, -0.4), (17.6, -6.2), fill: rgb("#fdf2f0"), stroke: none)
    content((17.450000000000003, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[반대편 — 보수적 귀족의 연합])
    rect((0.2, -7.6), (17.6, -12.4), fill: rgb("#f7f7f7"), stroke: none)
    content((17.450000000000003, -7.68), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[그 뒤에 온 것])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[제2차 계승전쟁 — 두 편, 그리고 그 뒤에 온 것])
    content((3.3, -1.5), name: "issue", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[구종가 당주의 첫째 자녀] \ #text(size: 5.1pt, fill: gray.darken(40%))[승계법의 빈칸 · 그 빈칸을 채운 차별이 전쟁의 원인]]))
    content((1.6, -3.0), name: "lord", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 구종가 당주] \ #text(size: 5.1pt, fill: gray.darken(40%))[하루의 친증조할아버지]]))
    content((1.6, -4.7), name: "gf", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 친할아버지] \ #text(size: 5.1pt, fill: gray.darken(40%))[첫째 자녀의 막내동생 · 다음 가주]]))
    content((4.3, -3.0), name: "gd1", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[비텐베르크 여대공] \ #text(size: 5.1pt, fill: gray.darken(40%))[1등공신 → 대공위 · 선선대(1대)]]))
    content((7.2, -3.0), name: "asc", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 가문] \ #text(size: 5.1pt, fill: gray.darken(40%))[가문 전체 참전 · 블루멘탈 분가를 멸망 직전까지]]))
    content((4.3, -4.7), name: "maudmel", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드가 · 멜가] \ #text(size: 5.1pt, fill: gray.darken(40%))[승전 측이면서 전쟁 중 이미 궤멸에 준하는 타격]]))
    content((7.2, -4.7), name: "anton", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜-안토노프·안토노바] \ #text(size: 5.1pt, fill: gray.darken(40%))[생존]]))
    content((11.6, -1.3), name: "arvid", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아르비드부르크 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 당주의 이복남동생을 따름 · 금서를 「엮음」 · 남녀노소 전멸 †]]))
    content((11.6, -3.0), name: "stauf", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜 종가] \ #text(size: 5.1pt, fill: gray.darken(40%))[전멸 †]]))
    content((15.0, -3.0), name: "hech", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜-헤힝겐 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[세력이 줄었으나 생존]]))
    content((11.6, -4.7), name: "thal", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[막판에 탈주해 성을 갈다]]))
    content((15.0, -4.7), name: "blum", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[막판에 탈주해 성을 갈다]]))
    content((8.8, -6.9), name: "law", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[절대적 맏이상속제] \ #text(size: 5.1pt, fill: gray.darken(40%))[성별 불문 · 「고르지 못하게 하려고」 · 직후 제정]]))
    content((11.6, -8.5), name: "regT", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 정권(이쪽 구체제)] \ #text(size: 5.1pt, fill: gray.darken(40%))[뒷날 쿠데타로 집권 · 뒷날의 수반 탈베르크 발터 하랄트 6세]]))
    content((15.4, -8.5), name: "regB", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 정권(저쪽 구체제)] \ #text(size: 5.1pt, fill: gray.darken(40%))[쿠데타로 집권 · 수반 블루멘탈 요아힘 지기스문트 — 학살을 명령]]))
    content((13.5, -10.3), name: "book", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[금서 도난] \ #text(size: 5.1pt, fill: gray.darken(40%))[두 집 중 한쪽 — 정하지 않는다 → 3차의 도화선]]))
    content((7.4, -8.5), name: "massA", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 학살] \ #text(size: 5.1pt, fill: gray.darken(40%))[집권 직후의 앙갚음 · 가문 전체 †]]))
    content((4.2, -8.5), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란] \ #text(size: 5.1pt, fill: gray.darken(40%))[유일 생존자 · 순수 모계 7대 분가 · 대공국을 거쳐 이쪽으로]]))
    content((1.3, -8.5), name: "duke2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[선대 대공(2대)] \ #text(size: 5.1pt, fill: gray.darken(40%))[유골 안장 · 출생 기록 보관]]))
    content((7.4, -10.3), name: "coup", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드가 · 멜가의 역쿠데타] \ #text(size: 5.1pt, fill: gray.darken(40%))[진압 → 보복학살 · 한 가정씩 탈출]]))
    content((4.2, -10.3), name: "exile", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[망명한 두 가정] \ #text(size: 5.1pt, fill: gray.darken(40%))[이쪽에서 극심한 빈곤 · 둘만 남기고 아사 †]]))
    content((1.3, -10.3), name: "ariLaura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리 · 멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[망명 뒤 이쪽에서 출생 · 각 집의 마지막]]))
    content((8.8, -11.9), name: "trial", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[전범재판의 증언들] \ #text(size: 5.1pt, fill: gray.darken(40%))[두 학살이 세계에 드러난다 · 아리·라우라도 그때 처음 안다(다음 장)]]))
    line("issue", "lord", stroke: (paint: black, thickness: .7pt))
    line("lord", "gf", stroke: (paint: black, thickness: .7pt))
    lbl((1.60, -3.85), [막내])
    line("issue", "arvid", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((7.45, -1.40), [빼야 한다고 한 쪽])
    line("thal", "regT", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("blum", "regB", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("regB", "massA", stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((11.40, -8.50), [집권하자마자])
    line("massA", "fran", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((5.80, -8.50), [혼자 살아남는다])
    line("duke2", "fran", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    line((13.7, -9.05), (9.0, -10.3), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((11.35, -9.68), [보복학살])
    line("coup", "exile", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("exile", "ariLaura", stroke: (paint: black, thickness: .7pt))
    line((7.4, -9.05), (7.4, -9.6), (9.6, -9.6), (9.6, -11.4), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line((8.0, -10.85), (8.8, -11.4), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((3.3, -1.5), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[구종가 당주의 첫째 자녀] \ #text(size: 5.1pt, fill: gray.darken(40%))[승계법의 빈칸 · 그 빈칸을 채운 차별이 전쟁의 원인]]))
    content((1.6, -3.0), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 구종가 당주] \ #text(size: 5.1pt, fill: gray.darken(40%))[하루의 친증조할아버지]]))
    content((1.6, -4.7), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 친할아버지] \ #text(size: 5.1pt, fill: gray.darken(40%))[첫째 자녀의 막내동생 · 다음 가주]]))
    content((4.3, -3.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[비텐베르크 여대공] \ #text(size: 5.1pt, fill: gray.darken(40%))[1등공신 → 대공위 · 선선대(1대)]]))
    content((7.2, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 가문] \ #text(size: 5.1pt, fill: gray.darken(40%))[가문 전체 참전 · 블루멘탈 분가를 멸망 직전까지]]))
    content((4.3, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드가 · 멜가] \ #text(size: 5.1pt, fill: gray.darken(40%))[승전 측이면서 전쟁 중 이미 궤멸에 준하는 타격]]))
    content((7.2, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜-안토노프·안토노바] \ #text(size: 5.1pt, fill: gray.darken(40%))[생존]]))
    content((11.6, -1.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아르비드부르크 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 당주의 이복남동생을 따름 · 금서를 「엮음」 · 남녀노소 전멸 †]]))
    content((11.6, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜 종가] \ #text(size: 5.1pt, fill: gray.darken(40%))[전멸 †]]))
    content((15.0, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨슈타우펜-헤힝겐 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[세력이 줄었으나 생존]]))
    content((11.6, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[막판에 탈주해 성을 갈다]]))
    content((15.0, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 분가] \ #text(size: 5.1pt, fill: gray.darken(40%))[막판에 탈주해 성을 갈다]]))
    content((8.8, -6.9), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[절대적 맏이상속제] \ #text(size: 5.1pt, fill: gray.darken(40%))[성별 불문 · 「고르지 못하게 하려고」 · 직후 제정]]))
    content((11.6, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 정권(이쪽 구체제)] \ #text(size: 5.1pt, fill: gray.darken(40%))[뒷날 쿠데타로 집권 · 뒷날의 수반 탈베르크 발터 하랄트 6세]]))
    content((15.4, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 정권(저쪽 구체제)] \ #text(size: 5.1pt, fill: gray.darken(40%))[쿠데타로 집권 · 수반 블루멘탈 요아힘 지기스문트 — 학살을 명령]]))
    content((13.5, -10.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[금서 도난] \ #text(size: 5.1pt, fill: gray.darken(40%))[두 집 중 한쪽 — 정하지 않는다 → 3차의 도화선]]))
    content((7.4, -8.5), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[호헨아스카니아 학살] \ #text(size: 5.1pt, fill: gray.darken(40%))[집권 직후의 앙갚음 · 가문 전체 †]]))
    content((4.2, -8.5), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란] \ #text(size: 5.1pt, fill: gray.darken(40%))[유일 생존자 · 순수 모계 7대 분가 · 대공국을 거쳐 이쪽으로]]))
    content((1.3, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[선대 대공(2대)] \ #text(size: 5.1pt, fill: gray.darken(40%))[유골 안장 · 출생 기록 보관]]))
    content((7.4, -10.3), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드가 · 멜가의 역쿠데타] \ #text(size: 5.1pt, fill: gray.darken(40%))[진압 → 보복학살 · 한 가정씩 탈출]]))
    content((4.2, -10.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[망명한 두 가정] \ #text(size: 5.1pt, fill: gray.darken(40%))[이쪽에서 극심한 빈곤 · 둘만 남기고 아사 †]]))
    content((1.3, -10.3), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리 · 멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[망명 뒤 이쪽에서 출생 · 각 집의 마지막]]))
    content((8.8, -11.9), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[전범재판의 증언들] \ #text(size: 5.1pt, fill: gray.darken(40%))[두 학살이 세계에 드러난다 · 아리·라우라도 그때 처음 안다(다음 장)]]))
    line((0.4, -12.95), (1.0, -12.95), stroke: (paint: black, thickness: .7pt))
    content((1.1, -12.95), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -12.95), (3.15, -12.95), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -12.95), (3.15, -12.95), stroke: (paint: white, thickness: .8pt))
    content((3.25, -12.95), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -12.95), (5.299999999999999, -12.95), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -12.95), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -12.95), (7.449999999999999, -12.95), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -12.95), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -12.95), (9.6, -12.95), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -12.95), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -12.95), (11.75, -12.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -12.95), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -12.95), (13.9, -12.95), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -12.95), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -12.95), (16.05, -12.95), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -12.95), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ② 제2차 계승전쟁(5-6·2-2, 설정집 전용·내레이션 층). 승계법의 빈칸을 채운 차별이 원인이고, 편은 한 집안이 아니라 사회 전체에 그어졌다 — 절대적 맏이상속제를 지지한 진보적 귀족·젠트리·요먼·부르주아의 연합 대 보수적 귀족의 연합. 붉은 화살표는 그 뒤 블루멘탈 정권이 한 일(집권 직후의 학살·보복학살), 파랑은 은인. 모드가·멜가와 호헨아스카니아의 자리가 아리·라우라·프란의 출신이 된다(판본 2.2).],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    rect((0.2, -14.2), (17.6, -17.3), fill: rgb("#f4f8f5"), stroke: none)
    content((17.450000000000003, -14.28), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[「학교」])
    rect((0.2, -17.7), (17.6, -21.3), fill: rgb("#f3f3f3"), stroke: none)
    content((17.450000000000003, -17.779999999999998), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[종전의 밤과 그 앞뒤 — 기관과 이름 없는 사람들])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[제3차 계승전쟁(금서전쟁) — 그 전쟁을 산 사람들])
    content((2.4, -1.0), name: "thal6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 발터 하랄트 6세] \ #text(size: 5.1pt, fill: gray.darken(40%))[이쪽 구체제 수반]]))
    content((7.0, -1.0), name: "felix", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 로흐스 펠릭스] \ #text(size: 5.1pt, fill: gray.darken(40%))[아버지 † 그 밤 · 평토장]]))
    content((10.6, -1.0), name: "rosa", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 로자 프레데리케] \ #text(size: 5.1pt, fill: gray.darken(40%))[어머니 † 그 밤]]))
    content((15.2, -1.0), name: "sigis", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 요아힘 지기스문트] \ #text(size: 5.1pt, fill: gray.darken(40%))[저쪽 구체제 수반]]))
    content((0.9, -2.6), name: "thal_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[이쪽 수반의 부인] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 그 밤을 알고 막지 않았다]]))
    content((4.2, -2.6), name: "halfbro", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[이복형] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 아버지의 혼외자]]))
    content((13.1, -2.6), name: "ex_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[저쪽 수반의 전처] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · † 아이들 앞에서]]))
    content((16.7, -2.6), name: "new_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[저쪽 수반의 후처] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음]]))
    content((3.4, -4.4), name: "cous_thal", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(이쪽 수반의 자녀들)] \ #text(size: 5.1pt, fill: gray.darken(40%))[그 밤 부모를 고발]]))
    content((3.4, -5.9), name: "cous_half", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(이복형의 자녀들)] \ #text(size: 5.1pt, fill: gray.darken(40%))[고발]]))
    content((6.6, -4.4), name: "eiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[에이란] \ #text(size: 5.1pt, fill: gray.darken(40%))['S' · 맏이 · 금서와 함께 소멸 †]]))
    content((8.8, -4.4), name: "reiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란] \ #text(size: 5.1pt, fill: gray.darken(40%))['W' · 둘째 · 저쪽으로 · 송출]]))
    content((11.0, -4.4), name: "seiran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[리지 세이란 · 막내 · 이쪽 「학교」 · 전사 → 부활]]))
    content((13.6, -4.4), name: "cous_ex", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(전처 소생)]]))
    content((16.4, -4.4), name: "cous_new", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(후처 소생)]]))
    content((1.8, -8.2), name: "haru_par", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 아버지 · 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[신종가 가주(양위) · 원작 제8권]]))
    content((5.2, -8.2), name: "hein_par", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하인리히의 부모] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 가주 내외 · 하루의 백부모 · 극비 문서를 만들어 봉인]]))
    content((0.85, -10.0), name: "haru_sis", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 언니] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 슈타우펜 즉사]]))
    content((2.85, -10.0), name: "haru", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트 할프레드 · 「학교」 학생 → 신종가 가주]]))
    content((5.5, -10.0), name: "hein", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하인리히] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트 하인리히 카를 † · 부모를 알던 사람 · 부모의 무덤을 만들었다 · 처형]]))
    content((4.8, -11.8), name: "six", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[동생 여섯] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 문 앞 스크럼 · 안할트가 묘지]]))
    content((8.0, -11.8), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란 선생] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 교사 · 하인리히의 죽마고우 · 함구]]))
    content((8.0, -13.4), name: "frieda", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[프리다] \ #text(size: 5.1pt, fill: gray.darken(40%))[하인리히의 유복녀 — 그가 알고 인정한 아이 · 종전 21일 전 출생]]))
    content((13.8, -8.2), name: "duke3", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[현 대공(3대)] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 · 그 밤 마차 떼 · 호위 병력]]))
    content((16.6, -8.2), name: "duke2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[선대 대공(2대)] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 독살(가족과 함께)]]))
    content((13.8, -10.0), name: "police", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[국제경찰] \ #text(size: 5.1pt, fill: gray.darken(40%))[긴급국제체포영장 · 추격 · 인계]]))
    content((16.6, -10.0), name: "icc", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[국제형사재판소(가칭)] \ #text(size: 5.1pt, fill: gray.darken(40%))[영장 발부]]))
    content((1.3, -15.0), name: "omi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[오미 선생] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 교사]]))
    content((4.0, -15.0), name: "mimi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[미미] \ #text(size: 5.1pt, fill: gray.darken(40%))[카가리 미미 · 불로불사(어머니의 소생)]]))
    content((6.6, -15.0), name: "shina", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[시나] \ #text(size: 5.1pt, fill: gray.darken(40%))[토츠키 시나 · 주인공 · 미미의 짝]]))
    content((9.2, -15.0), name: "laura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[시나의 전 룸메이트 · 1화 전 전사 → 부활]]))
    content((11.8, -15.0), name: "ari", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란의 룸메이트 · 그 밤 마차에]]))
    content((14.4, -15.0), name: "esta", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타 · 헤더 · 리카] \ #text(size: 5.1pt, fill: gray.darken(40%))[셋 · 헤더는 부활자]]))
    content((16.7, -15.0), name: "senpai", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[남자 선배] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란이 구했다]]))
    content((4.0, -16.6), name: "mimi_mom", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[미미의 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 생명을 소진해 소생]]))
    content((9.2, -16.6), name: "clea", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[클레아 · 다른 여학생들 · 2화의 아이]]))
    content((2.6, -18.6), name: "relay", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[신호를 이어 준 사람들] \ #text(size: 5.1pt, fill: gray.darken(40%))[저쪽 지하 언론인들 · 세계의 언론인들 · 이름 없음 · 여럿이 † (3-6)]]))
    content((6.6, -18.6), name: "reporter", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[외신기자] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 문 밖의 보는 얼굴 · 찍어 나갔다]]))
    content((10.2, -18.6), name: "crowd", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[시위대] \ #text(size: 5.1pt, fill: gray.darken(40%))[얼굴 없음 · 거리 · 세이란에게 길을]]))
    content((13.8, -18.6), name: "employees", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 종가의 피고용인들] \ #text(size: 5.1pt, fill: gray.darken(40%))[지기스문트를 슈타우펜에서 붙잡다]]))
    content((8.4, -20.4), name: "night", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 7.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[종전의 밤 — 0년 4월 7일] \ #text(size: 5.1pt, fill: gray.darken(40%))[폭로방송 · 여섯의 화형 · 에이란의 소멸 · 세이란의 부활과 첫 만남 · 두 자매의 15번째 생일]]))
    line((8.8, -1.25), (8.8, -3.3), stroke: (paint: black, thickness: .7pt))
    line((6.6, -3.3), (11.0, -3.3), stroke: (paint: black, thickness: .7pt))
    line((6.6, -3.3), (6.6, -3.95), stroke: (paint: black, thickness: .7pt))
    line((8.8, -3.3), (8.8, -3.95), stroke: (paint: black, thickness: .7pt))
    line((11.0, -3.3), (11.0, -3.95), stroke: (paint: black, thickness: .7pt))
    lbl((8.8, -2.85), [일란성 세쌍둥이 · −15년 4/7 · 블루멘탈베르크])
    line("thal6", "felix", stroke: (paint: black, thickness: .7pt))
    lbl((4.70, -1.00), [친형제])
    line("rosa", "sigis", stroke: (paint: black, thickness: .7pt))
    lbl((12.90, -1.00), [친남매])
    line("felix", "rosa", stroke: (paint: black, thickness: 1.7pt))
    line("felix", "rosa", stroke: (paint: white, thickness: .8pt))
    line((2.4, -1.55), (2.4, -1.9), (6.4, -1.9), (6.4, -1.5), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((4.40, -1.90), [암살 명령])
    line((15.2, -1.55), (15.2, -1.9), (11.2, -1.9), (11.2, -1.5), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((13.20, -1.90), [암살 명령])
    line("thal_wife", "thal6", stroke: (paint: black, thickness: 1.7pt))
    line("thal_wife", "thal6", stroke: (paint: white, thickness: .8pt))
    line("halfbro", "thal6", stroke: (paint: black, thickness: .7pt))
    lbl((3.30, -1.80), [이복형])
    line("ex_wife", "sigis", stroke: (paint: black, thickness: 1.7pt))
    line("ex_wife", "sigis", stroke: (paint: white, thickness: .8pt))
    lbl((14.15, -1.80), [전처])
    line("new_wife", "sigis", stroke: (paint: black, thickness: 1.7pt))
    line("new_wife", "sigis", stroke: (paint: white, thickness: .8pt))
    lbl((15.95, -1.80), [후처])
    line((13.1, -2.2), (12.0, -1.3), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((12.55, -1.75), [길을 열어 줌])
    line("thal6", "cous_thal", stroke: (paint: black, thickness: .7pt))
    line("halfbro", "cous_half", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cous_ex", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cous_new", stroke: (paint: black, thickness: .7pt))
    line((6.6, -4.85), (6.6, -5.45), (8.8, -5.45), (8.8, -4.9), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((7.70, -5.45), [해제법을 주었다(2-6)])
    line("haru_par", "hein_par", stroke: (paint: black, thickness: .7pt))
    lbl((3.50, -8.20), [형제])
    line("haru_par", "haru", stroke: (paint: black, thickness: .7pt))
    line("haru_par", "haru_sis", stroke: (paint: black, thickness: .7pt))
    line("hein_par", "hein", stroke: (paint: black, thickness: .7pt))
    lbl((5.35, -9.10), [맏이])
    line((5.9, -8.65), (5.9, -11.35), stroke: (paint: black, thickness: .7pt))
    line((6.8, -10.2), (7.7, -11.3), stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((7.25, -10.75), [죽마고우 · 아이를 알고 인정했다(혼인은 없음)])
    line((6.5, -10.55), (7.0, -13.4), stroke: (paint: black, thickness: .7pt))
    lbl((6.75, -11.98), [아버지])
    line("fran", "frieda", stroke: (paint: black, thickness: .7pt))
    line((4.6, -9.45), (4.6, -7.2), (6.0, -5.3), (6.4, -4.9), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((5.30, -6.25), [그 밤 안고 뛰었다])
    line((6.8, -9.75), (8.2, -9.6), (10.6, -5.3), (10.8, -4.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((9.40, -7.45), [두 해 찾아냈다])
    line((14.6, -1.55), (14.6, -2.0), (12.4, -2.0), (12.4, -12.55), (5.6, -12.55), (5.4, -12.3), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((12.40, -7.28), [화형 명령])
    line((14.3, -1.55), (14.3, -2.15), (12.2, -2.15), (12.2, -7.5), (0.35, -7.5), (0.35, -9.6), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((12.20, -4.83), [사살])
    line((16.2, -1.55), (17.75, -2.4), (17.75, -7.0), (16.9, -7.75), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((17.75, -4.70), [독살])
    line((14.9, -1.55), (14.9, -2.3), (12.3, -2.3), (12.3, -11.0), (6.9, -11.0), (6.5, -10.55), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((12.30, -6.65), [처형(펠덴부르크)])
    line("duke3", "police", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("icc", "police", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    lbl((15.20, -10.00), [영장])
    line("mimi_mom", "mimi", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((4.00, -15.80), [소생])
    line("mimi", "shina", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((5.30, -15.00), [짝])
    line("shina", "laura", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((7.90, -15.00), [전 룸메이트])
    line((11.0, -4.85), (11.8, -14.5), stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((11.40, -9.68), [룸메이트])
    line((12.0, -4.6), (16.7, -14.5), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((14.35, -9.55), [구했다])
    line((7.6, -12.3), (1.3, -14.4), stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((4.45, -13.35), [동료 교사])
    line("relay", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("reporter", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("crowd", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("employees", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((2.4, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 발터 하랄트 6세] \ #text(size: 5.1pt, fill: gray.darken(40%))[이쪽 구체제 수반]]))
    content((7.0, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 로흐스 펠릭스] \ #text(size: 5.1pt, fill: gray.darken(40%))[아버지 † 그 밤 · 평토장]]))
    content((10.6, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 로자 프레데리케] \ #text(size: 5.1pt, fill: gray.darken(40%))[어머니 † 그 밤]]))
    content((15.2, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 요아힘 지기스문트] \ #text(size: 5.1pt, fill: gray.darken(40%))[저쪽 구체제 수반]]))
    content((0.9, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[이쪽 수반의 부인] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 그 밤을 알고 막지 않았다]]))
    content((4.2, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[이복형] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 아버지의 혼외자]]))
    content((13.1, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[저쪽 수반의 전처] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · † 아이들 앞에서]]))
    content((16.7, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[저쪽 수반의 후처] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음]]))
    content((3.4, -4.4), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(이쪽 수반의 자녀들)] \ #text(size: 5.1pt, fill: gray.darken(40%))[그 밤 부모를 고발]]))
    content((3.4, -5.9), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(이복형의 자녀들)] \ #text(size: 5.1pt, fill: gray.darken(40%))[고발]]))
    content((6.6, -4.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[에이란] \ #text(size: 5.1pt, fill: gray.darken(40%))['S' · 맏이 · 금서와 함께 소멸 †]]))
    content((8.8, -4.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란] \ #text(size: 5.1pt, fill: gray.darken(40%))['W' · 둘째 · 저쪽으로 · 송출]]))
    content((11.0, -4.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[리지 세이란 · 막내 · 이쪽 「학교」 · 전사 → 부활]]))
    content((13.6, -4.4), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(전처 소생)]]))
    content((16.4, -4.4), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[사촌들(후처 소생)]]))
    content((1.8, -8.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 아버지 · 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[신종가 가주(양위) · 원작 제8권]]))
    content((5.2, -8.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하인리히의 부모] \ #text(size: 5.1pt, fill: gray.darken(40%))[구종가 가주 내외 · 하루의 백부모 · 극비 문서를 만들어 봉인]]))
    content((0.85, -10.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 언니] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 슈타우펜 즉사]]))
    content((2.85, -10.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트 할프레드 · 「학교」 학생 → 신종가 가주]]))
    content((5.5, -10.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[하인리히] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트 하인리히 카를 † · 부모를 알던 사람 · 부모의 무덤을 만들었다 · 처형]]))
    content((4.8, -11.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[동생 여섯] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 문 앞 스크럼 · 안할트가 묘지]]))
    content((8.0, -11.8), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란 선생] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 교사 · 하인리히의 죽마고우 · 함구]]))
    content((8.0, -13.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[프리다] \ #text(size: 5.1pt, fill: gray.darken(40%))[하인리히의 유복녀 — 그가 알고 인정한 아이 · 종전 21일 전 출생]]))
    content((13.8, -8.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[현 대공(3대)] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-비텐베르크 · 그 밤 마차 떼 · 호위 병력]]))
    content((16.6, -8.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[선대 대공(2대)] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 독살(가족과 함께)]]))
    content((13.8, -10.0), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[국제경찰] \ #text(size: 5.1pt, fill: gray.darken(40%))[긴급국제체포영장 · 추격 · 인계]]))
    content((16.6, -10.0), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[국제형사재판소(가칭)] \ #text(size: 5.1pt, fill: gray.darken(40%))[영장 발부]]))
    content((1.3, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[오미 선생] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 교사]]))
    content((4.0, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[미미] \ #text(size: 5.1pt, fill: gray.darken(40%))[카가리 미미 · 불로불사(어머니의 소생)]]))
    content((6.6, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[시나] \ #text(size: 5.1pt, fill: gray.darken(40%))[토츠키 시나 · 주인공 · 미미의 짝]]))
    content((9.2, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[시나의 전 룸메이트 · 1화 전 전사 → 부활]]))
    content((11.8, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란의 룸메이트 · 그 밤 마차에]]))
    content((14.4, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타 · 헤더 · 리카] \ #text(size: 5.1pt, fill: gray.darken(40%))[셋 · 헤더는 부활자]]))
    content((16.7, -15.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[남자 선배] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란이 구했다]]))
    content((4.0, -16.6), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[미미의 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 생명을 소진해 소생]]))
    content((9.2, -16.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[클레아 · 다른 여학생들 · 2화의 아이]]))
    content((2.6, -18.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[신호를 이어 준 사람들] \ #text(size: 5.1pt, fill: gray.darken(40%))[저쪽 지하 언론인들 · 세계의 언론인들 · 이름 없음 · 여럿이 † (3-6)]]))
    content((6.6, -18.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[외신기자] \ #text(size: 5.1pt, fill: gray.darken(40%))[이름 없음 · 문 밖의 보는 얼굴 · 찍어 나갔다]]))
    content((10.2, -18.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[시위대] \ #text(size: 5.1pt, fill: gray.darken(40%))[얼굴 없음 · 거리 · 세이란에게 길을]]))
    content((13.8, -18.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 종가의 피고용인들] \ #text(size: 5.1pt, fill: gray.darken(40%))[지기스문트를 슈타우펜에서 붙잡다]]))
    content((8.4, -20.4), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 7.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[종전의 밤 — 0년 4월 7일] \ #text(size: 5.1pt, fill: gray.darken(40%))[폭로방송 · 여섯의 화형 · 에이란의 소멸 · 세이란의 부활과 첫 만남 · 두 자매의 15번째 생일]]))
    line((0.4, -21.950000000000003), (1.0, -21.950000000000003), stroke: (paint: black, thickness: .7pt))
    content((1.1, -21.950000000000003), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -21.950000000000003), (3.15, -21.950000000000003), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -21.950000000000003), (3.15, -21.950000000000003), stroke: (paint: white, thickness: .8pt))
    content((3.25, -21.950000000000003), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -21.950000000000003), (5.299999999999999, -21.950000000000003), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -21.950000000000003), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -21.950000000000003), (7.449999999999999, -21.950000000000003), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -21.950000000000003), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -21.950000000000003), (9.6, -21.950000000000003), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -21.950000000000003), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -21.950000000000003), (11.75, -21.950000000000003), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -21.950000000000003), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -21.950000000000003), (13.9, -21.950000000000003), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -21.950000000000003), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -21.950000000000003), (16.05, -21.950000000000003), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -21.950000000000003), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ③ 제3차 계승전쟁 = 금서전쟁 — 그 전쟁을 산 사람들(2-2·2-5·3-6·5-6·24절). 위: 두 집과 세 자매·사촌들. 가운데: 안할트 종가·하인리히 7형제·프란·프리다. 아래: 「학교」와, 종전의 밤에 있었던 사람들·기관. 결혼·후손·재판은 다음 장.],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    rect((0.2, -0.4), (17.6, -4.4), fill: rgb("#f7f7f7"), stroke: none)
    content((17.450000000000003, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[전범재판(+1~+3년) 과 그 뒤 — 성의 향방])
    rect((0.2, -14.0), (17.6, -16.8), fill: rgb("#f3f3f3"), stroke: none)
    content((17.450000000000003, -14.08), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[백 년 뒤(+99년)])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[금서전쟁의 뒤 — 재판·결혼·후손·백 년 뒤])
    content((1.6, -1.3), name: "judge", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[재판장] \ #text(size: 5.1pt, fill: gray.darken(40%))[군대 없는 중립국의 수장 · 대공국 출신]]))
    content((5.0, -1.3), name: "thal6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 발터 하랄트 6세] \ #text(size: 5.1pt, fill: gray.darken(40%))[종신형 · 화면에는 내레이션의 호명 한 번뿐]]))
    content((8.6, -1.3), name: "sigis", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 요아힘 지기스문트] \ #text(size: 5.1pt, fill: gray.darken(40%))[종신형 · 면회실의 유리 저쪽 · 「부디 장수하십시오」]]))
    content((12.2, -1.3), name: "spouses", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[두 수반의 배우자들] \ #text(size: 5.1pt, fill: gray.darken(40%))[재판(다른 형) · 이복형은 교수형 †]]))
    content((15.6, -1.3), name: "witness", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[증언대의 얼굴] \ #text(size: 5.1pt, fill: gray.darken(40%))[사촌들의 증언 · 대공가 사람들과 프란의 증언(두 학살) · 그날 불려 나온 사람]]))
    content((3.2, -3.2), name: "cousT", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[친가 쪽 사촌들] \ #text(size: 5.1pt, fill: gray.darken(40%))[성을 버림 → 대공국이 준 성]]))
    content((7.0, -3.2), name: "cousB", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[외가 쪽 사촌들] \ #text(size: 5.1pt, fill: gray.darken(40%))[블루멘탈베르크를 받음 · 5촌 조카(변호사, 제19.7화)]]))
    content((11.0, -3.2), name: "acting", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[대통령권한대행] \ #text(size: 5.1pt, fill: gray.darken(40%))[국장을 소박히 · 기록관 임기제]]))
    content((14.6, -3.2), name: "pres", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[남자 선배 → 대통령] \ #text(size: 5.1pt, fill: gray.darken(40%))[인권변호사 → 의원 → 대통령 · 제20화 †]]))
    content((4.4, -6.0), name: "reiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[초대 기록관장 · 평생]]))
    content((7.0, -6.0), name: "laura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[일기의 보관자 · 대통령비서실장]]))
    content((10.4, -6.0), name: "seiran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[광학 석사 · 사진작가]]))
    content((13.0, -6.0), name: "ari", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리] \ #text(size: 5.1pt, fill: gray.darken(40%))[배심 거절 · 유해 처리 자원]]))
    content((5.7, -7.9), name: "d_reiran", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란의 딸 둘 · 라우라의 딸 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[라우라 미란 · 아말리아 카란 / 안토니아 2세 · 소피아 2세]]))
    content((10.4, -7.9), name: "d_seiran", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란의 딸 셋 · 아리의 딸 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[루디 스즈란 · 프리다 펠리시아 주란 · 할프리트 마르가레테 케이란 / 레티시아 3세 · 프레시스 2세]]))
    content((14.2, -7.9), name: "adela", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[아델라 아리 아이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란의 막내딸]]))
    content((1.5, -8.6), name: "haru", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루] \ #text(size: 5.1pt, fill: gray.darken(40%))[신종가 가주 → 양위]]))
    content((1.5, -6.0), name: "haru_par", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 아버지 · 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[형 내외의 무덤을 열어 DNA로 확인]]))
    content((14.2, -10.2), name: "ferd", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 페르디난트] \ #text(size: 5.1pt, fill: gray.darken(40%))[하루의 양자 · 가주 · 제2대 기록관장(첫 임기제)]]))
    content((14.2, -12.2), name: "seven", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[페르디난트의 일곱 딸] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-블루멘탈베르크]]))
    content((4.6, -10.4), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란] \ #text(size: 5.1pt, fill: gray.darken(40%))[제19.5화의 고백 · 신종가가 가족으로 인정]]))
    content((8.0, -10.4), name: "frieda", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[프리다] \ #text(size: 5.1pt, fill: gray.darken(40%))[극비 문서로 안할트-헤힝겐 성 · 안할트-호헨아스카니아-헤힝겐-펠덴부르크]]))
    content((8.0, -12.4), name: "esta", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타] \ #text(size: 5.1pt, fill: gray.darken(40%))[출산 직후 † (+20년)]]))
    content((4.6, -12.4), name: "heather", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[헤더 · 리카] \ #text(size: 5.1pt, fill: gray.darken(40%))[다섯을 기른다 · 페르디난트도 지킨 아이]]))
    content((11.2, -12.4), name: "quint", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타의 다섯쌍둥이] \ #text(size: 5.1pt, fill: gray.darken(40%))[제21화의 노인 다섯]]))
    content((1.5, -12.4), name: "funeral", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[다섯 겹의 국장(+78년)] \ #text(size: 5.1pt, fill: gray.darken(40%))[대통령 · 세이란 · 레이란 · 라우라 · 아리]]))
    content((1.8, -15.2), name: "pres100", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[대통령(백 년 뒤)] \ #text(size: 5.1pt, fill: gray.darken(40%))[여성 · 미래편 後編]]))
    content((5.2, -15.2), name: "ferd2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[2대 기록관장 페르디난트] \ #text(size: 5.1pt, fill: gray.darken(40%))[하인리히의 유골을 파고 감식한다]]))
    content((9.0, -15.2), name: "desc", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란의 여계 후손] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 고학년 · mtDNA · 이름 없음]]))
    content((12.4, -15.2), name: "males", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[순수 남계 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[대공국 사람 · Y 염색체]]))
    content((15.6, -15.2), name: "envoy", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[사절단 · 헬기의 촬영기자] \ #text(size: 5.1pt, fill: gray.darken(40%))[後編 · 前編의 마지막 컷]]))
    line("judge", "thal6", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("judge", "sigis", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("thal6", "cousT", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cousB", stroke: (paint: black, thickness: .7pt))
    line("acting", "pres", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    lbl((12.80, -3.20), [사후 대행])
    line("reiran", "laura", stroke: (paint: black, thickness: 1.7pt))
    line("reiran", "laura", stroke: (paint: white, thickness: .8pt))
    line("seiran", "ari", stroke: (paint: black, thickness: 1.7pt))
    line("seiran", "ari", stroke: (paint: white, thickness: .8pt))
    line("laura", "d_reiran", stroke: (paint: black, thickness: .7pt))
    line("ari", "d_seiran", stroke: (paint: black, thickness: .7pt))
    line((11.4, -6.2), (14.2, -7.45), stroke: (paint: black, thickness: .7pt))
    lbl((12.80, -6.83), [막내딸])
    line("adela", "ferd", stroke: (paint: black, thickness: 1.7pt))
    line("adela", "ferd", stroke: (paint: white, thickness: .8pt))
    line("ferd", "seven", stroke: (paint: black, thickness: .7pt))
    line("haru_par", "haru", stroke: (paint: black, thickness: .7pt))
    lbl((1.50, -7.30), [양위])
    line((1.5, -9.15), (1.5, -9.55), (12.5, -9.55), (13.0, -10.0), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    lbl((7.00, -9.55), [입양 · 양위])
    line((5.2, -12.85), (5.2, -13.35), (16.5, -13.35), (16.5, -10.55), (15.75, -10.3), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    lbl((10.85, -13.35), [지킨 아이])
    line((4.4, -6.55), (3.3, -7.1), (3.3, -9.05), (12.7, -9.05), (13.6, -9.7), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    lbl((3.30, -8.07), [초대 → 2대 기록관장])
    line((2.4, -6.55), (3.4, -9.9), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((2.90, -8.22), [가족으로 인정])
    line("fran", "frieda", stroke: (paint: black, thickness: .7pt))
    line("esta", "quint", stroke: (paint: black, thickness: .7pt))
    line((5.9, -12.55), (9.9, -12.55), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    lbl((7.90, -12.55), [기른다])
    line((14.2, -10.75), (16.9, -11.6), (16.9, -13.6), (6.7, -13.6), (5.2, -14.75), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("desc", "ferd2", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((7.10, -15.20), [감식에 계통을 대다])
    line((11.2, -15.2), (10.4, -15.9), (6.7, -15.9), (6.3, -15.6), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((1.6, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[재판장] \ #text(size: 5.1pt, fill: gray.darken(40%))[군대 없는 중립국의 수장 · 대공국 출신]]))
    content((5.0, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[탈베르크 발터 하랄트 6세] \ #text(size: 5.1pt, fill: gray.darken(40%))[종신형 · 화면에는 내레이션의 호명 한 번뿐]]))
    content((8.6, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[블루멘탈 요아힘 지기스문트] \ #text(size: 5.1pt, fill: gray.darken(40%))[종신형 · 면회실의 유리 저쪽 · 「부디 장수하십시오」]]))
    content((12.2, -1.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[두 수반의 배우자들] \ #text(size: 5.1pt, fill: gray.darken(40%))[재판(다른 형) · 이복형은 교수형 †]]))
    content((15.6, -1.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[증언대의 얼굴] \ #text(size: 5.1pt, fill: gray.darken(40%))[사촌들의 증언 · 대공가 사람들과 프란의 증언(두 학살) · 그날 불려 나온 사람]]))
    content((3.2, -3.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[친가 쪽 사촌들] \ #text(size: 5.1pt, fill: gray.darken(40%))[성을 버림 → 대공국이 준 성]]))
    content((7.0, -3.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[외가 쪽 사촌들] \ #text(size: 5.1pt, fill: gray.darken(40%))[블루멘탈베르크를 받음 · 5촌 조카(변호사, 제19.7화)]]))
    content((11.0, -3.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[대통령권한대행] \ #text(size: 5.1pt, fill: gray.darken(40%))[국장을 소박히 · 기록관 임기제]]))
    content((14.6, -3.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[남자 선배 → 대통령] \ #text(size: 5.1pt, fill: gray.darken(40%))[인권변호사 → 의원 → 대통령 · 제20화 †]]))
    content((4.4, -6.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[초대 기록관장 · 평생]]))
    content((7.0, -6.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[멜 라우라] \ #text(size: 5.1pt, fill: gray.darken(40%))[일기의 보관자 · 대통령비서실장]]))
    content((10.4, -6.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[광학 석사 · 사진작가]]))
    content((13.0, -6.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[모드 아리] \ #text(size: 5.1pt, fill: gray.darken(40%))[배심 거절 · 유해 처리 자원]]))
    content((5.7, -7.9), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[레이란의 딸 둘 · 라우라의 딸 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[라우라 미란 · 아말리아 카란 / 안토니아 2세 · 소피아 2세]]))
    content((10.4, -7.9), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란의 딸 셋 · 아리의 딸 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[루디 스즈란 · 프리다 펠리시아 주란 · 할프리트 마르가레테 케이란 / 레티시아 3세 · 프레시스 2세]]))
    content((14.2, -7.9), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[아델라 아리 아이란] \ #text(size: 5.1pt, fill: gray.darken(40%))[세이란의 막내딸]]))
    content((1.5, -8.6), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루] \ #text(size: 5.1pt, fill: gray.darken(40%))[신종가 가주 → 양위]]))
    content((1.5, -6.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[하루의 아버지 · 어머니] \ #text(size: 5.1pt, fill: gray.darken(40%))[형 내외의 무덤을 열어 DNA로 확인]]))
    content((14.2, -10.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[안할트 페르디난트] \ #text(size: 5.1pt, fill: gray.darken(40%))[하루의 양자 · 가주 · 제2대 기록관장(첫 임기제)]]))
    content((14.2, -12.2), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[페르디난트의 일곱 딸] \ #text(size: 5.1pt, fill: gray.darken(40%))[안할트-블루멘탈베르크]]))
    content((4.6, -10.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[프란] \ #text(size: 5.1pt, fill: gray.darken(40%))[제19.5화의 고백 · 신종가가 가족으로 인정]]))
    content((8.0, -10.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[프리다] \ #text(size: 5.1pt, fill: gray.darken(40%))[극비 문서로 안할트-헤힝겐 성 · 안할트-호헨아스카니아-헤힝겐-펠덴부르크]]))
    content((8.0, -12.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타] \ #text(size: 5.1pt, fill: gray.darken(40%))[출산 직후 † (+20년)]]))
    content((4.6, -12.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[헤더 · 리카] \ #text(size: 5.1pt, fill: gray.darken(40%))[다섯을 기른다 · 페르디난트도 지킨 아이]]))
    content((11.2, -12.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[에스타의 다섯쌍둥이] \ #text(size: 5.1pt, fill: gray.darken(40%))[제21화의 노인 다섯]]))
    content((1.5, -12.4), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[다섯 겹의 국장(+78년)] \ #text(size: 5.1pt, fill: gray.darken(40%))[대통령 · 세이란 · 레이란 · 라우라 · 아리]]))
    content((1.8, -15.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[대통령(백 년 뒤)] \ #text(size: 5.1pt, fill: gray.darken(40%))[여성 · 미래편 後編]]))
    content((5.2, -15.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[2대 기록관장 페르디난트] \ #text(size: 5.1pt, fill: gray.darken(40%))[하인리히의 유골을 파고 감식한다]]))
    content((9.0, -15.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[세이란의 여계 후손] \ #text(size: 5.1pt, fill: gray.darken(40%))[「학교」 고학년 · mtDNA · 이름 없음]]))
    content((12.4, -15.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[순수 남계 둘] \ #text(size: 5.1pt, fill: gray.darken(40%))[대공국 사람 · Y 염색체]]))
    content((15.6, -15.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[사절단 · 헬기의 촬영기자] \ #text(size: 5.1pt, fill: gray.darken(40%))[後編 · 前編의 마지막 컷]]))
    line((0.4, -17.35), (1.0, -17.35), stroke: (paint: black, thickness: .7pt))
    content((1.1, -17.35), anchor: "west", text(size: 5.8pt)[혈연])
    line((2.55, -17.35), (3.15, -17.35), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -17.35), (3.15, -17.35), stroke: (paint: white, thickness: .8pt))
    content((3.25, -17.35), anchor: "west", text(size: 5.8pt)[혼인])
    line((4.699999999999999, -17.35), (5.299999999999999, -17.35), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -17.35), anchor: "west", text(size: 5.8pt)[양자·기른 사람])
    line((6.85, -17.35), (7.449999999999999, -17.35), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -17.35), anchor: "west", text(size: 5.8pt)[사제·동급])
    line((9.0, -17.35), (9.6, -17.35), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -17.35), anchor: "west", text(size: 5.8pt)[직무])
    line((11.15, -17.35), (11.75, -17.35), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -17.35), anchor: "west", text(size: 5.8pt)[은인])
    line((13.3, -17.35), (13.9, -17.35), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -17.35), anchor: "west", text(size: 5.8pt)[죽임])
    line((15.450000000000001, -17.35), (16.05, -17.35), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -17.35), anchor: "west", text(size: 5.8pt)[→ 그 뒤])
  }),
  caption: [인물관계도 ④ 금서전쟁의 뒤(2-2·5-2·2-12·제19.5화·종장·백 년 뒤의 미래편). 위: 재판과 성의 향방. 가운데: 두 부부와 딸들(점선 = 설정집 전용), 페르디난트와 일곱 딸, 프란·프리다에게 온 것. 아래: 다섯 겹의 국장, 백 년 뒤. 이중선 = 혼인, 일점쇄선 = 양자·기른 사람, 점선 = 직무.],
  supplement: none,
  numbering: none,
)
