// 인물관계도 v2.7.4 — 생성물. tools/relations_diagram_gen.py 가 만든다(KO/JA 록스텝). 손으로 고치지 않는다.
// 일곱 장 — ① 1차 계승전쟁 ② 2차 ③ 금서전쟁: 권력의 집과 세 자매 ④ 곁에 있던 사람들
// ⑤ 「학교」와 그날 ⑥ 전쟁의 뒤: 재판과 성의 향방 ⑦ 관계와 아이들, 그리고 먼 뒤(유향 하이퍼엣지).
#import "@preview/cetz:0.4.2": canvas, draw

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[第一次継承戦争 ―― アンハルト家の枝])
    content((8.8, -0.8), name: "root", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[共通始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ホーエンアスカニアの共通始祖]]))
    content((5.4, -2.3), name: "anh0", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト中始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[共通始祖の一人息子]]))
    content((12.4, -2.3), name: "asc0", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア中始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[共通始祖の末娘 · この代から指名相続]]))
    content((5.4, -3.8), name: "g3", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト三代当主] \ #text(size: 5.1pt, fill: gray.darken(40%))[十九人の息子]]))
    content((12.4, -3.8), name: "asc", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア家門] \ #text(size: 5.1pt, fill: gray.darken(40%))[→ 第二次は旧宗家側（次の図）]]))
    content((1.7, -5.5), name: "f1", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[長男〜五男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争 · 断絶 †]]))
    content((4.2, -5.5), name: "f2", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[六男〜十二男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争 · 断絶 †]]))
    content((6.9, -5.5), name: "f3", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[十三・十四・十九男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争の一方]]))
    content((9.6, -5.5), name: "f4", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[十五男〜十八男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争の一方]]))
    content((3.0, -7.4), name: "main", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト旧宗家・新宗家] \ #text(size: 5.1pt, fill: gray.darken(40%))[十三男の系譜 · ハインリヒの家（旧宗家）→ ハルの家（新宗家）]]))
    content((7.0, -7.4), name: "meissen", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン] \ #text(size: 5.1pt, fill: gray.darken(40%))[十四男の系譜 · 当主直系など残りは第二次で断絶 †]]))
    content((10.4, -7.4), name: "witt", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ヴィッテンベルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[十九男の系譜 · のちの大公家]]))
    content((13.0, -7.4), name: "f17", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[十七男系譜の分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[訴訟で破産 · 名を受け取れなかった側 · 長（女性・前科者）―― 終戦を妨げる]]))
    content((16.15, -7.4), name: "unk", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[何男から出たか定めない家々] \ #text(size: 5.1pt, fill: gray.darken(40%))[ホーエンシュタウフェン宗家 · ヘヒンゲン分家 · アントノフ・アントノヴァ分家など]]))
    content((5.6, -9.0), name: "thal", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン＝タールベルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[初代当主の四男 → のちのタールベルク家 · 父方の従兄弟たち（→アンハルト＝ニーダーヴィッテンベルク）の起源]]))
    content((8.8, -9.0), name: "blum", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン＝ブルーメンタール] \ #text(size: 5.1pt, fill: gray.darken(40%))[五男 → のちのブルーメンタール家 · 三姉妹・母方の従姉妹たち（→ブルーメンタールベルク）の起源]]))
    content((1.4, -9.0), name: "arvid", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンアルヴィートブルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主の異母弟 → 第二次の反対側]]))
    line("root", "anh0", stroke: (paint: black, thickness: .7pt))
    lbl((7.10, -1.55), [一人息子])
    line("root", "asc0", stroke: (paint: black, thickness: .7pt))
    lbl((10.60, -1.55), [末娘])
    line("anh0", "g3", stroke: (paint: black, thickness: .7pt))
    line("asc0", "asc", stroke: (paint: black, thickness: .7pt))
    line("g3", "f1", stroke: (paint: black, thickness: .7pt))
    line("g3", "f2", stroke: (paint: black, thickness: .7pt))
    line("g3", "f3", stroke: (paint: black, thickness: .7pt))
    line("g3", "f4", stroke: (paint: black, thickness: .7pt))
    line("f3", "main", stroke: (paint: black, thickness: .7pt))
    lbl((4.95, -6.45), [十三男])
    line("f3", "meissen", stroke: (paint: black, thickness: .7pt))
    lbl((6.95, -6.45), [十四男])
    line("f3", "witt", stroke: (paint: black, thickness: .7pt))
    lbl((8.65, -6.45), [十九男])
    line("f4", "f17", stroke: (paint: black, thickness: .7pt))
    lbl((11.30, -6.45), [十七男])
    line("meissen", "thal", stroke: (paint: black, thickness: .7pt))
    lbl((6.30, -8.20), [四男])
    line("meissen", "blum", stroke: (paint: black, thickness: .7pt))
    lbl((7.90, -8.20), [五男])
    line("main", "arvid", stroke: (paint: black, thickness: .7pt))
    lbl((2.20, -8.20), [異母弟])
    content((8.8, -0.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[共通始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ホーエンアスカニアの共通始祖]]))
    content((5.4, -2.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト中始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[共通始祖の一人息子]]))
    content((12.4, -2.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア中始祖] \ #text(size: 5.1pt, fill: gray.darken(40%))[共通始祖の末娘 · この代から指名相続]]))
    content((5.4, -3.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト三代当主] \ #text(size: 5.1pt, fill: gray.darken(40%))[十九人の息子]]))
    content((12.4, -3.8), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア家門] \ #text(size: 5.1pt, fill: gray.darken(40%))[→ 第二次は旧宗家側（次の図）]]))
    content((1.7, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[長男〜五男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争 · 断絶 †]]))
    content((4.2, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[六男〜十二男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争 · 断絶 †]]))
    content((6.9, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[十三・十四・十九男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争の一方]]))
    content((9.6, -5.5), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[十五男〜十八男] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一次継承戦争の一方]]))
    content((3.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト旧宗家・新宗家] \ #text(size: 5.1pt, fill: gray.darken(40%))[十三男の系譜 · ハインリヒの家（旧宗家）→ ハルの家（新宗家）]]))
    content((7.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン] \ #text(size: 5.1pt, fill: gray.darken(40%))[十四男の系譜 · 当主直系など残りは第二次で断絶 †]]))
    content((10.4, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ヴィッテンベルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[十九男の系譜 · のちの大公家]]))
    content((13.0, -7.4), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[十七男系譜の分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[訴訟で破産 · 名を受け取れなかった側 · 長（女性・前科者）―― 終戦を妨げる]]))
    content((16.15, -7.4), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[何男から出たか定めない家々] \ #text(size: 5.1pt, fill: gray.darken(40%))[ホーエンシュタウフェン宗家 · ヘヒンゲン分家 · アントノフ・アントノヴァ分家など]]))
    content((5.6, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン＝タールベルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[初代当主の四男 → のちのタールベルク家 · 父方の従兄弟たち（→アンハルト＝ニーダーヴィッテンベルク）の起源]]))
    content((8.8, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンマイセン＝ブルーメンタール] \ #text(size: 5.1pt, fill: gray.darken(40%))[五男 → のちのブルーメンタール家 · 三姉妹・母方の従姉妹たち（→ブルーメンタールベルク）の起源]]))
    content((1.4, -9.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト＝ホーエンアルヴィートブルク] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主の異母弟 → 第二次の反対側]]))
    line((0.4, -9.95), (1.0, -9.95), stroke: (paint: black, thickness: .7pt))
    content((1.1, -9.95), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -9.95), (3.15, -9.95), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -9.95), (3.15, -9.95), stroke: (paint: white, thickness: .8pt))
    content((3.25, -9.95), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -9.95), (5.299999999999999, -9.95), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -9.95), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -9.95), (7.449999999999999, -9.95), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -9.95), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -9.95), (9.6, -9.95), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -9.95), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -9.95), (11.75, -9.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -9.95), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -9.95), (13.9, -9.95), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -9.95), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -9.95), (16.05, -9.95), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -9.95), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図① 第一次継承戦争 ―― アンハルト家の枝（2-2・3-6、設定集専用）。三代当主の十九人の息子が四つの側で戦い、長男〜十二男の系譜は断絶した。残った枝がのちの二つの統治家（十四男アンハルト＝ホーエンマイセン系譜）・大公家（十九男）・旧宗家と新宗家（十三男）になる。何男から出たか定めない貴族の家々は右に別に（モード家・メル家は貴族ではなくジェントリの家柄 ―― ②の図参照）。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    rect((0.2, -0.4), (8.6, -6.2), fill: rgb("#f4f8f5"), stroke: none)
    content((8.45, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[旧宗家側 ―― 進歩貴族・ジェントリ・ヨーマン・ブルジョワ連合（戦勝）])
    rect((9.0, -0.4), (17.6, -6.2), fill: rgb("#fdf2f0"), stroke: none)
    content((17.450000000000003, -0.48000000000000004), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[反対側 ―― 保守的貴族の連合])
    rect((0.2, -7.6), (17.6, -12.4), fill: rgb("#f7f7f7"), stroke: none)
    content((17.450000000000003, -7.68), anchor: "north-east", text(size: 6pt, fill: gray.darken(30%))[そのあとに来たもの])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[第二次継承戦争 ―― 二つの側、そしてそのあとに来たもの])
    content((3.3, -1.5), name: "issue", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[旧宗家当主の第一子] \ #text(size: 5.1pt, fill: gray.darken(40%))[継承法の空白 · その空白を埋めた差別が戦争の原因 · のちに当主となり天寿を全うし、子がない]]))
    content((1.6, -3.0), name: "lord", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト旧宗家当主] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハルの曾祖父]]))
    content((1.6, -4.7), name: "gf", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの祖父] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一子の末弟 · 次の当主]]))
    content((4.3, -3.0), name: "gd1", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[初代女大公ナターシャ一世] \ #text(size: 5.1pt, fill: gray.darken(40%))[一等功臣 → 大公位 · 初代国婿オレクサ一世（漁師出身、妻の姓を下賜）]]))
    content((7.2, -3.0), name: "asc", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア家門] \ #text(size: 5.1pt, fill: gray.darken(40%))[家門全体が参戦 · ブルーメンタール分家を全滅寸前まで]]))
    content((4.3, -4.7), name: "maudmel", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード家・メル家（ジェントリ）] \ #text(size: 5.1pt, fill: gray.darken(40%))[貴族と血縁・姻戚なし · 戦勝側でありながら戦中壊滅に準ずる打撃]]))
    content((7.2, -4.7), name: "anton", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン＝アントノフ・アントノヴァ] \ #text(size: 5.1pt, fill: gray.darken(40%))[生存]]))
    content((11.6, -1.3), name: "arvid", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアルヴィートブルク分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主の異母弟に従う · 禁書を「編む」· 老若男女全滅 †]]))
    content((11.6, -3.0), name: "stauf", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン宗家] \ #text(size: 5.1pt, fill: gray.darken(40%))[全滅 †]]))
    content((15.0, -3.0), name: "hech", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン＝ヘヒンゲン分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[勢力を減らしつつ生存]]))
    content((11.6, -4.7), name: "thal", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[土壇場に逃れて姓を替える]]))
    content((15.0, -4.7), name: "blum", frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[土壇場に逃れて姓を替える]]))
    content((8.8, -6.9), name: "law", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[絶対的長子相続] \ #text(size: 5.1pt, fill: gray.darken(40%))[性別を問わず · 「選べないように」· 直後に制定]]))
    content((11.6, -8.5), name: "regT", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク政権（こちらの旧体制）] \ #text(size: 5.1pt, fill: gray.darken(40%))[のちにクーデターで政権 · のちの首班タールベルク・ヴァルター・ハラルト六世]]))
    content((15.4, -8.5), name: "regB", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール政権（向こうの旧体制）] \ #text(size: 5.1pt, fill: gray.darken(40%))[クーデターで政権 · 首班ブルーメンタール・ヨアヒム・ジギスムント ―― 虐殺を命じる]]))
    content((13.5, -10.3), name: "book", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[禁書の盗難] \ #text(size: 5.1pt, fill: gray.darken(40%))[二つの家のうち一方 ―― 定めない → 第三次の導火線]]))
    content((7.4, -8.5), name: "massA", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア虐殺] \ #text(size: 5.1pt, fill: gray.darken(40%))[政権直後の仕返し · 家門全体 †]]))
    content((4.2, -8.5), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[唯一の生存者 · 母エミリア · マサコが逃走を助ける · 大公国を経てこちらへ]]))
    content((1.3, -8.5), name: "duke2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[先代大公（第二代）オレクサ二世] \ #text(size: 5.1pt, fill: gray.darken(40%))[遺骨を葬り · 出生記録を保管]]))
    content((7.4, -10.3), name: "coup", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード家・メル家の逆クーデター] \ #text(size: 5.1pt, fill: gray.darken(40%))[鎮圧 → 報復の虐殺 · 一家族ずつ脱出]]))
    content((4.2, -10.3), name: "exile", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[亡命した二つの家族] \ #text(size: 5.1pt, fill: gray.darken(40%))[こちらで極度の貧困 · 二人を残して餓死 †]]))
    content((1.3, -10.3), name: "ariLaura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ · メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[ジェントリ二家の最後 · アリ・ラウラ以外は貴族と血縁・姻戚皆無]]))
    content((8.8, -11.9), name: "trial", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[戦犯裁判の証言] \ #text(size: 5.1pt, fill: gray.darken(40%))[二つの虐殺が世界に明らかになる · アリ・ラウラもそのとき初めて知る（次の図）]]))
    line("issue", "lord", stroke: (paint: black, thickness: .7pt))
    line("lord", "gf", stroke: (paint: black, thickness: .7pt))
    lbl((1.60, -3.85), [末弟])
    line("issue", "arvid", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((7.45, -1.40), [外すべきだとした側])
    line("thal", "regT", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("blum", "regB", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("regB", "massA", stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((11.40, -8.50), [政権を握るや否や])
    line("massA", "fran", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((5.80, -8.50), [一人だけ生き残る])
    line("duke2", "fran", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    line((13.7, -9.05), (9.0, -10.3), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((11.35, -9.68), [報復の虐殺])
    line("coup", "exile", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("exile", "ariLaura", stroke: (paint: black, thickness: .7pt))
    line((7.4, -9.05), (7.4, -9.6), (9.6, -9.6), (9.6, -11.4), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line((8.0, -10.85), (8.8, -11.4), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((3.3, -1.5), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[旧宗家当主の第一子] \ #text(size: 5.1pt, fill: gray.darken(40%))[継承法の空白 · その空白を埋めた差別が戦争の原因 · のちに当主となり天寿を全うし、子がない]]))
    content((1.6, -3.0), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト旧宗家当主] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハルの曾祖父]]))
    content((1.6, -4.7), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの祖父] \ #text(size: 5.1pt, fill: gray.darken(40%))[第一子の末弟 · 次の当主]]))
    content((4.3, -3.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[初代女大公ナターシャ一世] \ #text(size: 5.1pt, fill: gray.darken(40%))[一等功臣 → 大公位 · 初代国婿オレクサ一世（漁師出身、妻の姓を下賜）]]))
    content((7.2, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア家門] \ #text(size: 5.1pt, fill: gray.darken(40%))[家門全体が参戦 · ブルーメンタール分家を全滅寸前まで]]))
    content((4.3, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード家・メル家（ジェントリ）] \ #text(size: 5.1pt, fill: gray.darken(40%))[貴族と血縁・姻戚なし · 戦勝側でありながら戦中壊滅に準ずる打撃]]))
    content((7.2, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン＝アントノフ・アントノヴァ] \ #text(size: 5.1pt, fill: gray.darken(40%))[生存]]))
    content((11.6, -1.3), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアルヴィートブルク分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主の異母弟に従う · 禁書を「編む」· 老若男女全滅 †]]))
    content((11.6, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン宗家] \ #text(size: 5.1pt, fill: gray.darken(40%))[全滅 †]]))
    content((15.0, -3.0), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンシュタウフェン＝ヘヒンゲン分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[勢力を減らしつつ生存]]))
    content((11.6, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[土壇場に逃れて姓を替える]]))
    content((15.0, -4.7), frame: "rect", fill: rgb("#fff3d6"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール分家] \ #text(size: 5.1pt, fill: gray.darken(40%))[土壇場に逃れて姓を替える]]))
    content((8.8, -6.9), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[絶対的長子相続] \ #text(size: 5.1pt, fill: gray.darken(40%))[性別を問わず · 「選べないように」· 直後に制定]]))
    content((11.6, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク政権（こちらの旧体制）] \ #text(size: 5.1pt, fill: gray.darken(40%))[のちにクーデターで政権 · のちの首班タールベルク・ヴァルター・ハラルト六世]]))
    content((15.4, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール政権（向こうの旧体制）] \ #text(size: 5.1pt, fill: gray.darken(40%))[クーデターで政権 · 首班ブルーメンタール・ヨアヒム・ジギスムント ―― 虐殺を命じる]]))
    content((13.5, -10.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[禁書の盗難] \ #text(size: 5.1pt, fill: gray.darken(40%))[二つの家のうち一方 ―― 定めない → 第三次の導火線]]))
    content((7.4, -8.5), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[ホーエンアスカニア虐殺] \ #text(size: 5.1pt, fill: gray.darken(40%))[政権直後の仕返し · 家門全体 †]]))
    content((4.2, -8.5), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[唯一の生存者 · 母エミリア · マサコが逃走を助ける · 大公国を経てこちらへ]]))
    content((1.3, -8.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[先代大公（第二代）オレクサ二世] \ #text(size: 5.1pt, fill: gray.darken(40%))[遺骨を葬り · 出生記録を保管]]))
    content((7.4, -10.3), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード家・メル家の逆クーデター] \ #text(size: 5.1pt, fill: gray.darken(40%))[鎮圧 → 報復の虐殺 · 一家族ずつ脱出]]))
    content((4.2, -10.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[亡命した二つの家族] \ #text(size: 5.1pt, fill: gray.darken(40%))[こちらで極度の貧困 · 二人を残して餓死 †]]))
    content((1.3, -10.3), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ · メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[ジェントリ二家の最後 · アリ・ラウラ以外は貴族と血縁・姻戚皆無]]))
    content((8.8, -11.9), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[戦犯裁判の証言] \ #text(size: 5.1pt, fill: gray.darken(40%))[二つの虐殺が世界に明らかになる · アリ・ラウラもそのとき初めて知る（次の図）]]))
    line((0.4, -12.95), (1.0, -12.95), stroke: (paint: black, thickness: .7pt))
    content((1.1, -12.95), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -12.95), (3.15, -12.95), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -12.95), (3.15, -12.95), stroke: (paint: white, thickness: .8pt))
    content((3.25, -12.95), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -12.95), (5.299999999999999, -12.95), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -12.95), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -12.95), (7.449999999999999, -12.95), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -12.95), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -12.95), (9.6, -12.95), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -12.95), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -12.95), (11.75, -12.95), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -12.95), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -12.95), (13.9, -12.95), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -12.95), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -12.95), (16.05, -12.95), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -12.95), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図② 第二次継承戦争（3-6・2-2、設定集専用・ナレーション層）。継承法の空白を埋めた差別が原因であり、側は一家ではなく社会全体に引かれた ―― 絶対的長子相続を支持した進歩的貴族・ジェントリ・ヨーマン・ブルジョワの連合 対 保守的貴族の連合。赤の矢印はそのあとブルーメンタール政権がしたこと（政権直後の虐殺・報復の虐殺）、青は恩人。モード家・メル家（貴族と血縁・姻戚関係が一切なかったジェントリの家柄）とホーエンアスカニアの位置がアリ・ラウラ・フランの出自になる（版2.2・2.7.1）。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[禁書戦争 ―― 権力の家と三姉妹])
    content((2.4, -1.0), name: "thal6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ヴァルター・ハラルト六世] \ #text(size: 5.1pt, fill: gray.darken(40%))[こちらの旧体制の首班]]))
    content((7.0, -1.0), name: "felix", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ロフス・フェリクス] \ #text(size: 5.1pt, fill: gray.darken(40%))[父 † あの夜 · 平土葬]]))
    content((10.6, -1.0), name: "rosa", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ローザ・フリーデリケ] \ #text(size: 5.1pt, fill: gray.darken(40%))[母 † あの夜]]))
    content((15.2, -1.0), name: "sigis", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ヨアヒム・ジギスムント] \ #text(size: 5.1pt, fill: gray.darken(40%))[向こうの旧体制の首班]]))
    content((0.9, -2.6), name: "thal_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[こちらの首班の妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · あの夜を知り止めなかった]]))
    content((4.2, -2.6), name: "halfbro", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[異母兄] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · 父の婚外子 · 権力の深部で人道に対する罪 · 死刑 → 絞首刑 †]]))
    content((13.1, -3.05), name: "ex_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[向こうの首班の前妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · † 子どもたちの前で · ローザに道を開いた]]))
    content((16.7, -3.05), name: "new_wife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[向こうの首班の後妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし]]))
    content((3.4, -4.4), name: "cous_thal", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[従兄弟たち（こちらの首班の子）] \ #text(size: 5.1pt, fill: gray.darken(40%))[あの夜、両親を告発]]))
    content((3.4, -5.9), name: "cous_half", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[従兄弟たち（異母兄の子）] \ #text(size: 5.1pt, fill: gray.darken(40%))[告発]]))
    content((6.6, -4.4), name: "eiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[エイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[「S」 · 長女 · 禁書とともに消滅 †]]))
    content((8.8, -4.4), name: "reiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[「W」 · 次女 · 向こうへ · 送出]]))
    content((11.5, -4.4), name: "seiran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[リジ・セイラン · 末娘 · こちらの「学校」· 戦死 → 復活]]))
    content((13.9, -5.9), name: "cous_ex", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[従姉妹たち（前妻の子）]]))
    content((16.5, -5.9), name: "cous_new", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[従姉妹たち（後妻の子）]]))
    line((8.8, -1.25), (8.8, -3.3), stroke: (paint: black, thickness: .7pt))
    line((6.6, -3.3), (11.5, -3.3), stroke: (paint: black, thickness: .7pt))
    line((6.6, -3.3), (6.6, -3.95), stroke: (paint: black, thickness: .7pt))
    line((8.8, -3.3), (8.8, -3.95), stroke: (paint: black, thickness: .7pt))
    line((11.5, -3.3), (11.5, -3.95), stroke: (paint: black, thickness: .7pt))
    lbl((8.8, -2.85), [一卵性の三つ子 · −15年 4/7 · ブルーメンタールベルク])
    line("thal6", "felix", stroke: (paint: black, thickness: .7pt))
    lbl((4.70, -1.00), [実の兄弟])
    line("rosa", "sigis", stroke: (paint: black, thickness: .7pt))
    lbl((12.90, -1.00), [実の兄妹])
    line("felix", "rosa", stroke: (paint: black, thickness: 1.7pt))
    line("felix", "rosa", stroke: (paint: white, thickness: .8pt))
    line((2.4, -1.55), (2.4, -1.9), (6.4, -1.9), (6.4, -1.5), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((4.40, -1.90), [暗殺の命令])
    line((15.2, -1.55), (15.2, -1.9), (11.2, -1.9), (11.2, -1.5), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    lbl((13.20, -1.90), [暗殺の命令])
    line("thal_wife", "thal6", stroke: (paint: black, thickness: 1.7pt))
    line("thal_wife", "thal6", stroke: (paint: white, thickness: .8pt))
    line("halfbro", "thal6", stroke: (paint: black, thickness: .7pt))
    lbl((3.30, -1.80), [異母兄])
    line("ex_wife", "sigis", stroke: (paint: black, thickness: 1.7pt))
    line("ex_wife", "sigis", stroke: (paint: white, thickness: .8pt))
    lbl((14.15, -2.02), [前妻])
    line("new_wife", "sigis", stroke: (paint: black, thickness: 1.7pt))
    line("new_wife", "sigis", stroke: (paint: white, thickness: .8pt))
    lbl((15.95, -2.02), [後妻])
    line("ex_wife", "rosa", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    line("thal6", "cous_thal", stroke: (paint: black, thickness: .7pt))
    line("halfbro", "cous_half", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cous_ex", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cous_new", stroke: (paint: black, thickness: .7pt))
    line((6.6, -4.85), (6.6, -5.45), (8.8, -5.45), (8.8, -4.9), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((7.70, -5.45), [解除法を与えた（2-6）])
    content((2.4, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ヴァルター・ハラルト六世] \ #text(size: 5.1pt, fill: gray.darken(40%))[こちらの旧体制の首班]]))
    content((7.0, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ロフス・フェリクス] \ #text(size: 5.1pt, fill: gray.darken(40%))[父 † あの夜 · 平土葬]]))
    content((10.6, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ローザ・フリーデリケ] \ #text(size: 5.1pt, fill: gray.darken(40%))[母 † あの夜]]))
    content((15.2, -1.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ヨアヒム・ジギスムント] \ #text(size: 5.1pt, fill: gray.darken(40%))[向こうの旧体制の首班]]))
    content((0.9, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[こちらの首班の妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · あの夜を知り止めなかった]]))
    content((4.2, -2.6), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[異母兄] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · 父の婚外子 · 権力の深部で人道に対する罪 · 死刑 → 絞首刑 †]]))
    content((13.1, -3.05), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[向こうの首班の前妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · † 子どもたちの前で · ローザに道を開いた]]))
    content((16.7, -3.05), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 1.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[向こうの首班の後妻] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし]]))
    content((3.4, -4.4), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[従兄弟たち（こちらの首班の子）] \ #text(size: 5.1pt, fill: gray.darken(40%))[あの夜、両親を告発]]))
    content((3.4, -5.9), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[従兄弟たち（異母兄の子）] \ #text(size: 5.1pt, fill: gray.darken(40%))[告発]]))
    content((6.6, -4.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[エイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[「S」 · 長女 · 禁書とともに消滅 †]]))
    content((8.8, -4.4), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[「W」 · 次女 · 向こうへ · 送出]]))
    content((11.5, -4.4), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[リジ・セイラン · 末娘 · こちらの「学校」· 戦死 → 復活]]))
    content((13.9, -5.9), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[従姉妹たち（前妻の子）]]))
    content((16.5, -5.9), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[従姉妹たち（後妻の子）]]))
    line((0.4, -7.75), (1.0, -7.75), stroke: (paint: black, thickness: .7pt))
    content((1.1, -7.75), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -7.75), (3.15, -7.75), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -7.75), (3.15, -7.75), stroke: (paint: white, thickness: .8pt))
    content((3.25, -7.75), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -7.75), (5.299999999999999, -7.75), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -7.75), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -7.75), (7.449999999999999, -7.75), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -7.75), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -7.75), (9.6, -7.75), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -7.75), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -7.75), (11.75, -7.75), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -7.75), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -7.75), (13.9, -7.75), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -7.75), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -7.75), (16.05, -7.75), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -7.75), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図③ 第三次継承戦争（禁書戦争）―― 権力の家と三姉妹（2-2・2-5）。二人の首班は兄弟であり、三姉妹の両親はその間から出る。三姉妹がどこへ行ったかは⑤にある。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[禁書戦争 ―― かたわらにいた人たち])
    content((1.8, -1.2), name: "haru_par", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの父 · 母] \ #text(size: 5.1pt, fill: gray.darken(40%))[新宗家当主（譲位）· 原作第8巻]]))
    content((5.2, -1.2), name: "hein_par", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハインリヒの父母] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主夫妻 · ハルの伯父伯母 · 極秘文書を作り封印]]))
    content((0.85, -3.0), name: "haru_sis", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの姉] \ #text(size: 5.1pt, fill: gray.darken(40%))[† シュタウフェンで即死]]))
    content((2.85, -3.0), name: "haru", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハル] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ハルフレズ · 「学校」の学生 → 新宗家当主]]))
    content((7.4, -3.0), name: "hein", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハインリヒ] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ハインリヒ・カール † · 両親を知っていた人 · 両親の墓を作った · 処刑]]))
    content((4.5, -4.8), name: "six", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[弟たち六人] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 扉の前のスクラム · アンハルト家墓地]]))
    content((10.4, -4.8), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン先生] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」の教師 · ハインリヒの幼馴染 · 沈黙]]))
    content((7.8, -6.5), name: "frieda", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[フリーダ] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハインリヒの遺腹の娘 ―― 彼が知り認めた子 · 終戦21日前に生まれる]]))
    content((13.4, -1.2), name: "duke3", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[現大公（第三代）ゲオルク＝グスタフ] \ #text(size: 5.1pt, fill: gray.darken(40%))[父ヴォロディミル（早世 †）· あの夜の馬車の群れ · 護衛兵力]]))
    content((16.3, -1.2), name: "duke2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[先代大公（第二代）オレクサ二世] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 毒殺（家族とともに）]]))
    content((13.4, -3.0), name: "police", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[国際警察] \ #text(size: 5.1pt, fill: gray.darken(40%))[緊急国際逮捕状 · 追撃 · 引き渡し]]))
    content((16.3, -3.0), name: "icc", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[（仮称）国際刑事裁判所] \ #text(size: 5.1pt, fill: gray.darken(40%))[逮捕状を発付]]))
    line("haru_par", "hein_par", stroke: (paint: black, thickness: .7pt))
    lbl((3.50, -1.20), [兄弟])
    line("haru_par", "haru", stroke: (paint: black, thickness: .7pt))
    line("haru_par", "haru_sis", stroke: (paint: black, thickness: .7pt))
    line("hein_par", "hein", stroke: (paint: black, thickness: .7pt))
    lbl((6.30, -2.10), [長男])
    line("hein_par", "six", stroke: (paint: black, thickness: .7pt))
    line("hein", "fran", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((8.90, -3.90), [幼馴染])
    line("hein", "frieda", stroke: (paint: black, thickness: .7pt))
    lbl((7.60, -4.75), [父])
    line("fran", "frieda", stroke: (paint: black, thickness: .7pt))
    line("duke3", "police", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("icc", "police", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((1.8, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの父 · 母] \ #text(size: 5.1pt, fill: gray.darken(40%))[新宗家当主（譲位）· 原作第8巻]]))
    content((5.2, -1.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハインリヒの父母] \ #text(size: 5.1pt, fill: gray.darken(40%))[旧宗家当主夫妻 · ハルの伯父伯母 · 極秘文書を作り封印]]))
    content((0.85, -3.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの姉] \ #text(size: 5.1pt, fill: gray.darken(40%))[† シュタウフェンで即死]]))
    content((2.85, -3.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハル] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ハルフレズ · 「学校」の学生 → 新宗家当主]]))
    content((7.4, -3.0), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハインリヒ] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト・ハインリヒ・カール † · 両親を知っていた人 · 両親の墓を作った · 処刑]]))
    content((4.5, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[弟たち六人] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 扉の前のスクラム · アンハルト家墓地]]))
    content((10.4, -4.8), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン先生] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」の教師 · ハインリヒの幼馴染 · 沈黙]]))
    content((7.8, -6.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[フリーダ] \ #text(size: 5.1pt, fill: gray.darken(40%))[ハインリヒの遺腹の娘 ―― 彼が知り認めた子 · 終戦21日前に生まれる]]))
    content((13.4, -1.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[現大公（第三代）ゲオルク＝グスタフ] \ #text(size: 5.1pt, fill: gray.darken(40%))[父ヴォロディミル（早世 †）· あの夜の馬車の群れ · 護衛兵力]]))
    content((16.3, -1.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[先代大公（第二代）オレクサ二世] \ #text(size: 5.1pt, fill: gray.darken(40%))[† 毒殺（家族とともに）]]))
    content((13.4, -3.0), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[国際警察] \ #text(size: 5.1pt, fill: gray.darken(40%))[緊急国際逮捕状 · 追撃 · 引き渡し]]))
    content((16.3, -3.0), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[（仮称）国際刑事裁判所] \ #text(size: 5.1pt, fill: gray.darken(40%))[逮捕状を発付]]))
    line((0.4, -7.949999999999999), (1.0, -7.949999999999999), stroke: (paint: black, thickness: .7pt))
    content((1.1, -7.949999999999999), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -7.949999999999999), (3.15, -7.949999999999999), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -7.949999999999999), (3.15, -7.949999999999999), stroke: (paint: white, thickness: .8pt))
    content((3.25, -7.949999999999999), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -7.949999999999999), (5.299999999999999, -7.949999999999999), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -7.949999999999999), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -7.949999999999999), (7.449999999999999, -7.949999999999999), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -7.949999999999999), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -7.949999999999999), (9.6, -7.949999999999999), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -7.949999999999999), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -7.949999999999999), (11.75, -7.949999999999999), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -7.949999999999999), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -7.949999999999999), (13.9, -7.949999999999999), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -7.949999999999999), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -7.949999999999999), (16.05, -7.949999999999999), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -7.949999999999999), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図④ 第三次継承戦争 ―― かたわらにいた人たち（2-2・2-5-c・5-6・第19.5話）。ハルの家とアンハルト家、フランとフリーダ、大公家と国際機関。⚠ この人たちは三姉妹の設計を知らない ―― ハインリヒとフランだけが一片ずつ知る。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[禁書戦争 ―― 「学校」とあの日])
    content((1.3, -1.2), name: "omi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[オミ先生] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」の教師]]))
    content((4.0, -1.2), name: "mimi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ミミ] \ #text(size: 5.1pt, fill: gray.darken(40%))[カガリ・ミミ · 不老不死（母の蘇生）]]))
    content((6.6, -1.2), name: "shina", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[シーナ] \ #text(size: 5.1pt, fill: gray.darken(40%))[トツキ・シーナ · 家門の外の孤児 · ミミの相方]]))
    content((9.2, -1.2), name: "laura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[シーナの元ルームメイト · 一話前に戦死 → 復活]]))
    content((11.8, -1.2), name: "ari", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランのルームメイト · あの夜馬車に]]))
    content((14.4, -1.2), name: "esta", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタ · ヘザー · リカ] \ #text(size: 5.1pt, fill: gray.darken(40%))[三人 · ヘザーは復活者]]))
    content((16.7, -1.2), name: "senpai", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[男子の先輩] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランが救った]]))
    content((4.0, -2.8), name: "mimi_mom", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[カガリ・マサコ（ミミの母）] \ #text(size: 5.1pt, fill: gray.darken(40%))[平民の未婚の母 · フラン逃走を助ける · † 命を使い果たして蘇生 · 第14話後編ブルーメンフルト合葬]]))
    content((10.1, -2.8), name: "clea", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[クレア（クーちゃん）· ほかの女子生徒 · 二話の子] \ #text(size: 5.1pt, fill: gray.darken(40%))[クレアはハルのルームメイト · 公共交通・都市工学の天賦の才 · 遷都・首都再整備・三国国際交通網を主導 · 終章〜未来編前編の間に自然死]]))
    content((2.6, -4.8), name: "relay", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[信号を繋いだ人々] \ #text(size: 5.1pt, fill: gray.darken(40%))[向こうの地下ジャーナリスト · 世界のジャーナリスト · 名なし · 何人もが †（3-6）]]))
    content((6.6, -4.8), name: "reporter", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[外信記者] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · 扉の外で見る顔 · 撮って持ち出した]]))
    content((10.2, -4.8), name: "crowd", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[デモ隊] \ #text(size: 5.1pt, fill: gray.darken(40%))[顔なし · 街 · セイランに道を]]))
    content((13.8, -4.8), name: "employees", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト宗家の被雇用者たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[ジギスムントをシュタウフェンで捕らえる]]))
    content((8.4, -6.6), name: "night", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 7.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[終戦の夜 ―― 0年4月7日] \ #text(size: 5.1pt, fill: gray.darken(40%))[暴露放送 · 六人の火刑 · エイランの消滅 · セイランの復活と初めての出会い · 二人の姉妹の十五歳の誕生日]]))
    line("mimi_mom", "mimi", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((4.00, -2.00), [蘇生])
    line("mimi", "shina", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((5.30, -1.20), [相方])
    line("shina", "laura", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((7.90, -1.20), [元ルームメイト])
    line("relay", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("reporter", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("crowd", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("employees", "night", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((1.3, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[オミ先生] \ #text(size: 5.1pt, fill: gray.darken(40%))[「学校」の教師]]))
    content((4.0, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ミミ] \ #text(size: 5.1pt, fill: gray.darken(40%))[カガリ・ミミ · 不老不死（母の蘇生）]]))
    content((6.6, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[シーナ] \ #text(size: 5.1pt, fill: gray.darken(40%))[トツキ・シーナ · 家門の外の孤児 · ミミの相方]]))
    content((9.2, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[メル・ラウラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[シーナの元ルームメイト · 一話前に戦死 → 復活]]))
    content((11.8, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[モード・アリ] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランのルームメイト · あの夜馬車に]]))
    content((14.4, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタ · ヘザー · リカ] \ #text(size: 5.1pt, fill: gray.darken(40%))[三人 · ヘザーは復活者]]))
    content((16.7, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[男子の先輩] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランが救った]]))
    content((4.0, -2.8), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[カガリ・マサコ（ミミの母）] \ #text(size: 5.1pt, fill: gray.darken(40%))[平民の未婚の母 · フラン逃走を助ける · † 命を使い果たして蘇生 · 第14話後編ブルーメンフルト合葬]]))
    content((10.1, -2.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 4.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[クレア（クーちゃん）· ほかの女子生徒 · 二話の子] \ #text(size: 5.1pt, fill: gray.darken(40%))[クレアはハルのルームメイト · 公共交通・都市工学の天賦の才 · 遷都・首都再整備・三国国際交通網を主導 · 終章〜未来編前編の間に自然死]]))
    content((2.6, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[信号を繋いだ人々] \ #text(size: 5.1pt, fill: gray.darken(40%))[向こうの地下ジャーナリスト · 世界のジャーナリスト · 名なし · 何人もが †（3-6）]]))
    content((6.6, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[外信記者] \ #text(size: 5.1pt, fill: gray.darken(40%))[名なし · 扉の外で見る顔 · 撮って持ち出した]]))
    content((10.2, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[デモ隊] \ #text(size: 5.1pt, fill: gray.darken(40%))[顔なし · 街 · セイランに道を]]))
    content((13.8, -4.8), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト宗家の被雇用者たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[ジギスムントをシュタウフェンで捕らえる]]))
    content((8.4, -6.6), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 7.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[終戦の夜 ―― 0年4月7日] \ #text(size: 5.1pt, fill: gray.darken(40%))[暴露放送 · 六人の火刑 · エイランの消滅 · セイランの復活と初めての出会い · 二人の姉妹の十五歳の誕生日]]))
    line((0.4, -8.15), (1.0, -8.15), stroke: (paint: black, thickness: .7pt))
    content((1.1, -8.15), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -8.15), (3.15, -8.15), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -8.15), (3.15, -8.15), stroke: (paint: white, thickness: .8pt))
    content((3.25, -8.15), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -8.15), (5.299999999999999, -8.15), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -8.15), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -8.15), (7.449999999999999, -8.15), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -8.15), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -8.15), (9.6, -8.15), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -8.15), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -8.15), (11.75, -8.15), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -8.15), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -8.15), (13.9, -8.15), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -8.15), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -8.15), (16.05, -8.15), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -8.15), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図⑤ 第三次継承戦争 ―― 「学校」とあの日（2-5・2-7・3-6）。兵器として育てられた子どもたちと彼らを教えた人、そして終戦の夜に外にいた人たち。⚠ 三姉妹がここにもいる（③参照）―― 同じ人が二つの図に出るのはこの図の形式である。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[戦争のあと ―― 裁判と姓の行方])
    content((1.6, -1.3), name: "judge", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[裁判長] \ #text(size: 5.1pt, fill: gray.darken(40%))[軍のない中立国の首長 · 大公国の出]]))
    content((5.0, -1.3), name: "thal6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ヴァルター・ハラルト六世] \ #text(size: 5.1pt, fill: gray.darken(40%))[終身刑（第14話後編後 ×8）· 画面にはナレーションの呼名一度だけ]]))
    content((8.6, -1.3), name: "sigis", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ヨアヒム・ジギスムント] \ #text(size: 5.1pt, fill: gray.darken(40%))[終身刑（×6→×8）· 面会室のガラスの向こう · 「どうか、長生きしてください」]]))
    content((12.2, -1.3), name: "spouses", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[二人の首班の配偶者たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[裁判を受け刑は異なる · 画面に上がらない（2-2）]]))
    content((15.6, -1.3), name: "witness", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[証言台の顔] \ #text(size: 5.1pt, fill: gray.darken(40%))[従兄弟たちの証言 · 大公家の人々とフランの証言（二つの虐殺）· あの日呼び出された人]]))
    content((3.2, -3.2), name: "cousT", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[父方の従兄弟たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[十四男（ホーエンマイセン＝タールベルク）後孫 · 姓を捨てる → 大公国が贈った姓「アンハルト＝ニーダーヴィッテンベルク」]]))
    content((7.0, -3.2), name: "cousB", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[母方の従姉妹たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[十四男（ホーエンマイセン＝ブルーメンタール）後孫 · ブルーメンタールベルクを受ける · 五親等の甥姪（弁護士、第20.7話）― 男子の先輩に法を学んだ]]))
    content((14.6, -3.2), name: "pres", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[男子の先輩 → 大統領] \ #text(size: 5.1pt, fill: gray.darken(40%))[少年兵 → 法学徒 → 人権弁護士 → ロースクール教授（碩座） → 最多選議員 → 大統領 · 任期中に逝去（第21話）†]]))
    content((1.6, -6.5), name: "haru", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハル] \ #text(size: 5.1pt, fill: gray.darken(40%))[新宗家当主 → 譲位]]))
    content((1.6, -5.0), name: "haru_par", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの父 · 母] \ #text(size: 5.1pt, fill: gray.darken(40%))[兄夫婦の墓を開けDNAで確認]]))
    content((5.0, -6.5), name: "fran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[第19.5話の告白 · 新宗家が家族として認める]]))
    content((9.1, -6.5), name: "frieda", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[フリーダ] \ #text(size: 5.1pt, fill: gray.darken(40%))[極秘文書でアンハルト＝ヘヒンゲン姓 · アンハルト＝ホーエンアスカニア＝ヘヒンゲン＝フェルデンブルク · のちに五つ子の一人と姻戚]]))
    line("judge", "thal6", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("judge", "sigis", stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    line("thal6", "cousT", stroke: (paint: black, thickness: .7pt))
    line("sigis", "cousB", stroke: (paint: black, thickness: .7pt))
    line("pres", "cousB", stroke: (paint: gray.darken(15%), thickness: .55pt))
    lbl((10.80, -3.20), [法を教えた])
    line("haru_par", "haru", stroke: (paint: black, thickness: .7pt))
    lbl((1.60, -5.75), [譲位])
    line("haru_par", "fran", stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    lbl((3.30, -5.75), [家族として認める])
    line("fran", "frieda", stroke: (paint: black, thickness: .7pt))
    content((1.6, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[裁判長] \ #text(size: 5.1pt, fill: gray.darken(40%))[軍のない中立国の首長 · 大公国の出]]))
    content((5.0, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[タールベルク・ヴァルター・ハラルト六世] \ #text(size: 5.1pt, fill: gray.darken(40%))[終身刑（第14話後編後 ×8）· 画面にはナレーションの呼名一度だけ]]))
    content((8.6, -1.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[ブルーメンタール・ヨアヒム・ジギスムント] \ #text(size: 5.1pt, fill: gray.darken(40%))[終身刑（×6→×8）· 面会室のガラスの向こう · 「どうか、長生きしてください」]]))
    content((12.2, -1.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[二人の首班の配偶者たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[裁判を受け刑は異なる · 画面に上がらない（2-2）]]))
    content((15.6, -1.3), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[証言台の顔] \ #text(size: 5.1pt, fill: gray.darken(40%))[従兄弟たちの証言 · 大公家の人々とフランの証言（二つの虐殺）· あの日呼び出された人]]))
    content((3.2, -3.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.7cm, align(center)[#text(size: 6.4pt, weight: "bold")[父方の従兄弟たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[十四男（ホーエンマイセン＝タールベルク）後孫 · 姓を捨てる → 大公国が贈った姓「アンハルト＝ニーダーヴィッテンベルク」]]))
    content((7.0, -3.2), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[母方の従姉妹たち] \ #text(size: 5.1pt, fill: gray.darken(40%))[十四男（ホーエンマイセン＝ブルーメンタール）後孫 · ブルーメンタールベルクを受ける · 五親等の甥姪（弁護士、第20.7話）― 男子の先輩に法を学んだ]]))
    content((14.6, -3.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[男子の先輩 → 大統領] \ #text(size: 5.1pt, fill: gray.darken(40%))[少年兵 → 法学徒 → 人権弁護士 → ロースクール教授（碩座） → 最多選議員 → 大統領 · 任期中に逝去（第21話）†]]))
    content((1.6, -6.5), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハル] \ #text(size: 5.1pt, fill: gray.darken(40%))[新宗家当主 → 譲位]]))
    content((1.6, -5.0), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[ハルの父 · 母] \ #text(size: 5.1pt, fill: gray.darken(40%))[兄夫婦の墓を開けDNAで確認]]))
    content((5.0, -6.5), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[フラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[第19.5話の告白 · 新宗家が家族として認める]]))
    content((9.1, -6.5), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[フリーダ] \ #text(size: 5.1pt, fill: gray.darken(40%))[極秘文書でアンハルト＝ヘヒンゲン姓 · アンハルト＝ホーエンアスカニア＝ヘヒンゲン＝フェルデンブルク · のちに五つ子の一人と姻戚]]))
    line((0.4, -7.75), (1.0, -7.75), stroke: (paint: black, thickness: .7pt))
    content((1.1, -7.75), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -7.75), (3.15, -7.75), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -7.75), (3.15, -7.75), stroke: (paint: white, thickness: .8pt))
    content((3.25, -7.75), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -7.75), (5.299999999999999, -7.75), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -7.75), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -7.75), (7.449999999999999, -7.75), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -7.75), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -7.75), (9.6, -7.75), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -7.75), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -7.75), (11.75, -7.75), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -7.75), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -7.75), (13.9, -7.75), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -7.75), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -7.75), (16.05, -7.75), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -7.75), anchor: "west", text(size: 5.8pt)[→ そのあと])
  }),
  caption: [人物関係図⑥ 禁書戦争のあと ―― 裁判と姓の行方（5-2・2-2・第19.5話）。二人の首班が並んで立ち、その下の世代が姓を捨てるか受け取る。フランとフリーダに来たものもここである。⚠ 人の少ない図であり、少ないことがこの場の性質である。],
  supplement: none,
  numbering: none,
)

#pagebreak()

#figure(
  canvas(length: 1cm, {
    import draw: *
    let lbl(p, s) = content(p, frame: "rect", fill: white, stroke: none, padding: (x: .04, y: .02), text(size: 5.2pt, fill: gray.darken(35%))[#s])
    content((8.9, 0.35), text(size: 8.5pt, weight: "bold")[関係と子どもたち、そして遠いあと])
    content((1.35, -1.2), name: "shina", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[シーナ]]))
    content((3.1, -1.2), name: "mimi", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ミミ]]))
    content((5.3, -1.2), name: "reiran", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイラン]]))
    content((7.05, -1.2), name: "laura", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ラウラ]]))
    content((9.25, -1.2), name: "seiran", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイラン]]))
    content((11.0, -1.2), name: "ari", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[アリ]]))
    content((13.2, -1.2), name: "esta", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタ]]))
    content((14.9, -1.2), name: "heather", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ヘザー]]))
    content((16.6, -1.2), name: "rika", frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[リカ]]))
    content((2.1, -4.3), name: "nine", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[九人の娘] \ #text(size: 5.1pt, fill: gray.darken(40%))[長女 → 大統領 · 末娘 → 大公国首相 · 中の七人はそれぞれ違う国で]]))
    content((6.2, -4.3), name: "d_rl", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイランの娘二人 · ラウラの娘二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[レイラン ― ラウラ・ミラン · アマリア・カラン（二卵性双生児）/ ラウラ ― アントニア二世 · ソフィア二世]]))
    content((11.2, -4.3), name: "d_sa", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 5.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイランの娘四人 · アリの娘二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイラン ― フリーデリケ・ルディ・スズラン · フリーダ・フェリシア・ジュラン（二卵性）· ハルフリート・マルガレーテ・ケイラン · アデラ・アリ・アイラン（一卵性）/ アリ ― レティシア三世 · プレシス二世]]))
    content((15.8, -4.3), name: "quint", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[五つ子の兄弟姉妹] \ #text(size: 5.1pt, fill: gray.darken(40%))[第22話の老人五人 · 一人がフリーダと姻戚（どちらかは定めない）]]))
    content((2.2, -6.7), name: "acting", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[権限代行 → 早期選挙] \ #text(size: 5.1pt, fill: gray.darken(40%))[当選者が直ちに就任（2-12）]]))
    content((6.4, -6.7), name: "funeral", frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[五重の国葬（+78年）] \ #text(size: 5.1pt, fill: gray.darken(40%))[大統領 · セイラン · レイラン · ラウラ · アリ]]))
    content((11.6, -6.7), name: "ferd", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト・フェルディナント] \ #text(size: 5.1pt, fill: gray.darken(40%))[ヘザー·リカが守った子 · ハルが養子に]]))
    content((14.9, -6.7), name: "fwife", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[妻 ― アデラ・アリ・アイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランの末娘 · セイランは七人の娘の母方の祖母（版1.69）]]))
    content((2.2, -10.1), name: "pres100", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[大統領（百年後）] \ #text(size: 5.1pt, fill: gray.darken(40%))[長女が当選のはるか前から数十年にわたって育てた後継者であり直後任]]))
    content((9.4, -10.1), name: "premier", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[大公国首相（百年後）] \ #text(size: 5.1pt, fill: gray.darken(40%))[九番目]]))
    content((13.4, -10.1), name: "seven", frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 4.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[七人の娘] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ブルーメンタールベルク ハイケ・カルラ一世 · フェルディナンダ・ハイデ一世 · アリス・リカ · シルヴィア・エスタ一世 · カトリナ・エイラン · エミリア・レイラン · ミア・レナ・セイラン · 百年後のあの場に全員]]))
    content((1.9, -12.7), name: "duke3", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[現大公（第三代）] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・ゲオルク＝グスタフ · ヘザーとリカの棺を載せて行き急死 †]]))
    content((6.6, -12.7), name: "duke4", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[第四代女大公] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・カタリーナ＝テレジア・エリザベト · 現大公の次女 · 生涯独身 · 五つ子に合葬を提案]]))
    content((11.0, -12.7), name: "duke5", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[第五代女大公ナターシャ二世] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・ナターシャ二世 · 第四代の養女（長女の一人娘 · 生後二か月で養子）]]))
    content((15.3, -12.7), name: "duke6", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[第六代女大公アガタ一世 · 黒人国婿] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・アガタ一世（第五代の一人娘 · 未来編直前に譲位）· 国婿はとてつもない親バカ]]))
    content((1.35, -15.1), name: "ferd2", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[二代記録館長] \ #text(size: 5.1pt, fill: gray.darken(40%))[フェルディナント · 百年後に掘る]]))
    content((4.45, -15.1), name: "desc", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイランの女系子孫] \ #text(size: 5.1pt, fill: gray.darken(40%))[mtDNA照合]]))
    content((7.85, -15.1), name: "males", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[純粋な男系二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[大公国の人 · このYだけが使える ― 他のYは養子ゆえ不可]]))
    content((11.35, -15.1), name: "envoy", frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[使節団 · ヘリの撮影記者]]))
    content((15.3, -15.1), name: "duke7", frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[指名継承者 ― アガタ・ナラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・アガタ・ナラ · 初の黒白混血当主予定 · 次女（姉と二卵性双生児）· 幼年期船上生活 · 国際求婚殺到]]))
    line("funeral", "acting", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    line("nine", "acting", stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((2.15, -5.50), [長女が当選])
    line((2.1, -4.9), (2.1, -5.4), (9.4, -5.4), (9.4, -9.5), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    lbl((5.75, -5.40), [末娘])
    line("duke3", "duke4", stroke: (paint: black, thickness: .7pt))
    lbl((4.25, -12.70), [次女])
    line("duke4", "duke5", stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    lbl((8.80, -12.70), [指名])
    line("duke5", "duke6", stroke: (paint: black, thickness: .7pt))
    lbl((13.15, -12.70), [譲位])
    line("duke6", "duke7", stroke: (paint: black, thickness: .7pt))
    lbl((15.30, -13.90), [指名（次女）])
    line("ferd2", "desc", stroke: (paint: gray.darken(15%), thickness: .55pt))
    line("desc", "males", stroke: (paint: gray.darken(15%), thickness: .55pt))
    line("shina", (2.2, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("mimi", (2.2, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((2.2, -2.75), "nine", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((2.2, -2.75), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    line("reiran", (6.2, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("laura", (6.2, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((6.2, -2.75), "d_rl", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((6.2, -2.75), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    line("seiran", (9.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("ari", (9.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((9.9, -2.75), "d_sa", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((9.9, -2.75), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    line("esta", (14.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("heather", (14.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("rika", (14.9, -2.75), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((14.9, -2.75), "quint", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((14.9, -2.75), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    lbl((15.52, -2.75), [三人])
    line("ferd", (13.4, -8.6), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line("fwife", (13.4, -8.6), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt))
    line((13.4, -8.6), "seven", stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((13.4, -8.6), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    content((1.35, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[シーナ]]))
    content((3.1, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ミミ]]))
    content((5.3, -1.2), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイラン]]))
    content((7.05, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ラウラ]]))
    content((9.25, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイラン]]))
    content((11.0, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[アリ]]))
    content((13.2, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[エスタ]]))
    content((14.9, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[ヘザー]]))
    content((16.6, -1.2), frame: "rect", fill: rgb("#eaf2ee"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 1.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[リカ]]))
    content((2.1, -4.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[九人の娘] \ #text(size: 5.1pt, fill: gray.darken(40%))[長女 → 大統領 · 末娘 → 大公国首相 · 中の七人はそれぞれ違う国で]]))
    content((6.2, -4.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[レイランの娘二人 · ラウラの娘二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[レイラン ― ラウラ・ミラン · アマリア・カラン（二卵性双生児）/ ラウラ ― アントニア二世 · ソフィア二世]]))
    content((11.2, -4.3), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 5.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイランの娘四人 · アリの娘二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイラン ― フリーデリケ・ルディ・スズラン · フリーダ・フェリシア・ジュラン（二卵性）· ハルフリート・マルガレーテ・ケイラン · アデラ・アリ・アイラン（一卵性）/ アリ ― レティシア三世 · プレシス二世]]))
    content((15.8, -4.3), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[五つ子の兄弟姉妹] \ #text(size: 5.1pt, fill: gray.darken(40%))[第22話の老人五人 · 一人がフリーダと姻戚（どちらかは定めない）]]))
    content((2.2, -6.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.9cm, align(center)[#text(size: 6.4pt, weight: "bold")[権限代行 → 早期選挙] \ #text(size: 5.1pt, fill: gray.darken(40%))[当選者が直ちに就任（2-12）]]))
    content((6.4, -6.7), frame: "rect", fill: rgb("#fdecea"), stroke: (paint: red.darken(15%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.1cm, align(center)[#text(size: 6.4pt, weight: "bold")[五重の国葬（+78年）] \ #text(size: 5.1pt, fill: gray.darken(40%))[大統領 · セイラン · レイラン · ラウラ · アリ]]))
    content((11.6, -6.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.8cm, align(center)[#text(size: 6.4pt, weight: "bold")[アンハルト・フェルディナント] \ #text(size: 5.1pt, fill: gray.darken(40%))[ヘザー·リカが守った子 · ハルが養子に]]))
    content((14.9, -6.7), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[妻 ― アデラ・アリ・アイラン] \ #text(size: 5.1pt, fill: gray.darken(40%))[セイランの末娘 · セイランは七人の娘の母方の祖母（版1.69）]]))
    content((2.2, -10.1), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[大統領（百年後）] \ #text(size: 5.1pt, fill: gray.darken(40%))[長女が当選のはるか前から数十年にわたって育てた後継者であり直後任]]))
    content((9.4, -10.1), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.0cm, align(center)[#text(size: 6.4pt, weight: "bold")[大公国首相（百年後）] \ #text(size: 5.1pt, fill: gray.darken(40%))[九番目]]))
    content((13.4, -10.1), frame: "rect", fill: rgb("#fbfbfb"), stroke: (paint: gray.darken(20%), thickness: .5pt, dash: "dashed"), padding: (x: .08, y: .06), box(width: 4.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[七人の娘] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ブルーメンタールベルク ハイケ・カルラ一世 · フェルディナンダ・ハイデ一世 · アリス・リカ · シルヴィア・エスタ一世 · カトリナ・エイラン · エミリア・レイラン · ミア・レナ・セイラン · 百年後のあの場に全員]]))
    content((1.9, -12.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[現大公（第三代）] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・ゲオルク＝グスタフ · ヘザーとリカの棺を載せて行き急死 †]]))
    content((6.6, -12.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[第四代女大公] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・カタリーナ＝テレジア・エリザベト · 現大公の次女 · 生涯独身 · 五つ子に合葬を提案]]))
    content((11.0, -12.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[第五代女大公ナターシャ二世] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・ナターシャ二世 · 第四代の養女（長女の一人娘 · 生後二か月で養子）]]))
    content((15.3, -12.7), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.3cm, align(center)[#text(size: 6.4pt, weight: "bold")[第六代女大公アガタ一世 · 黒人国婿] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・アガタ一世（第五代の一人娘 · 未来編直前に譲位）· 国婿はとてつもない親バカ]]))
    content((1.35, -15.1), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[二代記録館長] \ #text(size: 5.1pt, fill: gray.darken(40%))[フェルディナント · 百年後に掘る]]))
    content((4.45, -15.1), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.4cm, align(center)[#text(size: 6.4pt, weight: "bold")[セイランの女系子孫] \ #text(size: 5.1pt, fill: gray.darken(40%))[mtDNA照合]]))
    content((7.85, -15.1), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 3.2cm, align(center)[#text(size: 6.4pt, weight: "bold")[純粋な男系二人] \ #text(size: 5.1pt, fill: gray.darken(40%))[大公国の人 · このYだけが使える ― 他のYは養子ゆえ不可]]))
    content((11.35, -15.1), frame: "rect", fill: rgb("#f1f1f1"), stroke: (paint: gray.darken(30%), thickness: .5pt), padding: (x: .08, y: .06), box(width: 2.6cm, align(center)[#text(size: 6.4pt, weight: "bold")[使節団 · ヘリの撮影記者]]))
    content((15.3, -15.1), frame: "rect", fill: rgb("#eef0f5"), stroke: (paint: black, thickness: .55pt), padding: (x: .08, y: .06), box(width: 3.5cm, align(center)[#text(size: 6.4pt, weight: "bold")[指名継承者 ― アガタ・ナラ] \ #text(size: 5.1pt, fill: gray.darken(40%))[アンハルト＝ヴィッテンベルク・アガタ・ナラ · 初の黒白混血当主予定 · 次女（姉と二卵性双生児）· 幼年期船上生活 · 国際求婚殺到]]))
    line((0.4, -16.75), (1.0, -16.75), stroke: (paint: black, thickness: .7pt))
    content((1.1, -16.75), anchor: "west", text(size: 5.8pt)[血縁])
    line((2.55, -16.75), (3.15, -16.75), stroke: (paint: black, thickness: 1.7pt))
    line((2.55, -16.75), (3.15, -16.75), stroke: (paint: white, thickness: .8pt))
    content((3.25, -16.75), anchor: "west", text(size: 5.8pt)[婚姻])
    line((4.699999999999999, -16.75), (5.299999999999999, -16.75), stroke: (paint: black, thickness: .7pt, dash: "dash-dotted"))
    content((5.3999999999999995, -16.75), anchor: "west", text(size: 5.8pt)[養子・育てた人])
    line((6.85, -16.75), (7.449999999999999, -16.75), stroke: (paint: gray.darken(15%), thickness: .55pt))
    content((7.55, -16.75), anchor: "west", text(size: 5.8pt)[師弟・同級])
    line((9.0, -16.75), (9.6, -16.75), stroke: (paint: gray.darken(15%), thickness: .55pt, dash: "dashed"))
    content((9.7, -16.75), anchor: "west", text(size: 5.8pt)[職務])
    line((11.15, -16.75), (11.75, -16.75), stroke: (paint: blue.darken(20%), thickness: .7pt), mark: (end: ">", fill: blue.darken(20%), scale: .5))
    content((11.85, -16.75), anchor: "west", text(size: 5.8pt)[恩人])
    line((13.3, -16.75), (13.9, -16.75), stroke: (paint: red.darken(15%), thickness: .7pt), mark: (end: ">", fill: red.darken(15%), scale: .5))
    content((14.0, -16.75), anchor: "west", text(size: 5.8pt)[殺害])
    line((15.450000000000001, -16.75), (16.05, -16.75), stroke: (paint: gray.darken(35%), thickness: .6pt, dash: "dotted"), mark: (end: ">", fill: gray.darken(35%), scale: .45))
    content((16.150000000000002, -16.75), anchor: "west", text(size: 5.8pt)[→ そのあと])
    line((0.4, -17.25), (1.0, -17.25), stroke: (paint: rgb("#2f6f4e"), thickness: .8pt), mark: (end: ">", fill: rgb("#2f6f4e"), scale: .5))
    circle((0.62, -17.25), radius: .085, fill: rgb("#2f6f4e"), stroke: none)
    content((1.1, -17.25), anchor: "west", text(size: 5.8pt)[関係（集合）→ 子どもたち])
  }),
  caption: [人物関係図⑦ 関係と子どもたち、そして遠いあと（2-11・2-12・第20話・第21話・百年後の未来編）。★ 四つの組とフェルディナント一家を同じ図形で描く ―― 有向ハイパーエッジ（緑、トピックマップのassociationの形式）: ハブ一つがその関係であり、そこから子どもたちへ矢印が一本出る。⚠ 出発点の集合の中を図形が分けない（誰が産んだかを言わない ― 版2.3.1）· 到着点は数だけあり名がない（誰がその子かを確定しない）· 異性の組にも同じ図形を使う。⚠ 娘たちの名は原典の表のままであり（版2.3.44で復元した ― ⑦の図を新たに作るとき落ちていた）、下の段は大公家の継承である。],
  supplement: none,
  numbering: none,
)
